### ISSUE TITLE
command not found `options`

### ISSUE THREAD

**Issue by joshuef** [rbreaves/kinto#10]
postinstall, running the commands, I'm getting an error re: `options` command not existing on Ubuntu 19.04

```options hid_apple swap_opt_cmd="1" | sudo tee -a /etc/modprobe.d/hid_apple.conf
zsh: correct 'options' to '_options' [nyae]? n
zsh: command not found: options
```
Performance has been flaky (not applied after reboot), so I came back to uninstall/reinstall and saw i missed this lasttime. 

Googling around I can't readily see what package to install to get an `options` command... Any advice would be appreciated!

**Comment by rbreaves** [comment]
Sounds like that would be related to the setxkbmap or xkbcomp command as they have an options argument. I've not ran into this problem though, so I am not sure why it'd be an issue in 19.04. Perhaps it is an issue created by zsh, I also use zsh, but the scripts define bash so again this is odd.

**Comment by joshuef** [comment]
ahh, you know what it is: atm the command is printed out thus:
`options hid_apple swap_opt_cmd=1" | sudo tee -a /etc/modprobe.d/hid_apple.conf`

it's missing an initial `"`.

So I believe should be: 

`"options hid_apple swap_opt_cmd=1" | sudo tee -a /etc/modprobe.d/hid_apple.conf`

**Comment by joshuef** [comment]
Ah, also the final command printed out: `update-initramfs -u -k all` may need to be `sudo` (it was for me)

**Comment by joshuef** [comment]
Just one last note: thanks! :D this is making my dev life _so much nicer_. :+1: good work.

**Comment by rbreaves** [comment]
Thanks, if you have any more problems or suggestions for improvements don't hesitate to open a new ticket.
