### ISSUE TITLE
Kinto not starting - Debian 10 1.0.6-4

### ISSUE THREAD

**Issue by argeas** [rbreaves/kinto#108]
**Describe the bug**
1 - Fresh install of Debian 10.3
2 - I follow the installation guide
3-  Kinto seems to not be active, although after installing it, the windows key stoped working as it normally does
.

**Install Type:** Bare Metal or VM
**Distro:** Debian 10.3
**DE:** Gnome, XFCE, KDE
**Branch:** master
**Commit:** 9a451bd

**Kinto Input Caret Status**
```
cat /tmp/kinto/caret
```
1
**Kinto Standard Log**
```
journalctl --user-unit=keyswap.service -b
```
No logs
**Kinto Debug Log (1.0.6-2+)**
```
systemctl --user stop keyswap
cd ~/.config/kinto
./kintox11 --debug
```
Running in debug mode
Data from user_config.json imported susccesfully
Running init command: gsetting set org.gnome.mutter overlay-key ' '
Starting keyswap...

   get focus window
-: event: 0, windows_id: 0
*no focus window, e.type: 0, current_app

**Screenshots**

**Additional context**

**Comment by rbreaves** [comment]
That does seem odd. I will install Debian in a VM and test this out. Thanks for the feedback.

**Comment by rbreaves** [comment]
@argeas Can you make sure you are running under X11? When I run Debian 10 with Gnome under x11 it appears to run fine, but yes - if you are under Wayland it will fail and should fail to install in the first place if you are on Wayland.

**Comment by argeas** [comment]
Hi ! thanks for the reply, Indeed , wayland seemed to be the issue ! thanks ! will close the bug :)
