### ISSUE TITLE
nautilus go up folder cmd + up doesnt work

### ISSUE THREAD

**Issue by medyagh** [rbreaves/kinto#118]
on ubuntu 20.04 inside nautilus  the alt or cmd arrows do not work to navigate up or down

![Screenshot from 2020-04-19 16-58-17](https://user-images.githubusercontent.com/4564227/79703211-34f1fe80-825f-11ea-9108-c738af2c5fdb.png)

could be a regression of this issue ? https://github.com/rbreaves/kinto/issues/2

**Comment by rbreaves** [comment]
I assume keeping it in the cmd key position would be the preferred option? If macs Finder has an equivalent I'd use that, but not sure if they do.

**Comment by medyagh** [comment]
currently none of them work on ubuntu with kinto,
niether alt arrow or cmd arrow or ctrl arrow

my preference would be cmd UP for go up
and cmd left for go back

**Comment by rbreaves** [comment]
Ok, I will look at adding it tomorrow or you can also just checkout the latest and new alpha branch and install the xkeysnail version of kinto.

```
git pull
git checkout alpha
./xkeysnail_service.sh
```

That will replace the xkb/kintox11 version of Kinto and you can also add new keymaps in this file here.
```
~/.config/kinto/kinto.py
```

Also the new service can be controlled via this
```
sudo systemctl start xkeysnail
sudo systemctl status xkeysnail
sudo systemctl stop xkeysnail

# monitor
journalctl -l --unit=xkeysnail.service -b
```

If you want to see more output just stop the service then run the config directly.
```
sudo systemctl stop xkeysnail
sudo xkeysnail --watch ~/.config/kinto/kinto.py
```

**Comment by rbreaves** [comment]
@medyagh I haven't forgot about you. I got most of the xkeysnail implementation worked out and up on the dev branch now. I will probably take a look at this ticket and a few others in the coming days, but you can also make a PR if you want.

xkeysnail makes adding the desired hotkeys you want a snap, once you know the wm_class name. (aka use xprop --spy or something similar) and then update the ./xkeysnail-config/kinto.py file. Info is in the readme on the dev branch as well.

```
# Keybindings for Sublime Text
define_keymap(re.compile("Sublime_text"),{
    K("C-h"): pass_through_key,          # cancel replace
    K("C-M-f"): K("C-h"),                # replace
    K("C-M-v"): [K("C-k"), K("C-v")],    # paste_from_history
}
```

**Comment by rbreaves** [comment]
Also to note nautilus keymaps would either supersede wordwise outright or need to be added in a way that allows for both wordwise and nautilus keymaps, so it could actually be a more difficult keymap to implement than I first assumed.

I would think your Super key or Alt key on a mac keyboard would still function though, so the middle key rather even with no keymap, but my preference would be to bring it back to the Cmd key position normally and keep wordwise.

**Comment by rbreaves** [comment]
Closing. I don't think wordwise is that important for Nautilus so I am going to call this done.

Besides that I am not yet happy with the dynamic wordwise solution for the browsers as it sometimes causes modifier keys to stick after browser usage (all depends on timing). I will likely need to integrate it into a custom fork of xkeysnail. I doubt I will package it in a way that make it into the actual program as it is a niche feature I don't think anyone else would want.
