### ISSUE TITLE
What is the key mapping with Super + Direction keys in Ubuntu

### ISSUE THREAD

**Issue by tly1980** [rbreaves/kinto#119]
Kinto is really a brilliant app, which broughts back my mac keybroad.
However, I have some quesionts around the ubuntu window short cut:

Ubuntu allows you to do super + up / down to maximize window / revert maximize
super + left to move window to left most or right most.

What is the key mapping for that in Kinto ?

Thank you so much.

**Comment by rbreaves** [comment]
Thanks, I plan to be making another update soon to move things over to xkeysnail over xkb as it will increase compatibility and make it easier for others to add new hotkeys over xkb. I will likely keep both methods available though, at least for awhile so if one doesn't work out well for someone they can always try the other. XKB works well enough with a single exception from my perspective (KDE AltTab), but xkeysnail uses udev and thus is lower level and can allow for more complicated keymaps while making the config easier at the same time.

Maximize App = Ctrl+Cmd+F (Alt+F10)
Minimize = Cmd+H (Alt+F9)

Shortcut Translation Table
https://github.com/rbreaves/kinto/issues/44

I don't mind bringing back the original keymaps, assuming they do not conflict with others. It is particularly easy to do under Gnome as it supports multiple hotkeys the best.

The shortcut keys start at line 54.
https://github.com/rbreaves/kinto/blob/master/setup.py

**Comment by rbreaves** [comment]
Closing ticket, I believe that my response answered the question and even if it didn't the ticket #44 has a complete table of the system level shortcuts that Kinto currently covers, with the exception of apps like Sublime or VS Code. Most of Sublime is covered, but VS Code probably still needs some shortcuts keys fleshed out by me or a user via PR.
