### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by yctn** [rbreaves/kinto#12]
./install.py 

                      Kint◎
            - F!x the dɑmn kɐyb◎ɑrd. - 

Press Enter to begin...

What type of keyboard are you using? (If Mac and Windows then select Mac)
    1) Windows
    2) Chromebook
    3) Mac
3

Would you like to swap Command back to Super/Win and Ctrl key back to Ctrl when using terminal applications? (y/n)
Note: For a more mac like experience & less issues with terminal based interactions y is recommended.
y
Apple hid_apple driver is not loaded, a keymap that is specific for only Apple keyboards will be used.
Setting up mac_only keyswap as a service.
You can disable and remove the service by using the following command in the Kinto directory.
./uninstall.sh
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Traceback (most recent call last):
  File "./install.py", line 176, in <module>
    keyboard_detect()
  File "./install.py", line 90, in keyboard_detect
    subprocess.check_output(keyswapcmd, shell=True).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/bin/bash -c "./keyswap_service.sh 1 0 mac_only 0 0 0"' returned non-zero exit status 1.

What could i be doing wrong here?

**Comment by rbreaves** [comment]
Make sure you have bash installed? And or that it is in or linked to the typical /bin/bash location? I could rewrite it to reference bash regardless of its home directory, but typically it is located in bin.

**Comment by yctn** [comment]
im running it from zsh not from bash. could this be the issue?

**Comment by rbreaves** [comment]
Have you tried any further attempts at getting this to work? What OS are you running, perhaps I can install it as well and test it out.

**Comment by rbreaves** [comment]
Closing ticket, I assume this is no longer an issue or a local and isolated issue.
