### ISSUE TITLE
Shortcut found twice in kglobalshortcutsrc when running setup.py

### ISSUE THREAD

**Issue by Jonchun** [rbreaves/kinto#120]
**Describe the bug**
I don't know exactly when this happens, but sometimes I've noticed that I get the following warning/error when running `setup.py`.
![image](https://user-images.githubusercontent.com/5800539/80136850-49d8d580-8570-11ea-965d-258159b6d126.png)

**Expected behavior**
Not sure why this error message pops up, but I would expect to not have duplicate shortcuts?

**Install Type:** VM
**Distro:** KDE Neon 5.18.4
**DE:** KDE
**Branch:** master
**Commit:** 08e5a01

**Comment by rbreaves** [comment]
Hmmm.. I am not entirely sure the related segment of code in the setup file is the following, but it should be setting existing keys, not creating duplicate ones. I am not even editing the file directly, but rather via the official means to do so.

```
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Switch to Previous Desktop" "Meta+Left,Meta+Left,Switch to Previous Desktop"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Window Operations Menu" "none,Alt+F3,Window Operations Menu"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows" "Ctrl+F13,Alt+Tab,Walk Through Windows"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows Alternative" "none,none,Walk Through Windows"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Walk Through Windows (Reverse)" "Ctrl+Shift+F14,Alt+Shift+Backtab,Walk Through Windows (Reverse)"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Maximize Window" "none,Meta+PgUp,Maximize Window"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Window Maximize" "Meta+Ctrl+F,Alt+F10,Maximize Window"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Minimize Window" "Meta+h,Meta+PgDown,Minimize Window"')
			cmdline('kwriteconfig5 --file "$HOME/.config/kglobalshortcutsrc" --group "kwin" --key "Switch to Next Desktop" "Meta+Right,Meta+Right,Switch to Next Desktop"')
```

**Comment by rbreaves** [comment]
You could try running the uninstaller first and resetting the system shortcuts to their defaults and then trying it again. I'd be curious to know if that appears when doing a fresh install or when you install kinto on top of itself.

The most odd shortcut I set is.. Maximize Window and to be honest I am not sure why this exists twice sorta, but I believe that it could be erroneous. I thought these were default shortcut settings still.. unless I created the duplicate (in which case it would not show up after an uninstall.).

"Maximize Window" "none,Meta+PgUp,Maximize Window"
"Window Maximize" "Meta+Ctrl+F,Alt+F10,Maximize Window"

**Comment by Jonchun** [comment]
> You could try running the uninstaller first and resetting the system shortcuts to their defaults and then trying it again. I'd be curious to know if that appears when doing a fresh install or when you install kinto on top of itself.

I'll give this a shot, but unsure of if it'll make a difference since this happens on a "Fresh install". I have a snapshot of my VM that I restore to when testing my setup scripts and I'm running it against that snapshot.

**Comment by rbreaves** [comment]
I know.. I still need to fix this lol. I am tired tonight though. I have updated the main branch though as I feel like the installer for xkeysnail is where it needs to be for a release. I have tested it in all of the distros I normally test in. Fedora and RHEL might not work though.. and I do not know why. I am kinda wondering if my install is just borked, it should work tbh.

@Jonchun If you want to test out the latest you can. Also added VS Code remaps that work without modifying VS Code any at all thankfully. Wordwise was tough getting to work in there.

**Comment by Jonchun** [comment]
I just saw this. Got lost in my emails. I haven't even had a chance to boot into my linux desktop in the last few days so haven't used it much. I will say that I've been running the dev branch (xkeysnail) on Ubuntu 20.04 and it has been working great. So great in fact that other software is breaking noticeably yet kinto runs fine. I'm pretty excited to swap back to my desktop and try giving kinto another go with the keysnail stuff. I'd like to make a game soon-ish and given the amount of window switching/hotkey using I'll be doing I'm sure it'll serve as a pretty rigorous test in stability.

**Comment by Jonchun** [comment]
I gave this another run on KDE Neon on the most recent master branch and can confirm the problem still exists.

Unsure of how much value I can provide with VS Code remaps since I don't use it :(

**Comment by rbreaves** [comment]
Shortcut key additions no longer occur unless they do not exist at all. Closing for now as of v1.2 release.
