### ISSUE TITLE
Opening a new window sometimes does not change keymaps

### ISSUE THREAD

**Issue by fratajczak** [rbreaves/kinto#121]
**Describe the bug**
When opening a new window, keyswap does not detect it and keeps the current keymap (happens ~50% of the time).
The same problem also occurs much less frequently when switching windows (~5% of the time).

**Expected behavior**
The keymap changes when opening a new window.

**Install Type:** Bare Metal
**Distro:** Fedora 31
**DE:** Gnome 3.34.5
**Branch:** master and dev
**Commit:** 08e5a01 and 079cb6e

**Kinto Input Caret Status**
```
2
```

**Kinto Standard Log**
```
Apr 25 16:54:09 pc bash[2640]: term: kitty
<opening a new firefox window, no log event>
<minimize firefox window, refocus it, log below appears>
Apr 25 16:54:20 pc bash[2640]: firefox: Firefox
```
**Kinto Debug Log (1.0.6-2+)**
```
term: kitty
run: xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.term $DISPLAY 2>&1 | grep -v XF86FullScreen
Running de term command: gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['<Control><Shift>Space']"
<opening firefox window here>
event: ConfigureNotify 22
  duration: 7870ms

  get focus window
  -kitty: event: 22, window_id: 50331662

  get top window
  -kitty: event: 22, window_id: 50331662,4198857

  get named window
  -kitty: event: 22, window_id: 50331662

<no log event for firefox window, keymap is still term>
```

**Comment by rbreaves** [comment]
That's odd.. I will have to test this out under fedora I suppose. I already have a fedora 31 vm I use for testing. I am surprised you'd run into issues with that high of frequency tbh. I will report back in a bit.

I also have an Alpha branch you might be interested in checking out, it does not use kintox11 at all as I will be offering xkeysnail (udev) as the recommended install option for Kinto, but I still plan to do bug fixes on kintox11 and maintain the xkb method as well, it just won't be the primary focus.

**Comment by rbreaves** [comment]
@fratajczak The dev branch now has an updated ./setup.py installer and I believe I have worked out most issues with the xkeysnail implementation.

Caret/Input checking for Firefox and Chrome to have proper Back/Forward buttons is a little buggy, but it generally works. Updating xkeysnail to detect the keymap change natively though, instead of restarting the service would be ideal.

**Comment by rbreaves** [comment]
It's probably related to an IBus issue, which I just worked out for fedora 31, I will need to fix the installer, but manually you can do this below. I would also checkout the latest from dev though if you want to use the xkb implementation (even though xkeysnail is at parity besides reliable back/forward hotkeys in firefox and chrome).

Try the following
```
sudo dnf install im-chooser imsettings imsettings-gsettings
# maybe skip this one initially
# sudo dnf install uim

# reboot, then run the following
im-chooser
# Go to Input Method tab and set your language

# logoff and back on
# switch between a couple of apps and see if it is working better

# If it does not work then you might need to reboot or set im-chooser again
im-chooser
# Make sure it highlighted/selected
# test it, but if it does not work then logoff or reboot again

# You can also try running this and see what it spits out.
# Should see various numbers as you select input fields in apps such as 1, 2, 14, etc
IBUSADD=$(cat ~/.config/ibus/bus/`ls ~/.config/ibus/bus -1rt | tail -n1` | awk -F'IBUS_ADDRESS=' '{print $2}' | xargs)
dbus-monitor --address $IBUSADD "path='/org/freedesktop/IBus/Panel',interface='org.freedesktop.IBus.Panel',member='FocusOut'" 2> /dev/null | grep --line-buffered -o -P '(?<=object path \"/org/freedesktop/IBus/InputContext_).*(?=[\"])'
```

<img width="492" alt="Screen Shot 2020-04-28 at 4 27 20 PM" src="https://user-images.githubusercontent.com/10969616/80541292-85104580-8970-11ea-9577-ff4428ff7afe.png">
<img width="737" alt="Screen Shot 2020-04-28 at 4 28 00 PM" src="https://user-images.githubusercontent.com/10969616/80541300-8a6d9000-8970-11ea-8621-fcf9632ccf55.png">

**Comment by rbreaves** [comment]
Since I can't recreate this issue (pre IBus fix or after) and I have had no further feedback I will be closing this bug for now.
