### ISSUE TITLE
USB device input freezes after reboot

### ISSUE THREAD

**Issue by markogresak** [rbreaves/kinto#128]
When I install kinto, it's working correctly right away. But after rebooting the machine, all USB input freezes, even the USB mouse stops working. The only thing I was able to do is to use the hardware power button to reboot the machine and remove the configuration from the recovery boot.

When digging through the `/var/log/syslog`, I found this line, which might be of interest:
```
pop-os kinto.desktop[2281]: /bin/sleep: unrecognized option '--user'
pop-os kinto.desktop[2281]: Try '/bin/sleep --help' for more information.
```

But I can't find where is `sleep --user` called.

To be sure, I have pulled out and tested `sleep_ms` separately with same Makefile, and it works as expected when I run the binary. 

I thought it might be related to the binary, so I've rebuilt it on my machine and reinstalled kinto, but I still hit the same problem after rebooting. 

---

**Install Type:** Bare Metal
**Distro:** PopOS 19.10
**DE:** Gnome
**Branch:** master
**Commit:** 701bf25c699d8485165b7eab78d75b0e8257823d

Other info: 
- System input is English (US) with Emacs input and Caps lock = Esc tweaks
- Windows ([ISO](https://en.wikipedia.org/wiki/ISO/IEC_9995#ISO/IEC_9995-10)) keyboard (104 keys)
- Applied the default options and suggested tweaks for gnome

**Kinto Input Caret Status**

The `/tmp/kinto` folder does not exist. In some cases it did, but it was empty.

**Kinto Debug Log (1.0.6-2+)**

Running the script directly works, and it also works well immediately after the install. I have also tried by modifying the script to run it with `--debug` flag but I did not find anything useful by grepping the `syslog` for `kinto|keyswap`.
Due to the nature of the problem, I can't go and run the script when I experience the problem.

**Comment by rbreaves** [comment]
That is strange, I’ll review all sleep commands in a bit but it sounds like sleep is seeing the systemctl —user switch, it shouldn’t be doing that.

**Comment by rbreaves** [comment]
Also the dev branch has an xkeysnail implementation that you could run (w/o experimental back/forward hotkeys).

**Comment by rbreaves** [comment]
Ok, I have updated the sleep command in a couple of ways after reviewing my code.. It had appeared to be working for me during my reboot and login tests previously, so I am surprised it hadn't been a problem for me actually.

This latest hotfix commit that I have merged into both master and dev should fix the xkb version of Kinto. Xkeysnail was unaffected as its process to run and start up is different enough that the sleep command isn't required at all.

https://github.com/rbreaves/kinto/commit/76e69ecc251ec0a8e372fd64c56dfe9044dccfc2

I will close this ticket once I hear back.

**Comment by markogresak** [comment]
I have tested the `dev` branch and it works well there. 

I haven’t tested the master with latest hotfix. If you want, I can test it for you.

I’m happy with how the `dev` branch is working so I’m closing this issue. 

Thank you for the quick answer :+1:

**Comment by rbreaves** [comment]
Np, and I am pretty confident the hotfix resolves the xkb Kinto issue as well. I am surprised I didn't catch it sooner tbh, so I am glad you reported it. I will be merging dev into master soon and hopefully have most users convert to the xkeysnail method going forward.
