### ISSUE TITLE
Is this service expected to work after restart and for every terminal session?

### ISSUE THREAD

**Issue by dijs** [rbreaves/kinto#14]
I am currently having to re-install each time I open a terminal window and after every restart.

Do I need to install this differently?

**Comment by rbreaves** [comment]
That is odd. It should just work on Ubuntu 18.04 and derivatives. What OS are you running? Is it using systemd?

**Comment by rbreaves** [comment]
I am not sure what would be causing that issue for you, but if you are on a debian/ubuntu 18.04+ based OS you can try the latest version I have in the dev branch.

The dev branch now has a custom kintox11 binary that should work a lot better than xprop. It certainly simplifies the script. (eventually I will likely remove the script altogether and just add arguments to the binary and couple it with dbus and DE's a little closer for Wayland support.)

```
git pull origin master && git pull origin dev
systemctl --user stop keyswap
git checkout 2d69c7b
```

**Comment by rbreaves** [comment]
The service has undergone some major changes as of the v1.0 release so I am closing this ticket. It is no longer relevant.
