### ISSUE TITLE
xkeysnail: terminator not behaving the same as gnome-terminal

### ISSUE THREAD

**Issue by flozano** [rbreaves/kinto#143]
GNOME-terminal properly behaves as expected, with CTRL+C and CMD+C for copying.

However, terminator doesn't. I can only send CTRL+C as CMD+C, and CTRL+C just sends C. I see terminator is listed in the 'appnames' in user_config.json, so I don't know why this could be happening.

terminator:
![Peek 2020-05-03 11-16](https://user-images.githubusercontent.com/1159291/80910410-902bf280-8d2f-11ea-8305-1d788cb23869.gif)

gnome-terminal:
![Peek 2020-05-03 11-17](https://user-images.githubusercontent.com/1159291/80910448-d08b7080-8d2f-11ea-9e7c-b18c157f9290.gif)

I just confirmed this only happens in xkeysnail based implementation. In xkb/x11 it works well.

**Comment by rbreaves** [comment]
Likely an issue that is case sensitive related. Either the proper case needs to be added or maybe re.compile needs to be swapped out w/ something else that is insensitive.

I discovered this just before merging into master but don’t have all the terminal apps installed to do proper testing.

**Comment by rbreaves** [comment]
Oops I never commented on the resolution lol. So I added something in the latest release I knew I should have added before the 1st official release w/ xkeysnail but just didn't get around to.. xkeysnail config file now forces case insensitivity, and I have made a PR to the original xkeysnail author to include an example in his readme.

It's really bad form imo to have something break because of a case sensitivity issue lol.

Let me know if there is anything else @flozano .

**Comment by flozano** [comment]
seems to work well now in xkeysnail, thanks!

**Comment by vietduc01100001** [comment]
I'm having the same error as @flozano while using alacritty. I cloned kinto with `5da4925` as the latest commit.

**Comment by rbreaves** [comment]
@vietduc01100001 checkout the latest dev & let me know. May have added it via my phone, but can’t test it atm.

https://github.com/rbreaves/kinto/commit/029d83ad5b2f3d84db800065e437428f0125674a

**Comment by vietduc01100001** [comment]
It works now! Thanks!

I tried adding alacritty to `user_config.js` yesterday but it didn't work. How does that file relate to `xkeysnail-config/kinto.py` file?

**Comment by rbreaves** [comment]
user_config.js only relates to the original kintox11/xkb method. Xkeysnail doesn’t use it at all, only uses Kinto.py.

Xkeysnail is a lot simpler in that all of its config is in that one Kinto.py file. Xkb required editing multiple xkb related files in contrast & an ass backwards way of remapping keys.
