### ISSUE TITLE
Kinto starts on login, but only for 1 terminal application

### ISSUE THREAD

**Issue by torma616** [rbreaves/kinto#15]
I was able to get Kinto to start on login by adding "systemctl --user start keyswap" as a login script, but it's only working in the Tilda terminal. The MATE terminal is unaffected by the keyswap.

**Comment by rbreaves** [comment]
The MATE terminal class name will need to be added to the xactive.sh file. If you mention the class name of your specific terminal I will add it to the project.

~/.config/xactive.sh
https://github.com/rbreaves/kinto/blob/master/system-config/xactive.sh

```
# How to add more terminal editors
# run this command while using the terminal
# and add the name to class_name
# xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) WM_CLASS
class_name='konsole\|Gnome-terminal\|terminator\|sakura\|guake\|tilda\|xterm\|eterm'
```
