### ISSUE TITLE
UK keyboard mappings

### ISSUE THREAD

**Issue by Mahoney** [rbreaves/kinto#152]
Quick one I hope; a UK mac keyboard has the following key bindings:
```
Shift-2: @
Alt-2:   €
Shift-3: £
Alt-3:   #
```

I'm a bit unclear how I'd set those (alt-n for instance seems to select a tab). Apologies if I should have been able to work it out.

Thanks!

**Comment by rbreaves** [comment]
It's fine xkeysnail can be a little weird to understand at first, but via a combination of using xbindkeys and referencing one of xkeysnails files I think you can derive at your answer.

    xbindkeys -mk

Reference xkeysnail's file https://github.com/mooz/xkeysnail/blob/master/xkeysnail/key.py.

I believe there is like an offset of like 8 bits involved btwn what xbindkeys reports or the even the xkb keymap file on the local system versus the key.py file.. So if nothing else finding out what your key value is will be key.

Already for your currency pound symbol it is probably this one.

    KEY_EURO   = 0x1b3

Simply creating the keymap in your ~/.config/kinto/kinto.py file will be enough
something along the lines of this.

    K('Shift-KEY_3'):K('KEY_EURO'),

If you are dedicated to wanting to make it as 100% identical to the UK mac keyboard then I would also encourage you to fork my project and save your changes in your own master or dev branch and then make PR's and I will accept them. Although the format I'd prefer it to be in would like this.

    # K('Shift-KEY_3'):K('KEY_EURO'), # UK KBD

If you do take the time, but no pressure. Commits that follow that structure though will allow me to go in and easily add more questions in my setup file that will uncomment those sections out for users that want it during the install.
