### ISSUE TITLE
Ubuntu uninstall leave keys without working

### ISSUE THREAD

**Issue by rodfersou** [rbreaves/kinto#154]
To fix this I need to follow this tip:

https://askubuntu.com/a/315226

In my case needed to run:

```bash
gsettings reset-recursively org.gnome.settings-daemon.plugins.media-keys
gsettings reset-recursively org.gnome.desktop.wm.keybindings
gsettings reset-recursively org.gnome.shell.keybindings
gsettings set org.gnome.mutter overlay-key 'super'
```

Also reinstall the keyboard.

**Comment by rbreaves** [comment]
Probably just didn’t run the uninstall correctly now that the installer has been changed to support 2 methods.

I will be relocating the uninstall option to appear at the 1st menu option so there’s less confusion & less chance that someone misses doing the proper uninstall.

**Comment by rbreaves** [comment]
Looking back over my source.. I think mutter overlay key does get reset via

    gsettings reset-recursively org.gnome.mutter.keybindings

but I will explicitly add this as you mentioned just to make sure.

    gsettings set org.gnome.mutter overlay-key 'super'

2 of the commands are irrelevant though as I don't actually change keybinds in all of the areas you mentioned, even if it seems like it. And hopefully the reset commands will stick in all cases, I know I am having to backup the new keybinds and re-apply them a 2nd time just to get custom keybinds to stick over reboots.

**Comment by rbreaves** [comment]
Thanks for reporting the issue @rodfersou . It should be knocked out now.
