### ISSUE TITLE
Add possibility to donate via Github sponsoring, Patreon et al.

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#161]
Title says it all. Great work, so make it easy for users to show their appreciation.

**Comment by rbreaves** [comment]
I have finally got around to adding an Amazon wishlist for anyone that wishes to donate to me lol. I appreciate all of the early feedback and testing that you gave me and I hope you being quiet is just a sign of how well it continues to work for you lol?

I may be releasing a commercial app in the coming months as well that will provide another means of people supporting me and this project indirectly. (The program is not directly related to Kinto, but it will compliment it.

I am finally closing this ticket!
