### ISSUE TITLE
setup.py fails to install xbinkeys on Manjaro

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#162]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1720088/81455729-52482780-9190-11ea-8883-d1006ee5c5d4.png)

```sh
error: target not found: xbindkeys
```

**Install Type:** VM
**Distro:** Manjaro (uptodate)
**DE:** Gnome
**Branch:** master
**Commit:** 0c3e03a

**Additional context**

`xbinkeys` in only in AUR, so the generate install command `sudo /usr/bin/pacman -Syy; sudo pacman -S  xbindkeys ibus` is not valid

**Comment by rbreaves** [comment]
Truthfully xbindkeys is no longer needed for the xkeysnail install, but yea it is still needed if one wants to use the older xkb/kintox11 method. Nice catch though, I probably added AUR and forgot that that would need to be part of the script.

**Comment by rbreaves** [comment]
Updated install with latest commit to not attempt to install xbindkeys for xkeysnail as it is only needed for the old implementation and somewhat optional at that. Would close the ticket but I probably should address it for the old installer.

**Comment by rbreaves** [comment]
Should have closed this ticket awhile ago. This has been completely removed from the setup as it has been completely rewritten and no user interaction occurs in the terminal for the setup now.
