### ISSUE TITLE
./setup.py: Detects OS and DE but then again it does not on Manjaro

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#163]
**Describe the bug**

At the end of the install:

```sh
Detected Manjaro  DE: gnome

Do you want to apply system level shortcuts? (Y/n) y
distro: manjaro de: gnome
A supported OS and DE was not found, you may not have full system level shortcuts installed.
```

**Install Type:** VM
**Distro:** Manjaro (uptodate)
**DE:** Gnome
**Branch:** master
**Commit:** 0c3e03a

**Comment by rbreaves** [comment]
Looks like I straight up overlooked Manjaro Gnome as far as system level shortcuts go. Looking in my excel doc to see if I have anything documented at all. It probably lines up pretty closely to another DE and OS already.

**Comment by rbreaves** [comment]
Oh wow.. I need to close this one too. Manjaro Gnome really didn't get much love from me 😅. v1.2 should be fine from what I can tell.
