### ISSUE TITLE
Word wise navigation on Firefox buggy, when menu is hidden

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#164]
**Describe the bug**

If the menu is configured to be hidden, the word wise cursor nav is only working every other time. The other time it toggles the menu (which is toggled by alt only), see the following screen recording:

![alt-firefox-menu](https://user-images.githubusercontent.com/1720088/81456838-38104880-9194-11ea-8580-7ea260e81385.gif)

**Expected behavior**

The menu should not be toggled, the alt keypress should not go through (perhaps?).

**Install Type:** VM
**Distro:** Manjaro (uptodate)
**DE:** Gnome
**Branch:** master
**Commit:** 0c3e03a

**Kinto Input Caret Status**
```
cat: /tmp/kinto/caret: No such file or directory
```

**Kinto Standard Log**
```
-- Logs begin at Fri 2020-04-17 10:54:24 CEST, end at Sat 2020-05-09 01:28:46 CEST. --
-- No entries --
```
**Kinto Debug Log (1.0.6-2+)**

The guide to debug log does not seem to work:

```
$ cd ~/.config/kinto
$ ./kintox11 --debug
bash: ./kintox11: No such file or directory
```

When the menu is set to be visible all the time, the word wise nav is working as expected.

**Comment by rbreaves** [comment]
It is a known issue and I need to highlight it in the readme. I believe I had intended to do so and must have forgot.

It is mentioned in kinto.py.
https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py
```
...
    # ** Firefox fix **
    #   User will need to set "ui.key.menuAccessKeyFocuses"
    #   under about:config to false.
    #
    #   https://superuser.com/questions/770301/pentadactyl-how-to-disable-menu-bar-toggle-by-alt
    # **
...
```
I am not sure if this fix can be scripted or not. Depends how/where firefox saves that config I suppose.

**Comment by rbreaves** [comment]
Also I am at a loss at the moment on giving any advice/direction on how to get the caret detection working properly for Manjaro Gnome. I have tried to resolve it a number of ways and nothing I do seems to bring in the IBus Panel extension that it desperately needs.. unless I find another way to detect the caret/input bar altogether.

Also caret detection is disabled for xkeysnail in master atm any ways. Restarting xkeysnail is not a very good solution for changing keymaps. At some point I will need to rewrite parts of xkeysnail to allow for changes of the keymap or maybe I could add in some inotify code to the config file itself that will turn on and off certain areas of the keymap based on the caret value.

**Comment by owzim** [comment]
What does Manjaro Gnome do/have to prevent that from working properly in comparison to other DEs/OSs?

**Comment by rbreaves** [comment]
@owzim I really don't know.. a different version of IBus compiled possibly? Or a default Panel extension missing from their compiled version? I mean compiling IBus from source or understanding how the Panel extension ties into it better would likely resolve the issue.

I have not spent the time to dig into it that far though. I've been hoping for a misconfiguration or something else I can either install or a switch to flip somewhere in code or the gui. I sure have not found it though.

**Comment by owzim** [comment]
An this is only on the GNOME edition and not on any of the other official spins? What can I do to help? I have actually no idea what this ibus or the panel extension does. Can we contact the package maintainer?

**Comment by rbreaves** [comment]
IBus seems to mostly be used a method to allow for other languages, chinese, korean, japanese, etc. They have other similar packages as well, so they may be useful if I find the time to look at them.

Right now the greater concern imo is adding in inotify to xkeysnail and some function to monitor the caret status, which yea - isn't happening (caret status) under Manjaro Gnome atm due to the missing IBus panel.

I suspect whoever handles the compiling of IBus for Arch or Manjaro would be more insightful than the IBus devs themselves. In general though Arch/Manjaro just doesn't have as many means of enabling IBus and its features as other distros, most other distros offer GUI methods which work, although I am able to script it just fine and not have to use the GUI, but I have had to do both at times to get things set.

IBus feels a little finicky to get set initially even when it does work right imo. I am not 100% certain it never unsets itself though once it is set, which makes me think I should always check it again on startup and/or re-apply it. Although re-applying it on shutdown might be smarter than on login.

**Comment by owzim** [comment]
> I suspect whoever handles the compiling of IBus for Arch or Manjaro would be more insightful than the IBus devs themselves.

With 'package maintainer' I meant exactly that. The people responsible for the package on Arch/Manjaro.

> An this is only on the GNOME edition and not on any of the other official spins? 

I assume that the package does not differ on the different spins, right?

**Comment by rbreaves** [comment]
From what I recall Manjaro KDE has a working IBus w/ the panel extension. No idea about other DE flavors

I just recently fell in love w/ Ubuntu Budgie so I’ll probably want to support Solus & Manjaro Budgie fairly soon.

**Comment by rbreaves** [comment]
Attempts as wordwise is still stripped out, I have some newer.. better method for doing a non-blocking activity inside python and may take a look at integrating it directly xkeysnail as an optional argument for additional keymap options.

**Comment by rbreaves** [comment]
Marking this as no plans to fix - I simply don't have the bandwidth to fix this for an edge case like the URL address bar. It works normally on elements within a page and the IBUS hack I did before was really not ideal. Also if the Menu bar is set to be always visible or to appear in the global menu (with a patch that is floating around out there) then this issue simply disappears.
