### ISSUE TITLE
No Control Left key anymore

### ISSUE THREAD

**Issue by parsifallo** [rbreaves/kinto#167]
Hey!

I use kinto for my Apple USB Keyboard and it works great but I have one problem. I'd like to use the qemu shortcut for KVM switching and I need to press Control Left and Control Right at the same time (hardcoded). I wondered why it doesn't work so I had a look into Ubuntu's (Gnome) keyboard layout while pressing keys:
Pressing Control L -> Super L
but pressing Super L -> Control R
Pressing Control R -> Super R
and pressing Super R -> Control R

So Right Control key is missing which means I am not able to use QEMU's kvm switch functionality.

**Comment by rbreaves** [comment]
I would add in an extra block of code specific to the qemu app to emulate the two control keys. Part of the design of Kinto xkeysnail is that it plays w/ the fact that there are two control keys.

It can easily be remedied though if a specific app uses both.

**Comment by rbreaves** [comment]
Just to note Terminals use both left & right control keys, & right is mostly given shift along w/ any key press on the Cmd key location.

Normal apps use Super, Alt & RCtrl (Cmd) on the left side. Sometimes Super is remapped to Ctrl or LCtrl, it just varies.

**Comment by parsifallo** [comment]
Thank you very much :) It works!
