### ISSUE TITLE
options cmd line missing to enable permanent apple keyboard keyswap

### ISSUE THREAD

**Issue by chinarut** [rbreaves/kinto#17]
hi!  I'm a bit of a Linux noob so bear with me... I've verified the keyswap service is running on  18.04 Ubuntu:

<pre>ubuntu@salsa:~/dev/kinto$ systemctl --user status keyswap
<font color="#8AE234"><b>●</b></font> keyswap.service - keyswap for Terminal and GUI
   Loaded: loaded (/home/ubuntu/.config/systemd/user/keyswap.service; disabled; vendor preset: enabled)
   Active: <font color="#8AE234"><b>active (running)</b></font> since Thu 2019-12-26 23:18:27 PST; 27min ago
 Main PID: 6740 (bash)
   CGroup: /user.slice/user-1002.slice/user@1002.service/keyswap.service
           ├─6740 /bin/bash /home/ubuntu/.config/xactive.sh mac 0 0 0
           ├─6763 xprop -spy -root _NET_ACTIVE_WINDOW
           ├─6764 grep --line-buffered -o 0[xX][a-zA-Z0-9]\+
           └─6765 /bin/bash /home/ubuntu/.config/xactive.sh mac 0 0 0
</pre>

I can't seem to run these commands at the end of the install because **options** doesn't exist:

<pre>An Apple keyboard with the hid_apple driver was detected.
Please run the following commands to swap alt/option and Command.
Your Kinto keymapping will not work right on Apple keyboards without it.

echo &apos;1&apos; | sudo tee -a /sys/module/hid_apple/parameters/swap_opt_cmd
&quot;<b>options</b> hid_apple swap_opt_cmd=1&quot; | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all
</pre>

Looking at the options [man page](https://manpages.ubuntu.com/manpages/bionic/en/man3/options.3tk.html), it appears to be part of Tk?  I verified I have Tk 8.4 installed.   I've poked around quite a bit and can't seem to figure out what package has the options command line.

I ran the commands in the debugging section and it definitely switches to "term to gui" when I go to Chromium and back to "gui to term" when I focus on Terminal.

**Comment by tommytomtj** [comment]
@chinarut "options does not appear to be a command but rather a settings paramater that's being writte to /etc/modprobe.d/hid_apple.conf. 'options' is part of "options hid_apple swap_opt_cmd=1" being piped to the command 'tee' which writes to the file I just mentioned. You are probably missing the quotes that wrap the options group and so Linux thinks youre trying to run a command called option instead.

**Comment by chinarut** [comment]
@tommytomtj thanks for getting back to me - finally cloned my Ubuntu install to my SSD to dual-boot my daily driver so excuse the delay -it's been an adventure :)

ok I see what's going on - it looks like there is a missing "echo" in these instructions:

```
An Apple keyboard with the hid_apple driver was detected.
Please run the following commands to swap alt/option and Command.
Your Kinto keymapping will not work right on Apple keyboards without it.

echo '1' | sudo tee -a /sys/module/hid_apple/parameters/swap_opt_cmd
"options hid_apple swap_opt_cmd=1" | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all
```
I did the following to fix the issue and toggling works :+1: 

```
echo "options hid_apple swap_opt_cmd=1" | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all

```
I can't help but be curious why the installer itself doesn't offer to run these commands?

**Comment by rbreaves** [comment]
I guess I fixed the print statement in a hurry last time, sorry about that. The echo is now mentioned in the printed statement. The reason I have the user to run that manually is that everything else about the script does not require elevated privileges and I wanted to avoid having to prompt the user for their password if at all possible.

Granted you still have to, but I would rather the user be aware of the explicit changes being added to their system level files.
