### ISSUE TITLE
applying system level shortcuts: "Expected argument was not provided"

### ISSUE THREAD

**Issue by medyagh** [rbreaves/kinto#175]
I uinstalled previous version and installed the new version with xkeysnail, at the end when it asks me 
Do you want to apply system level shortcuts? (Y/n) y
I get this error
```
Expected argument was not provided
```

**Full Log** :

<details>
<pre>
med@xmac:~/workspace/kinto (master)$ ./setup.py 

Kinto - Type in Linux like it's a Mac.

1) Kinto - xkeysnail (udev/x11) - Recommended
2) Kinto - Original xkb/x11 implementation
3) Uninstall Kinto - xkeysnail
4) Uninstall Kinto - Original xkb

1

Install Kinto - xkeysnail (udev)
  1) Windows & Mac (HID driver)
  2) Mac Only & VMs on Macbooks
  3) Chromebook
2

Support for Firefox/Chrome Back/Forward hotkeys (Cmd+Left/Right) disabled on master w/ xkeysnail 

[sudo] password for med: 
Service file added to /usr/lib/systemd/system/xkeysnail.service
Ownership set for root...
Permissions set to 644...
Created soft symlink...
ln: failed to create symbolic link '/etc/systemd/system/graphical.target.wants/xkeysnail.service': File exists
Failed to create soft symlink for graphical target...
localuser:root being added to access control list
fatal: destination path 'xkeysnail' already exists and is not an empty directory.
fatal: reference is not a tree: 51c369084e0045a8410d227bab52411bf84fb65b
Cloning into 'xkeysnail'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 42 (delta 20), reused 20 (delta 6), pack-reused 0
Unpacking objects: 100% (42/42), 24.22 KiB | 2.42 MiB/s, done.
fatal: reference is not a tree: 51c369084e0045a8410d227bab52411bf84fb65b
From https://github.com/rbreaves/xkeysnail
 * branch            master     -> FETCH_HEAD
Already up to date.
Processing /home/med/workspace/kinto/xkeysnail
Requirement already satisfied, skipping upgrade: evdev in /usr/local/lib/python3.8/dist-packages (from xkeysnail==0.3.0) (1.3.0)
Requirement already satisfied, skipping upgrade: inotify_simple in /usr/local/lib/python3.8/dist-packages (from xkeysnail==0.3.0) (1.3.3)
Requirement already satisfied, skipping upgrade: python-xlib in /usr/local/lib/python3.8/dist-packages (from xkeysnail==0.3.0) (0.27)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->xkeysnail==0.3.0) (1.14.0)
Building wheels for collected packages: xkeysnail
  Building wheel for xkeysnail (setup.py) ... done
  Created wheel for xkeysnail: filename=xkeysnail-0.3.0-py3-none-any.whl size=17588 sha256=5e4a4bda45bd214aad1ed0dad5d52448d5cd1e14c045dcc6322c860cfe297df5
  Stored in directory: /tmp/pip-ephem-wheel-cache-nb6r051n/wheels/06/59/35/470d84e00506fedbcb8ac16f0c2965e5fee89f2474bd631c0e
Successfully built xkeysnail
Installing collected packages: xkeysnail
  Attempting uninstall: xkeysnail
    Found existing installation: xkeysnail 0.3.0
    Uninstalling xkeysnail-0.3.0:
      Successfully uninstalled xkeysnail-0.3.0
Successfully installed xkeysnail-0.3.0
Adding xhost fix...

Kinto install is complete.

Kinto xkeysnail service is running.

Commands for controlling Kinto's xkeysnail service
sudo systemctl restart xkeysnail
sudo systemctl stop xkeysnail
sudo systemctl start xkeysnail
sudo systemctl status xkeysnail

If Kinto is already running it will be stopped...
If you cancel the installer you can re-run Kinto via
 systemctl --user start keyswap
Failed to stop keyswap.service: Unit keyswap.service not loaded.

Detected Ubuntu 20.04 DE: gnome

Do you want to apply system level shortcuts? (Y/n) y
Expected argument was not provided
</pre>
</details>

**Comment by rbreaves** [comment]
Yea.. I do need to fix that, nothing to actually be concerned about, a failing check for Budgie DE actually. It needs to go silent.

**Comment by rbreaves** [comment]
Issue is now resolved in the latest merge on master. Closing ticket

**Comment by medyagh** [comment]
thanks
