### ISSUE TITLE
Ctrl-click in terminal acts like ctrl is never released

### ISSUE THREAD

**Issue by arnaud-lb** [rbreaves/kinto#185]
**Describe the bug**

After a ctrl-click on a link in gnome-terminal, everything acts like the ctrl key was not released. For example, trying to scroll in Firefox will act like ctrl-scroll, alt-tab will act like ctrl-alt-tab, and so on.

**Expected behavior**

After a ctrl-click, the ctrl key should be released.

**Install Type:** Bare Metal
**Distro:** Ubuntu LTS 20.04
**DE:** Gnome
**Branch:** master
**Commit:** ac34350

**Kinto Input Caret Status**
```
cat: /tmp/kinto/caret: No such file or directory
```

**Kinto Standard Log**
```
journalctl --unit=keysnail.service 
-- Logs begin at Wed 2020-05-06 13:47:44 CEST, end at Tue 2020-05-19 18:33:12 CEST. --
-- No entries --
```

**Additional context**

I can cause the ctrl key to be released by switching back to gnome-terminal, and hitting ctrl-c.

I verified that the issue does not happen when xkeysnail is stopped.

**Comment by arnaud-lb** [comment]
When I say ctrl, it's actually LEFT_META, since my LEFT_CTRL is mapped to LEFT_META.

Also, the problem doesn't happen with alt-click (which is actually RIGHT_CTRL, since my LEFT_ALT is mapped to RIGHT_CTRL)

**Comment by rbreaves** [comment]
> When I say ctrl, it's actually LEFT_META, since my LEFT_CTRL is mapped to LEFT_META.
> 
> Also, the problem doesn't happen with alt-click (which is actually RIGHT_CTRL, since my LEFT_ALT is mapped to RIGHT_CTRL)

Firefox and Electron apps are the only 2 things I am aware of that can introduce the Alt activation issue. Not saying there are not more, but those are the 2 I have come across. Fixing it in Firefox is easy, although has not been automated, I assume it can be but I am not sure how/where to go to do so.

```
define_keymap(lambda wm_class: wm_class.casefold() not in mscodes,{
    # Wordwise remaining - for Everything but VS Code
    K("M-Left"): K("C-Left"),               # Left of Word
    K("M-Shift-Left"): K("C-Shift-Left"),   # Select Left of Word
    K("M-Right"): K("C-Right"),             # Right of Word
    K("M-Shift-Right"): K("C-Shift-Right"), # Select Right of Word
    # ** VS Code fix **
    #   Electron issue precludes normal keybinding fix.
    #   Alt menu auto-focus/toggle gets in the way.
    #
    #   refer to ./xkeysnail-config/vscode_keybindings.json
    # **
    #
    # ** Firefox fix **
    #   User will need to set "ui.key.menuAccessKeyFocuses"
    #   under about:config to false.
    #
    #   https://superuser.com/questions/770301/pentadactyl-how-to-disable-menu-bar-toggle-by-alt
    # **
    #
})
```

**Comment by rbreaves** [comment]
And that is an interesting behavior, of the ctrl key being held if a ctrl click occurs.. I don't think I have experienced that - but will need to test it as you describe it. I know I sometimes do a ctrl + right click, but rarely, if ever, a ctrl + left click.

**Comment by rbreaves** [comment]
Oh re-reading this might make more sense why I hadn’t ran into this.. I’ve never held down the newly mapped Super key while left clicking. Will get around to testing soon.

**Comment by rbreaves** [comment]
@arnaud-lb I can't seem to duplicate this problem, I just tried it in the Gnome-terminal with a test hyper-link, held down physical Ctrl (meta/super) and then went to the browser, text editor or terminal in different attempts and pressed the left or right arrow expecting it to behave the way Super+Left/right would behave but it appeared as though no modifier was held.

I am not sure how to duplicate the issue. Also this was attempted in the latest master and Ubuntu Mate LTS 20.04. Leaving this open for now, but may be closing this in the next few days if I can't figure out how to duplicate the issue.

**Comment by rbreaves** [comment]
Closing this issue for now. I might suggest that you delete the the ./xkeysnail folder in the kinto folder and pull down the latest master and then re-run the installer.

I think the latest master should put xkeysnail on the proper commit even if you didn't delete it, but just to make sure. I am wondering if you installed it when I had a bad commit on the xkeysnail branch (as far as I knew it only broke Ctrl+Tab)
