### ISSUE TITLE
Using alt+backspace in apps?

### ISSUE THREAD

**Issue by gulo-gulo** [rbreaves/kinto#187]
First I want to say, I just found this project and it's saving me from the world of pain that I thought I'd have to deal with when I decided to move to using my custom built PC running Ubuntu instead of a mac as my daily driver.

I was going to file this as a bug, but because I'm so new to kinto (and Ubuntu Desktop), I wanted to make sure first.

Coming from using a mac, I'm used to correcting whatever I'm typing by deleting words via `alt+backspace`. In some text inputs, I can use it the same way I use `command+backspace` with kinto, and the behavior is the same (e.g. address bar in chrome). However, it's not the same everywhere (e.g. `alt+backspace` does nothing as I type this nor in Sublime Text). 

Is there a way to keep `alt+backspace` consistent across apps or am I missing something here?

**Comment by gulo-gulo** [comment]
Hmmm, actually, I may be confusing `alt+backspace` with `control+backspace` on the mac, I'll change the comment above and title to reflect that.

**Comment by rbreaves** [comment]
I think to put what you are requesting into normal terms you are wanting the following.

Super/Alt + Backspace = Ctrl + Backspace (Left word delete)
Super/Alt + Fn + Backspace (delete) = Ctrl + Fn + Backspace (Right word delete)

And yes that behavior should have been added already, so it is part of it now. From what I can tell whether you hold Ctrl or Alt on a mac it will delete the word to the left of the cursor.

Chromebooks are limited on their default modifier layout, caps is really Super, but my preference is to treat Alt more like Fn to force the Backspace key on chromebooks to behave like a normal delete key.

**Comment by gulo-gulo** [comment]
> I think to put what you are requesting into normal, programming, terms you are wanting the following.
> 
> Super/Alt + Backspace = Ctrl + Backspace (Left word delete)
> Super/Alt + Fn + Backspace (delete) = Ctrl + Fn + Backspace (Right word delete)
> 
> And yes that behavior should have been added already, so it is part of it now. From what I can tell whether you hold Ctrl or Alt on a mac it will delete the word to the left of the cursor.
> 
> Chromebooks are limited on their default modifier layout, caps is really Super, but my preference is to treat Alt more like Fn to force the Backspace key on chromebooks to behave like a normal delete key. That's also why it wasn't mapped correctly before, but things have changed since then, it is easy for me to keep chromebook specific keymaps while mapping every other keyboard layout properly. (I run a perl command during install that will comment in or comment out the appropriate areas of the key remap script file)

@rbreaves thanks a ton. Once I read your reply, I realized I likely broke something when I was messing around with various OS files e.g. `/usr/share/X11/symbols/pc` prior to finding `kinto`. So I just did a clean install of ubuntu and now everything works perfectly. Thanks a ton man, I very appreciate your time and help. I was looking for a donation link or github sponsor option for `kinto` but I don't see anything; I'll keep an eye out for that, should you ever choose to add one.

**Comment by rbreaves** [comment]
@gulo-gulo Sounds good and I'm glad it works well for you! And yea I may add a sponsor or donate button at some point.
