### ISSUE TITLE
Properly Mapping Guake Hotkey

### ISSUE THREAD

**Issue by tucamsam** [rbreaves/kinto#199]
I have typically mapped LeftCtrl+Grave as my hotkey for Guake, but it seems some of the default settings have made this slightly more challenging. First, I removed the mapping from LC-Grave -> LC-PageUp, which seemed to work with some success.
At this point, it seemed that my hotkey in Guake was getting set correctly. However, then I noticed that I could no longer open Guake using my hotkey, though I could close it once open.

I've tried globally mapping LC-Grave -> LC-Grave to ensure it wouldn't get remapped, but that seems to break the rest of the global mappings. Am I just missing how the order of these keys are mapped? Or is what I'm attempting to do simply not possible?

**Comment by rbreaves** [comment]
Yea sounds like you found the obvious LC-Grave remaps, but you are missing that during GUI app usage your physical Left Ctrl key becomes Super instead (your physical Left Alt/Cmd key is actually being mapped to Right Ctrl).

So just creating something like this under the None category that affects most everything.

    K("Super-Grave"): K("LC-Grave"),                     # Guake toggle
