### ISSUE TITLE
Hugely appreciate your efforts with this

### ISSUE THREAD

**Issue by awediohead** [rbreaves/kinto#200]
Just in case you only read the title I thought I'd make myself super clear - just so you get a sense of how grateful I am, I had to spend an hour digging out my old github password to login just to say thank you to you! My 30 years of Mac based muscle memory copy cut and paste have been driving me insane the last few days - I even thought about buying a new keyboard, but then thought that's crazy, I really like my keyboard and you're supposed to be able to make Linux do what YOU want! So glad I found kinto! 
One tiny bit of constructive criticism that will not help 99% of your users but would have helped me because I'm a total noob to Linux - it took me a while to figure out I had to navigate to the kinto-master directory before the python script would do anything. Bleeding obvious now, but if you want to help people with Mac keyboards coming from OSX who may not be very techy, (some are of course), maybe revisit your 'how to' with my kinda level of ignorance in mind? :) Cheers

**Comment by rbreaves** [comment]
Sure, and I appreciate you letting me know!! Updating the readme is something that is very important for any project and I probably do need to spend more time doing that.

Additionally I do have some things in the works to help simplify the install further, a PPA repo that is planned - that'll make the install as simple as installing Sublime Text 3 in linux from a PPA or any other app that comes from a repo. I am not sure if I will be able to get it included in any official distro PPAs but that is always something to look into at a later date as well.

I have also had conversations with a maintainer over at Ubuntu Budgie (20.04) on the possibility of including Kinto with their distro and making it part of their Cupertino layout even. Similar conversations with Enso OS (xfce based) as well.

I need to do some more polishing of Kinto though, add system tray icon support among other things. Also here is what the new installer will look like https://github.com/rbreaves/kinto/blob/alpha/keycheck.py. It will literally guide the user to press a few keys and it will configure the keyboard right every time after that. There won't be any more of this Windows, Mac or Chromebook stuff in the setup. It will just have you press your modifier keys and let you know what is about to get remapped to it and it'll move on from there.

If you come across anything you think I can improve in the future about Kinto just let me know!

**Comment by rbreaves** [comment]
In the future the install will hopefully go something like this, unless the user just wants to use the latest from the github page instead.

 Install the GPG key:

    wget -qO - https://someurl.launchpad.com/kinto/yaddayadda.gpg | sudo apt-key add -

Ensure apt is set up to work with https sources:

    sudo apt-get install apt-transport-https

Select the channel to use:

Stable

    echo "deb https://launchpad.com/kinto/ apt/stable/" | sudo tee /etc/apt/sources.list.d/kinto.list

 Update apt sources and install Kinto

```
sudo apt-get update
sudo apt-get install kinto

# Run setup
kinto-setup
```

Uninstall

    kinto-remove

Advanced Setup
    kinto-setup -kb windows -de gnome -km st4vsc

I don't have the arguments finalized for the advanced setup, but I know some users need to fully automate the setup without it being interactive. I will be making or rather keeping that functionality, but it will be improved.

**Comment by picolens** [comment]
Wonderful project that's just so useful :) Couldn't agree more. Now, wish more people knew about it. Maybe this project needs to be featured on those blog sites like omgubuntu, lwn, or itsfloss etc
