### ISSUE TITLE
Vscode won't allow me to use alt+ctrl

### ISSUE THREAD

**Issue by darekf77** [rbreaves/kinto#203]
I am using Kinto on my **linux mint 19.3** and it is fantastic...I would like to support it with money ! but..

when I am trying to use VSCODE... I am not allowed to use my global shortcuts ( those are 
macos's Spectacle app shortcuts )
- toogle full screen (ctrl+alt+f)
- snap left (cltr+alt+arrowleft)
- snap right (cltr+alt+arrowright)

before kinto there was not a problem, because I was using **Super** insted of **Ctrl**:
- toogle full screen (super+alt+f)
- snap left (super+alt+arrowleft)
- snap right (super+alt+arrowright)

I know that vscode can be configured pretty easily to use Ctrl instead of Super... 
And I am thinking if it is possible to swap in kinto to default key (Super) for vscode.
Let me know what you think !

Thanks
D

**Comment by rbreaves** [comment]
Thanks, glad to here that it is working well for you, aside from a few items.

Interesting.. there is a problem with the  sublime text 3 keymap.. some how replace and fullscreen ended up with similar shortcuts. I will fix that today. Shouldn't impact you using the physical Ctrl key though whether you use vs code or sublime.

1. toggle full screen (ctrl+alt+f)
2. snap left (cltr+alt+arrowleft) or snap right (cltr+alt+arrowright)

To address them I will step through the ./xkeysnail-config/kinto.py config file

1. toggle shortcut may conflict with replace, however you say you already user Super in place of Ctrl? If that is the case then I see no reason why your physical Ctrl key (which is Super during normal GUI app usage) is not sufficient to activate your fullscreen toggle, no modifications to kinto.py should be needed as there are no Super-M-f remaps.

To fix it for Terminal usage however an additional will need to be made.

```
...
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("LC-M-f"): K("Super-M-f"),                       # toggle fullscreen
...
```

Non-conflicting shortcuts, but initially seemed like potential issues

```
...
# Keybindings for VS Code
define_keymap(re.compile(codeStr, re.IGNORECASE),{
    ...
    K("C-M-f"): K("C-h"),                       # replace
    ...
...
# Keybindings for Sublime Text
define_keymap(re.compile("Sublime_text", re.IGNORECASE),{
    ...
    K("C-M-f"): K("f11"),                       # toggle_full_screen
    K("C-M-f"): K("C-h"),                       # replace
...
```

2. Snap to left or right

I am not seeing any conflicts here at all, and again during normal GUI app usage the physical Ctrl & Alt keys should work fine for an existing keybind, but to fix it for termninal usage you'd need to do something similar as above again.

```
...
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("LC-M-Left"): K("Super-M-Left"),                       # Snap window to left
    K("LC-M-Right"): K("Super-M-Right"),                     # Snap window to Right
...
```

**Comment by rbreaves** [comment]
> I know that vscode can be configured pretty easily to use Ctrl instead of Super...
And I am thinking if it is possible to swap in kinto to default key (Super) for vscode.
Let me know what you think !

Also I am not entirely sure what you mean by that comment, I mean we're essentially using the mac's Super location as the primary by relocating the Ctrl to that spot period. (RCtrl to be technical, so that the terminal can still use LCtrl on the physical control key later on - not a perfect solution because the Super key is essentially lost during this time and only makes a come back when we explicitly remap LCtrl to make use of Super key combos.)

You can certainly place your primary key wherever you would like during any particular app by looking at how it is done for the terminal or GUI apps, it is at the very beginning of the config file.

Terminal main modifier remap
./xkeysnail-config/kinto.py

```
...
# [Conditional modmap] Change modifier keys in certain applications
define_conditional_modmap(re.compile(termStr, re.IGNORECASE), {
    # # Chromebook
    # Key.LEFT_ALT: Key.RIGHT_CTRL,     # Chromebook
    # # Left Ctrl Stays Left Ctrl
    # Key.LEFT_META: Key.LEFT_ALT,      # Chromebook
    # Key.RIGHT_ALT: Key.RIGHT_CTRL,    # Chromebook - Multi-language (Remove)
    # Key.RIGHT_CTRL: Key.RIGHT_ALT,    # Chromebook
    # # Right Meta does not exist on chromebooks

    # # Default Mac/Win
    # Key.LEFT_ALT: Key.RIGHT_CTRL,   # WinMac
    # Key.LEFT_META: Key.LEFT_ALT,    # WinMac
    # Key.LEFT_CTRL: Key.LEFT_CTRL,   # WinMac
    # Key.RIGHT_ALT: Key.RIGHT_CTRL,  # WinMac - Multi-language (Remove)
    # Key.RIGHT_META: Key.RIGHT_ALT,  # WinMac
    # Key.RIGHT_CTRL: Key.LEFT_CTRL,  # WinMac

    # # KintoWin
    # Key.LEFT_CTRL: Key.RIGHT_CTRL,   # KintoWin
    # Key.LEFT_META: Key.LEFT_CTRL,    # KintoWin

    # # Mac Only
    # Key.LEFT_META: Key.RIGHT_CTRL,  # Mac
    # # Left Ctrl Stays Left Ctrl
    # Key.RIGHT_META: Key.RIGHT_CTRL, # Mac
    # Key.RIGHT_CTRL: Key.LEFT_CTRL,  # Mac
})
...
```

By default it is all commented out until the setup runs through it and enables the parts that are relevant to your setup. Most of the remaining config remains unchanged with a few exceptions that are DE specific.

**Comment by darekf77** [comment]
> Also I am not entirely sure what you mean by that comment, I mean we're essentially using the mac's Super location as the primary by relocating the Ctrl key to that spot period. (RCtrl to be

@rbreaves in vscode there is very nice keybinding section... and you can configure there all shortcuts you want, including: copying|pasting in editor, creating new tab, copying|pasting in terminal etc..

In short: I need kinto for everything in system **except vscode**.

**Comment by rbreaves** [comment]
Ah, right, I have made use of it awhile back too to help fix the wordwise situation in VS Code, although I did finally manage to implement wordwise without setting up any VS Code remaps. #176  The Alt Menu will still sometimes activate/take focus though.. so really if you are dealing with Alt based keymaps then VS Code remapping may be the best route to go. I think it is primarily Electron based apps with that issue - but I have had one user say that it impacted other apps for them as well.

If Alt menu activation issues really is wide spread though then I may make some changes to Kinto to manage Alt based keymaps via xkb while remapping the rest via xkeysnail, but I am not sure yet. I also don't understand how it is that xkb manages to bind alt keymaps without the Alt menus stealing the focus - as that focus stealing even happens normally too - unless that keymap is natively set in the app.

I think I am going to go ahead and restore this file into master just as an easy example for others to see. Modifying individual keymaps on the app level though is something I want the Kinto app to avoid doing, the point of Kinto is that it is the one stop shop for all key rebinds and will leave the original mappings untouched as much as possible.

https://github.com/rbreaves/kinto/blob/268a1bdbff4cca6cac51267785267a87d8f4b05a/xkeysnail-config/vscode_keybindings.json

Also you can certainly disable all VS Code remapping in Kinto by commenting it out or removing that bit of code.

Is there anything more I can help you with on this?

**Comment by rbreaves** [comment]
That is odd, so your hotkeys, they do work in VS Code though if you disable Kinto?? That would be weird if that is the case.

xkeysnail is on such a low level I just can't see any app having issues with it. I could see VS Code doing the Alt menu stealing though, and yea if you hide and disable the Alt menu that shouldn't happen in theory - or if you bind that combo in the app - but then you can't use it globally.

I am not sure what to suggest, although you could try setting the global keymap to a different combo, the F keys above F12 even and then remap your desired combo in Kinto...

So super+alt+f could become this
```
K("Super-M-f"):K("C-F14") #fullscreen toggle
```

I've had to do that in some cases involving Alt-Tab, although xfce does not appear to allow for F keys above F12, so it uses backslash instead.

**Comment by darekf77** [comment]
OK I see now... there is only problem with:
snap left (cltr+alt+arrowleft)
snap right (cltr+alt+arrowright)

Alt menu is taking focus... even when disabled..

![image](https://user-images.githubusercontent.com/7131693/83982086-de7e7380-a923-11ea-8a09-09f497d5b0d6.png)

**Comment by rbreaves** [comment]
Ah, well I will be closing this issue then, this may be something to notify the VS Code team about or Electron in general - I am honestly not sure which party would be best to resolve that, but this is definitely problematic under Linux. This issue does not occur on macOS or Windows, so I consider it to be a bug brought about by how Electron apps tend to interface with most, possibly all, Linux based DEs.

You seriously might just want to to bind it to a non-alt key, and then use my suggestion about on remapping that to what it is that you actually want. You could attempt to do it the same way I handle wordwise and would probably find some success in doing that.

kinto.py
```
...
# Keybindings for VS Code
define_keymap(re.compile(codeStr, re.IGNORECASE),{
    # Snap window example
    K("Super-M-Left"):[K("M-F19"),K("C-F15")]
    # Wordwise remaining - for VS Code
    # Alt-F19 hack fixes Alt menu activation
    K("M-Left"): [K("M-F19"),K("C-Left")],                  # Left of Word
    K("M-Right"): [K("M-F19"),K("C-Right")],                # Right of Word
    K("M-Shift-Left"): [K("M-F19"),K("C-Shift-Left")],      # Select Left of Word
...
```

To break down what is happening further you are still activating the Alt menu obviously with this keymapping, but the M-F19 (F19 is not bound to anything) that follows it will usually immediately disable the Alt menu and then it proceeds to your actual global keymap - it does not have to be Ctrl-F15, you can set it to whatever you want it to be at this point.

K("Super-M-Left"):[K("M-F19"),K("C-F15")]

So yea, it isn't really a problem with Kinto as much as an issue with VS Code 😅. I will be closing this ticket, if you have any other questions or issues just let me know and I will help out where I can.

**Comment by rbreaves** [comment]
Also since it is a global keymap being discussed it would be better to go in the define keymap None section and the define keymap Terminal section, but with LCtrl instead of Super. That would take care of it under any app.

**Comment by darekf77** [comment]
> K("Super-M-Left"):[K("M-F19"),K("C-F15")],

Does not work.. (btw I am not fluent in python... I've done 1 python app in my life .. long time ago.. )


anyway now I see that my linux is not seeing the difference between pressing cltr+arrorw and arrow (or alt+arrow and alt) in **Keyboard shortcuts** .. I am using 1) xkeysnail

![image](https://user-images.githubusercontent.com/7131693/84100691-b1f25680-aa0c-11ea-865c-02e650a3129b.png)

![image](https://user-images.githubusercontent.com/7131693/84100770-d51d0600-aa0c-11ea-88c9-f7bb92e730b6.png)

**Comment by darekf77** [comment]
hmmmmmmm...  this **fuckin alt menu** is preventing my navigating word by word just like in macos in vscode... I just can't disabled this shit.. I've tried almost everything ... I am already spending to much time on this... I think I won't use my linux machine for programming.. only for games,vm's, backup :/  
Or maybe in future I will install macos in vm with gpu passthrough - that is also solution. Anyway thanks for help @rbreaves.

**Comment by rbreaves** [comment]
As I mentioned earlier, one sure fire way of fixing the Alt based wordwise shortcuts is to manually add these mappings directly into VS Code - the Alt menu will then ignore the combo properly and the need for Alt-Arrow to remap to a Ctrl-Arrow keymap goes away. (don't recall if you have to remove that from Kinto or not, I would think it to be optional because Ctrl-Left/Right tends to be a system level shortcut for traversing words in general.)

https://github.com/rbreaves/kinto/blob/dev/xkeysnail-config/vscode_keybindings.json

And yea, VS Code on linux is not ideal, but I think that just applies to Electron apps in general on Linux. If at some point someone comes up with a better way of handling Electron apps then I will certainly implement the fix in Kinto.

**Comment by rbreaves** [comment]
> > K("Super-M-Left"):[K("M-F19"),K("C-F15")],
> 
> Does not work.. (btw I am not fluent in python... I've done 1 python app in my life .. long time ago.. )
> 
> anyway now I see that my linux is not seeing the difference between pressing cltr+arrorw and arrow (or alt+arrow and alt) in **Keyboard shortcuts** .. I am using 1) xkeysnail
> 

I am not really sure why that wouldn't work if that entry is added to the None section (LCtrl the terminal section). And I assume you are updating the ~/.config/kinto/kinto.py file and restarting the service after that. "sudo systemctl restart xkeysnail". No real reason to re-install the app just for a modification to the config file.

**Comment by lowderdev** [comment]
I know this is old, but I had the same issue as darekf77 and just turning off the menu bar in vscode fixed it for me:

https://stackoverflow.com/questions/48044429/override-alt-to-toggle-menu-bar-on-vs-code
