### ISSUE TITLE
Installation fails when home directory is not in /home

### ISSUE THREAD

**Issue by japert** [rbreaves/kinto#204]
**Describe the bug**
Installation fails when home directory is not in `/home`.
Installation only fails in a soft manner: A warning is printed but otherwise it looks successful.
Upon reboot, x11 server fails to load because of incorrect paths in setting files.

**Install Type:** Bare Metal
**Distro:** Ubuntu 18.04 -- but anywhere really
**DE:** Gnome
**Branch:** master
**Commit:** 3143f11

Logs and status if relevant
```
Jun 09 09:53:54 hostname systemd[1]: Starting xkeysnail...
Jun 09 09:53:54 hostname bash[14376]: localuser:root being added to access control list
Jun 09 09:53:54 hostname runuser[14376]: pam_unix(runuser-l:session): session opened for user user by (uid=0)
Jun 09 09:53:54 hostname bash[14376]: -bash: /home/user/.config/kinto/prexk.sh: No such file or directory
Jun 09 09:53:54 hostname runuser[14376]: pam_unix(runuser-l:session): session closed for user user
Jun 09 09:53:54 hostname systemd[1]: xkeysnail.service: Control process exited, code=exited status=127
Jun 09 09:53:54 hostname systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Jun 09 09:53:54 hostname systemd[1]: Failed to start xkeysnail.
```

I have a fix ready.

**Comment by japert** [comment]
I have a branch ready that I could create a PR for.

**Comment by rbreaves** [comment]
I appreciate the PR! The changes looked good to me so I have merged the changes into master.
