### ISSUE TITLE
Sudoers syntax errors on Gentoo aarch64

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#212]
Attempted install on a Gentoo-based 64-bit distro aimed at the Raspberry Pi 3/4. 

System boot image was obtained from: 

https://github.com/sakaki-/gentoo-on-rpi-64bit

It did not go well. Main thing right off the bat is many complaints about syntax errors on pretty much every line in the /etc/sudoers.d/limitedadmins file created by setup.py. Which of course broke everything else and the install failed. 

Uninstall was of course also completely broken because sudo was broken by the syntax errors. 

Had to remove the limitedadmins file manually by su-ing to root to fix sudo. 

**Install Type:** Bare Metal on a Raspberry Pi 4B 8GB model
**Distro:** Gentoo aarch64
**DE:** XFCE
**Branch:** master

This is just an FYI post mainly. Not sure how much effort I'm ready to put into troubleshooting a Gentoo-based system right now. It seems to have little internal resemblance to either Debian or Arch distros. Just rebooted the Pi back into the Debian-based Twister OS where Kinto works fine now.

**Comment by rbreaves** [comment]
Well you are hitting all of the unsupported distros & DEs so expect much to be broken I guess 😅. I’ll be happy to accept any PRs though for code I can also review & test under the supported distros & DEs to confirm that they continue to work.

And limitedadmins was definitely I thing added to xkeysnail by me to make it a systemd service & sadly unlike xkb xkeysnail needs sudo level access.

**Comment by RedBearAK** [comment]
Just want to confirm that since the username is hard coded into the xkeysnail.service file, this current iteration of Kinto probably won't work well on any system that's actually used by multiple users, correct?

**Comment by rbreaves** [comment]
That would be true, although I think the xkb method is multiuser capable, although you’d need to install it for each user. Xkb was done in way to make user of user level permissions.

Xkeysnail could be done in that way too BUT I felt changing the permissions of certain system level binaries to run on a user level would be worse from a security perspective than running xkeysnail as sudo & a system level systemd service.. so I made the call to drop multi-user support in favor of higher security.

I didn’t like losing it but given the alternative.. I liked that even less.

**Comment by rbreaves** [comment]
I really need to take out prexkey.sh though any ways.. it was there for caret input status checking & atm it isn’t implemented due to issues & when I do fix I won’t need prexkey any ways. Xhost will still need to be there though.

**Comment by rbreaves** [comment]
Marking this as won't fix, unless a PR is made, and closing ticket.
