### ISSUE TITLE
System Trays for All Supported DEs in Readme

### ISSUE THREAD

**Issue by rbreaves** [rbreaves/kinto#213]
Making this a separate ticket, not entirely sure I won't tackle it myself for Linux, but I would like to give an opportunity to any linux users or devs out there to help me out here. There are screenshots and a working example of Kinto working on Windows with a system tray on the master branch and even autoset capabilities in Alpha that is working and will make its way into dev and then master.

That's it really, if someone wants to contribute to this project in a major sort of way I'd say bringing system tray apps to any of these DEs gnome3, budgie, xfce, and kde would be pretty huge. 

If anyone has any questions about it though please let me know, but for the most part I will leave this very open ended - I have no strict requirements of any kind as far as what to code it in, I imagine the DE will dictate that more than anything. Just make sure the user can do 3 things, set Windows or Mac keyboards, suspend (stop) kinto, and close that app.

Automating the resetting of keyboards on a usb keyboard being plugged in would be nice and in the roadmap ticket there is a link to an article that describes how to do something like that, but initially it is not requirement as that brings in additional complexity. Keep it tight, keep it light.

**Comment by rbreaves** [comment]
Just to add this, there is a very clear example of some regex that can be used from the toggle_kb.bat file for Windows but is standard Perl PCRE regex that can be used in a bash script to switch kinto from Windows to Apple keyboards, but it would also need the proper regex for chromebooks as well (not a big deal tbh, because the setup.py file also contains the regex for that too).

No sense in forgetting to mention that, because the regex way of toggling the keymaps is probably the easiest and fastest method to use and is already built out for re-use.

**Comment by joy2306** [comment]
hello @rbreaves  i would like to contribute to this project , is it still open ? and i don't have any experience in opensource will it be ok?

**Comment by rbreaves** [comment]
You can certainly contribute still, maybe add support for desktop environments I haven’t yet or find shortcuts or features I’ve yet to implement (not sure what they’d be tbh lol). I do appreciate the offer!

This specific issue is almost done actually as I am nearing the end of a new system tray that covers every major distro except for Gnome3 or KDE DE’s.. for them I have a full on GUI app. Sys tray is built for DE’s w/ appindicator support.

I suppose KDE could still have a separate sys tray app created. Gnome3 will be difficult, they don’t want sys trays.

Tbh the only 3 major things I want done after release 1.2 will be multiuser support so I can do an official release on the distro repos. Add distro/de switching options, & add the ability to bind new keys via a GUI (per app, by app group or globally).

**Comment by rbreaves** [comment]
@joy2306 v1.2 has now been released, if you'd like to test it out then please do! I would love the feedback.
