### ISSUE TITLE
MATE needs XFCE system level shortcuts applied

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#227]
On a Raspberry Pi 4B running a fresh install of Ubuntu Server 20.04 LTS 64-bit and set up with the MATE desktop environment via the “desktopify” app, the Alt+Tab keys fail to activate window cycling/task switching. 

In the Keyboard Shortcuts app the setting for “Move between windows, using a popup window” defaults to “Alt+Tab”. Pressing Alt+Tab on the physical keyboard while Kinto is running results in the keyboard shortcut changing to “Ctrl+Tools”. This shortcut combo fails to function. Other combos however will activate switching. 

Editing kinto.py to comment out the non-XFCE shortcuts and uncomment the “xfce4” shortcuts results in physical Alt+Tab changing the shortcut above to “Ctrl+Backslash” as would be expected in XFCE. With this change, physical Alt+Tab now successfully activates task/window switching. Problem solved. 

Conclusion: XFCE system level shortcuts should probably be applied to MATE desktop environments as well. The installer recognizes MATE as “mate” at the end, and then complains about a missing schema “org.gnome.shell.keybindings”, and does not apply the XFCE system level shortcuts. 

Perhaps a simpler solution would be allowing the user to choose to try the XFCE “backslash” shortcuts regardless of which DE is detected.

**Comment by rbreaves** [comment]
That's interesting, Mate branches off of Gnome2 and is configured via dconf or gsettings and typically those are fine with F keys, not sure why it wouldn't work on a raspberry pi, may have a more limited xkb config set of key definitions.. I am not sure. If it was really an issue with the DE then I am pretty sure I'd have detected that in my VMs.

**Comment by RedBearAK** [comment]
Might have something to do with having used Desktopify to install the desktop environment on top of the Ubuntu Server base. Maybe the script doesn’t install quite all the GNOME packages you’re used to seeing on a mainstream distro or the “desktop” version of Ubuntu. But everything seems to work fine otherwise. 

I’m not as impressed by this setup as much as the YouTubers who convinced me to try it. Think I’ll go back to Twister OS for now. Hardware video acceleration be damned. 

Side not: If you haven’t heard of BashTOP yet you should check it out when you have a moment. It’s kind of amazing for a CLI app. Both visually and functionally.

**Comment by rbreaves** [comment]
Closing ticket I think the current keymaps are fine in v1.2 but if not I will address it when notified.
