### ISSUE TITLE
Expanding supported keyboards, trying to understand where changes are made for linux installs

### ISSUE THREAD

**Issue by jackmac92** [rbreaves/kinto#229]
I'm trying to set this up with a non-standard keyboard (ergodox). But got some weird results on my mechanical keyboard (alt mapped to the OS key). However I know the install worked correctly with my other keyboard. I'm working on figuring out the issues with the keycodes in my mechanical keyboard (but nothing helpful to report about my issue yet).

Am I correct in thinking that this only is meant to support specific keyboards?

Considering an attempt to fork and modify this myself (but I understand that doesn't seem easy, death by a thousand cuts). Would I primarily be looking to modify kinto.py? Or would you recommend working with xkeysnail from scratch?

Small nitpick: I found the below prompt slightly unclear. It's meant to ask what keyboard is used on this computer right?
https://github.com/rbreaves/kinto/blob/d96e23855064c24594bce4fa308ffe3e1073e45d/xkeysnail_service.sh#L154

**Comment by rbreaves** [comment]
Yea, the 3 options are specifically related to the keyboard types. All options are for Linux OS’s.

The windows installer looks different & only loads when Windows 10 is detected.

And yes, on Linux, you’d want to modify Kinto.py. I don’t know the default config of ergodox, but knowing the key codes isn’t needed, you’ll see the first couple of functions specially for GUI & Terminal usage & by modifying their Keyswaps you can locate the keys according to the ReadMe. Everything that follows should go untouched unless you have other things you want to add.

**Comment by rbreaves** [comment]
> Considering an attempt to fork and modify this myself (but I understand that doesn't seem easy, death by a thousand cuts). Would I primarily be looking to modify kinto.py? Or would you recommend working with xkeysnail from scratch?

    ~/.config/kinto/kinto.py

Forking and updating either config file I believe is fairly straight forward to be honest. The comment in my readme about death by a thousand papercuts was really geared towards the more complicated configurations I have seen using Autokey in Linux without setting up system-wide remaps first.

Kinto's use of Xkeysnail for Linux and Autohotkey for Windows keeps everything pretty tidy and simple in my view, granted I could create an easier GUI wrapper down the line for either. Also I eliminated the need for additional apps like xbindkeys in linux or Sharpkeys/registry hacks in Windows, those were things that held back the earlier versions of Kinto.

Here are some pretty crazy Autokey configs, this one might be the worst offender - the hierarchy of folders and json files spread out all over the place for autokey.
https://github.com/danyim/elementary-macos 

Many of these are tackling the problem too directly on an app by app basis so much of the time. It doesn't need to be this complicated.

https://github.com/bartosjiri/autokey-macos
https://github.com/xortim/autokey
https://github.com/bliles/autokey-macos
https://github.com/roymckenzie/macos-autokey-phrases
https://github.com/sttts/mac-autokey
https://github.com/namgk/autokey-config
https://github.com/viktorot/autokey-osx-bindings
https://github.com/andreasgrill/onekeyboard
https://github.com/samfpetersen/ubuntu-macos-keys
https://github.com/petrstepanov/autokey-macos-gnome

Another thing I completely forgot about was the lack of being able to apply a system-wide remaps and then exclude a single pattern/program easily with autokey. This is not an issue with xkeysnail or autohotkey implementations, all in all you can script and write your logic however you see fit and the text files it is based on is far more readable and usable. Autokey is probably most useful for those that want to use it with a GUI wrapper, but even then I just haven't found it to fit the bill. It's very easy to create groupings of app categories via xkeysnail or ahk and should be pretty quick and easy to recognize in either config file, kinto.py or kinto.ahk.

https://github.com/autokey/autokey/issues/161
