### ISSUE TITLE
Duplicate hid_apple.conf lines added every upgrade

### ISSUE THREAD

**Issue by thebitstick** [rbreaves/kinto#233]
**Describe the bug**
Every time I reinstall kinto via setup.py, it appends `options hid_apple swap_opt_cmd=1`to the end of the file. This leads to multiple lines of the same option.

**Expected behavior**
Installer only adds line once and checks if line exists in file.

**Install Type:** Bare Metal
**Distro:** Arch Linux (up-to-date as of `date -u`: `Tue 07 Jul 2020 03:49:21 AM UTC`)
**DE:** Gnome
**Branch:** dev (replicatable on master)
**Commit:** acd0b80

**Comment by rbreaves** [comment]
Oh wow.. thank you for reporting that. I am surprised I had not noticed or realized that it would have been doing that.
