### ISSUE TITLE
xkb symbols mac_term mac_gui: No such file

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#238]
I'm submitting this as a question because I'm not exactly clear on just how important these errors are, but I've seen these lines a lot right at the end of the Kinto setup process: 

```
Can't open /home/kris/.xkb/symbols/mac_term: No such file or directory.
Can't open /home/kris/.xkb/symbols/mac_term: No such file or directory.
Can't open /home/kris/.xkb/symbols/mac_gui: No such file or directory.
Can't open /home/kris/.xkb/symbols/mac_gui: No such file or directory.
```

They seem to be triggered by these lines (186-189 at the moment) in setup.py: 

```
cmdline('perl -pi -e "s/(\/\/ )(.*)(\/\/ Elementary cmdtab)/\$2\$3/g" ~/.xkb/symbols/mac_term')
cmdline('perl -pi -e "s/(\w.*)(\/\/ Default cmdtab)/\/\/ \$1\$2/g" ~/.xkb/symbols/mac_term')
cmdline('perl -pi -e "s/(\/\/ )(.*)(\/\/ Elementary cmdtab)/\$2\$3/g" ~/.xkb/symbols/mac_gui')
cmdline('perl -pi -e "s/(\w.*)(\/\/ Default cmdtab)/\/\/ \$1\$2/g" ~/.xkb/symbols/mac_gui')
```
I'm unable to parse exactly what the purpose of these lines is, and with the "xkb" I have been assuming that this had something to do with the "other" version of Kinto, the non-xkeysnail version. 

Is this correct or should I be looking at a way to fix these errors? 

The errors are happening because the .xkb directory doesn't exist, of course. Should it, if I never choose option #2 during setup? Is this something relevant in any way to the xkeysnail version of Kinto?

**Comment by rbreaves** [comment]
Yea, anything xkb related is the prior version, which was also more complicated and cmd-tab never worked fully - particularly in KDE. That part of the setup really should be skipped over completely unless the user is wanting to do the xkb install, but at this point I do not know why anyone would want to use xkb over xkeysnail.

**Comment by RedBearAK** [comment]
I figured it was just a leftover of the xkb version. I see you already if-ed it out. Nice. That should stop it.

**Comment by RedBearAK** [comment]
Probably a really stupid question, but is it the added whitespace in front of the "cmdline" lines that determines where the new if statement terminates? I'm not really familiar with Python yet. Does the if statement close itself without needing a "fi" or something on the end the way a bash script would? I know there's an elif right below it but that was already there and seems unrelated. And has less whitespace in front of it. Is that the determining factor in Python? Just the whitespace alone?

**Comment by rbreaves** [comment]
Yea, python has no syntactic sugar, such as brackets. Personally I like brackets in my code - but the author of Python despises them I guess and wants indentation to be the only means of readable code. I think it is misguided - formatting gets lost to easily imo, but it is what it is.

And yea - that was an oversight from when I upgraded Kinto to use xkeysnail. I test on elementaryOS but not frequently as it is very similar to the ubuntu releases.

**Comment by RedBearAK** [comment]
Hahaha, that's funny. I was about to add to that comment above, "If that is the case it must be a bit nerve-wracking to process Python files with certain utilities that might mess up the whitespace formatting." LOL. Quite a bold choice. I prefer positively terminated code as well, but then again it's just as easy to forget or misplace the positive terminator and when you're in the same boat. Six of one... 

See you on the next bug.
