### ISSUE TITLE
Installation problems (Ubuntu)

### ISSUE THREAD

**Issue by joesaunderson** [rbreaves/kinto#243]
I am using Ubuntu on a Macbook Pro via Parallels.

I have followed your instructions, and disabled the shortcuts in parallels but not a single shortcut works?

What am I doing wrong or am I being naive in assuming some shortcuts come out the box?

Even CMD+C/V do not work.

**Comment by rbreaves** [comment]
Did you choose 1 (xkeysnail) & then 2 (the one intended for VMs on MacBook)?

**Comment by joesaunderson** [comment]
I see this message when installing:

```
If Kinto is already running it will be stopped...
If you cancel the installer you can re-run Kinto via
 systemctl --user start keyswap
Failed to stop keyswap.service: Unit keyswap.service not loaded.

```

**Comment by joesaunderson** [comment]
```
➜  kinto git:(master) sudo systemctl status xkeysnail
● xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-07-14 17:32:29 BST; 30s ago
    Process: 8605 ExecStartPre=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /sbin/runuser -l eng -c /home/eng/.config/kinto/prexk.sh (code=exited, status=0/SUCCESS)
   Main PID: 8630 (sudo)
      Tasks: 5 (limit: 9480)
     Memory: 20.1M
     CGroup: /system.slice/xkeysnail.service
             ├─8630 /usr/bin/sudo /bin/bash -c  /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
             ├─8634 /bin/bash /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
             ├─8636 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /tmp/kinto/xkeysnail/kinto.py
             ├─8638 inotifywait -m -e close_write,moved_to,create,modify /tmp/kinto/xkeysnail
             └─8639 /bin/bash /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py

Jul 14 17:32:29 eng-development-environment systemd[1]: Starting xkeysnail...
Jul 14 17:32:29 eng-development-environment bash[8606]: localuser:root being added to access control list
Jul 14 17:32:29 eng-development-environment systemd[1]: Started xkeysnail.
Jul 14 17:32:29 eng-development-environment sudo[8630]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c  /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/x>
Jul 14 17:32:29 eng-development-environment sudo[8630]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 14 17:32:29 eng-development-environment sudo[8638]: Setting up watches.
Jul 14 17:32:29 eng-development-environment sudo[8638]: Watches established.

```

**Comment by rbreaves** [comment]
> I see this message when installing:
> 
> ```
> If Kinto is already running it will be stopped...
> If you cancel the installer you can re-run Kinto via
>  systemctl --user start keyswap
> Failed to stop keyswap.service: Unit keyswap.service not loaded.
> ```

You can ignore that, only relevant to users coming from/installing on top of the earlier Kinto app written for xkbcomp.

**Comment by joesaunderson** [comment]
Any idea what could be preventing it from working, it appears to be running?

**Comment by rbreaves** [comment]
> ➜  kinto git:(master) sudo systemctl status xkeysnail
> ● xkeysnail.service - xkeysnail
>      Loaded: loaded (/lib/systemd/system/xkeysnail.service; enabled; vendor preset: enabled)
>      Active: active (running) since Tue 2020-07-14 17:32:29 BST; 30s ago
>     Process: 8605 ExecStartPre=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /sbin/runuser -l eng -c /home/eng/.config/kinto/prexk.sh (code=exited, status=0/SUCCESS)
>    Main PID: 8630 (sudo)
>       Tasks: 5 (limit: 9480)
>      Memory: 20.1M
>      CGroup: /system.slice/xkeysnail.service
>              ├─8630 /usr/bin/sudo /bin/bash -c  /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
>              ├─8634 /bin/bash /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
>              ├─8636 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /tmp/kinto/xkeysnail/kinto.py
>              ├─8638 inotifywait -m -e close_write,moved_to,create,modify /tmp/kinto/xkeysnail
>              └─8639 /bin/bash /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
> 
> Jul 14 17:32:29 eng-development-environment systemd[1]: Starting xkeysnail...
> Jul 14 17:32:29 eng-development-environment bash[8606]: localuser:root being added to access control list
> Jul 14 17:32:29 eng-development-environment systemd[1]: Started xkeysnail.
> Jul 14 17:32:29 eng-development-environment sudo[8630]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c  /home/eng/.config/kinto/xkeystart.sh /tmp/kinto/x>
> Jul 14 17:32:29 eng-development-environment sudo[8630]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 14 17:32:29 eng-development-environment sudo[8638]: Setting up watches.
> Jul 14 17:32:29 eng-development-environment sudo[8638]: Watches established.

According to that it’s running just fine, my guess is that parallels is still messing w/ your key layout & you don’t realize it.

Turn Kinto off temporarily.

    sudo systemctl stop xkeysnail

Make sure Ctrl = Ctrl, Alt = Alt, Cmd = Super in the VM before running start.

    sudo systemctl start xkeysnail

**Comment by joesaunderson** [comment]
Would the keyboard settings in Ubuntu have any affect on this?

Within the VM I have set it up to use the MacOS keyboard?

**Comment by rbreaves** [comment]
Possibly, I am not sure what it means to have it set to use a macOS keyboard in the VM.

The key thing is that before you install Kinto your mac keyboard layout should be like this.

Ctrl - Alt - Super - Spacebar - Super - Alt

If that is not your starting your point then Kinto will fail to remap correctly. And as long as you install with options 1 & 2 then it should work fine.

On a physical mac keyboard connected via usb or BT though you can use the built in mac kb driver to swap the alt and Cmd/Super key via the driver - in which case option 1 & 1 will work (whether the driver settings have been set or not, it will set it).

**Comment by matthew-gill** [comment]
@joesaunderson I think I've cracked it.
In parallels, change the profile to Generic

![image](https://user-images.githubusercontent.com/31350541/87870692-5bc8e980-c9a2-11ea-9ae3-efcdf8c573af.png)

**Comment by joesaunderson** [comment]
I tried this, but it didn't appear to work at the time. Maybe I needed to do another step?

**Comment by rbreaves** [comment]
@joesaunderson Can you try checking out the dev branch and reinstalling? You will want to install this as well though StatusNotifierItem/AppIndicator Support https://extensions.gnome.org/extension/615/appindicator-support/.

I have simplified the service file now and added a system tray icon to help control Kinto going forward as well (although only tested on Ubuntu Budgie I believe it should work in standard Gnome and Mate as well).

https://github.com/rbreaves/kinto/blob/dev/xkeysnail-config/xkeysnail.service

```
git checkout dev
./setup.py
```

Not sure if Kinto could have been running for you multiple times or what.. but I am wondering as I managed to accomplish some unexpected remap behaviors while coding by running multiple instances. That really shouldn't ever happen in the master branch though.

**Comment by rbreaves** [comment]
Please try the latest v1.2 release and let me know if anything changes for you. I will reopen this ticket if you report that it still fails.
