### ISSUE TITLE
Quote key on GB-UK keyboard maps to forwardtick

### ISSUE THREAD

**Issue by dac09** [rbreaves/kinto#249]
**Describe the bug**
Using the latest kinto version with xkeysnail, 
- the single and double quote keys map to forwardticks e.g. `´`
- backtick is very slow

**Expected behavior**
- I need to type quotes! 

**Install Type:** Bare Metal
**Distro:** elementary OS 5.1.6 Hera (Built on Ubuntu 18.04.4 LTS)
**DE:** Gnome
**Branch:** master
**Commit:** c4dcd3f

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
● xkeysnail.service - xkeysnail
   Loaded: loaded (/lib/systemd/system/xkeysnail.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-07-26 13:12:06 BST; 11min ago
  Process: 17375 ExecStop=/bin/bash -c me=$$;ps -ef | grep '[t]mp/kinto' | awk -v me=$me '$2 != me {print $2}' | xargs kill;/usr/b
  Process: 17403 ExecStartPre=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /sbin/runuser -l dac09 -c /home/dac09/.config/kint
 Main PID: 17542 (sudo)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/xkeysnail.service
           ├─17542 /usr/bin/sudo /bin/bash -c  /home/dac09/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
           ├─17546 /bin/bash /home/dac09/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py
           ├─17550 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /tmp/kinto/xkeysnail/kinto.py
           ├─17551 inotifywait -m -e close_write,moved_to,create,modify /tmp/kinto/xkeysnail
           └─17552 /bin/bash /home/dac09/.config/kinto/xkeystart.sh /tmp/kinto/xkeysnail/kinto.py

Jul 26 13:12:06 bigmac systemd[1]: Starting xkeysnail...
Jul 26 13:12:06 bigmac bash[17403]: localuser:root being added to access control list
Jul 26 13:12:06 bigmac runuser[17403]: pam_unix(runuser-l:session): session opened for user dac09 by (uid=0)
Jul 26 13:12:06 bigmac runuser[17403]: pam_unix(runuser-l:session): session closed for user dac09
Jul 26 13:12:06 bigmac systemd[1]: Started xkeysnail.
Jul 26 13:12:06 bigmac sudo[17542]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c  /home/dac09/.config/kinto/x
Jul 26 13:12:06 bigmac sudo[17542]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 13:12:06 bigmac sudo[17542]: Setting up watches.
Jul 26 13:12:06 bigmac sudo[17542]: Watches established.
```

**Additional context**
- I used to use the xkb version, and it almost worked well, but the backtick didnt map correctly. In the latest version i get
```
Failed to start keyswap.service: Unit keyswap.service is not loaded properly: Exec format error.
```
- Im using a thirdparty bluetooth mac keyboard
- I can type `'` and `"` if I switch the keyboard to US, but that messes up the mapping for backtick to `§`

**Comment by rbreaves** [comment]
I suspect this is actually a bug of some kind w/ xkeysnail. Not sure how best to go about debugging it w/o a UK keyboard to test against. I imagine you need a different key layout defined in xkeysnail though.

**Comment by dac09** [comment]
Thanks for the reply and for building this!

Would sending my relevant keycode to you be helpful?

Alternatively perhaps you could point me at some examples to custom remaps for kinto so I can swap certain keys only (£,€,backtick,etc.) on the US layout. Had a look at the file but wasn't sure about what values the mappings accept. 

Also, any thoughts on the Xkb version?

**Comment by rbreaves** [comment]
> Thanks for the reply and for building this!
> 
> Would sending my relevant keycode to you be helpful?
> 
> Alternatively perhaps you could point me at some examples to custom remaps for kinto so I can swap certain keys only (£,€,backtick,etc.) on the US layout. Had a look at the file but wasn't sure about what values the mappings accept.

I am not sure if the keycodes you'd retrieve would really line up with the keycode values in this file or not.

https://github.com/rbreaves/xkeysnail/blob/master/xkeysnail/key.py

The backtick is known as Grave btw on line 50.

    GRAVE = 41

> Also, any thoughts on the Xkb version?

The xkb version is one I really don't update or maintain much anymore, it is considerably more complicated to setup. Although perhaps more native in one way, despite that the python wrapper for remapping udev input, xkeysnail, has greater compatibility with any app because the udev input operates on a lower level than xkb.

**Comment by rbreaves** [comment]
Actually I was thinking backtick ` not forwardtick... American keyboards don't even have forward ticks so I am not sure how to go about fixing it for you myself..

But I do know you will need to run this command.

    sudo showkey -k

And press forwardtick, it should show the keycode of 40 I would suspect? After that press the key that is mapping to forwardticks.. I assume there is one? One you have that you can swap the values in the key.py

./xkeysnail/xkeysnail/key.py
```
...
    SEMICOLON = 39
    APOSTROPHE = 40
    MYSTERYKEY = ??
    GRAVE = 41
    LEFT_SHIFT = 42
...
```
```
...
    SEMICOLON = 39
    APOSTROPHE = ??
    MYSTERYKEY = 40
    GRAVE = 41
    LEFT_SHIFT = 42
...
```

Starting in root directory of kinto
```
cd xkeysnail
sudo pip3 install --upgrade .
sudo systemctl restart xkeysnail
```

Closing ticket as there is nothing more I can do unless someone sends me a GB-UK keyboard.

**Comment by dac09** [comment]
Appreciate the reply, I haven't been on my Linux machine in the past few days. 

UK keyboards don't have a forward tick either (not that I can see!) - I was using the quote key - '/" 

Thanks for the tips, I'll report back when I get a chance to try it again.

**Comment by rbreaves** [comment]
I see.. then I guess without xkeysnail running I'd do this.

```
sudo systemctl stop xkeysnail
sudo showkey -k
# press " key
# note the proper keycode
```
Then update the key.py file as mentioned above with the proper value, whatever it happens to be and not worry about the mystery key since it does not physically exist. And lastly reinstall xkeysnail.
