### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by loeffel-io** [rbreaves/kinto#256]
Der Befehl "C:\Users\loeff\AppData\Roaming\Microsoft\Windows\STARTM~1\Programs\Startup\kinto-start.vbs" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by loeffel-io** [comment]
After running kinto-start.vbs manually: 

kinto shows up in the task bar but only the cmd + c etc. are working - not even the at sign is working .. pretty bad

**Comment by loeffel-io** [comment]
not even the uninstall deletes strawberry perl and autohotkey - this is to bad

**Comment by loeffel-io** [comment]
not even the `~/.kinto` dir gets removed

**Comment by rbreaves** [comment]
Thank I’ll re-review these items & see what’s going on.

**Comment by rbreaves** [comment]
I apologize that it appears like I never got back to you on this. I have made a new release that addresses mostly Linux concerns, however there were changes on the Windows side of things as well, so perhaps some of those changes resolved it incidentally?

**Comment by rbreaves** [comment]
Closing for now. Will re-open if/when I hear back on the status of the current build.
