### ISSUE TITLE
Unsure about expected behavior // some characters missing // keysnail error message

### ISSUE THREAD

**Issue by pidab** [rbreaves/kinto#259]
I installed Kinto (which I haven't used before) on a new Lenovo T14 with Ubuntu 20.04. It has a German keyboard. Installation seems to partially succeed: I can copy text using <kbd>Alt</kbd>+<kbd>c</kbd> and paste it using <kbd>Alt</kbd> +<kbd>v</kbd>, even in the Terminal. I can also use <kbd>Alt</kbd>+<kbd>Tab</kbd> to switch between applications like I would on a Mac.

However, there's at least one major problem: I don't have a clue how to enter some characters as @, €, or ~. I don't know if they are supposed to work like on a Mac (involving the option key) or any other way. Also, I'd expect to be able to copy/paste using <kbd>Super</kbd>+<kbd>c</kbd>/<kbd>Super</kbd>+<kbd>v</kbd>. During installation, I also got the message `fatal: directory 'keysnail' exists and is not empty` (translated from German).

So, I have three questions:
1. Can I use Kinto with my keyboard or is it for some layouts only? If the answer is yes, how can I enter @, €, and ~?
2. Is it normal that copy/paste etc. works with the <kbd>Alt</kbd> key instead of the <kbd>Super</kbd> key? In fact I hope so, but I didn't expect Kinto to do this on it's own (I hardly used tools like this one before and I don't really understand even the first section of the docs). 
3. Should I worry about the error message? I haven't used my new Laptop a lot yet and haven't used Linux in years. I wonder whether there are features of Kinto that are not working yet.

**Comment by rbreaves** [comment]
I think the xkeysnail projects needs better multi language support added to it via its key.py file. Xkeysnail appears to be written for US based keyboards I believe.

Not sure what the best method will be to compile the keycodes for other languages & have xkeysnail check your language type (for your keyboard).

**Comment by rbreaves** [comment]
I have released v1.2 but no additional changes have been made to multi-language support at this time and it may be something better addressed on the xkeysnail project level as mentioned previously. I will be closing this ticket, but if you open a ticket on the xkeysnail then I and others will see it there and hopefully one of us will get around to working something out programmatically.

https://github.com/mooz/xkeysnail
