### ISSUE TITLE
Got Cmd+Grave (physical) / Ctrl+Grave (logical) working on XFCE, MATE, and Cinnamon

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#260]
Hardware: White 2007 MacBook
OS: Linux Mint 20, 64-bit, XFCE ISO
DEs: XFCE, MATE, Cinnamon

Started with a Linux Mint 20 XFCE flavor, later manually installed `mint-meta-mate` and `mint-meta-cinnamon` to enable MATE and Cinnamon. Also tried Budgie but had lots of weird issues with it and eventually uninstalled it. Budgie would do things like have Cmd+Tab work fine but then later get stuck Cmd+Tabbing between only two applications, ignoring any other open applications. Logging out and back in did not fix it. 

This isn't exactly a bug report but rather a report of successfully getting Cmd+Grave (logical Ctrl+Grave) working as it is supposed to, as a shortcut for switching between the open windows of only a single application. So far this tweak of kinto.py is working apparently exactly the same way in XFCE, MATE, and Cinnamon, as long as I set the appropriate keyboard shortcut for that function in the control center for each DE. Without this code tweak I get the weirdness of XFCE seeing the Cmd+Grave combo as just "Control R" and activating the in-app window switching when simply hitting the Cmd key by itself. 

As usual before tweaking I could set other shortcuts for in-app switching such as Alt+Grave and it would work just fine. It was only when I tried to pair Grave with Cmd(Ctrl) that the DE wouldn't accept it. 

Here is the tweak that seems to work for me. 

```
define_keymap(None,{
    # Basic App hotkey functions
    K("RC-Q"): K("Alt-F4"),
    K("RC-H"): K("Alt-F9"),
    # Cmd Tab - App Switching Default
#    K("RC-Tab"): K("RC-F13"),                     # Default not-xfce4
#    K("RC-Shift-Tab"): K("RC-Shift-F13"),         # Default not-xfce4
#    K("RC-Grave"): K("M-F6"),                     # Default not-xfce4
#    K("RC-Shift-Grave"): K("M-Shift-F6"),         # Default not-xfce4
     K("RC-Tab"): K("RC-backslash"),               # xfce4
     K("RC-Shift-Tab"): K("RC-Shift-backslash"),   # xfce4
     K("RC-Grave"): K("RC-Grave"),   # xfce4
    # K("RC-Grave"): K("RC-Shift-backslash"),       # xfce4
```

At first I was having success by simply commenting out this line: 

```
    # K("RC-Grave"): K("RC-Shift-backslash"),       # xfce4
```

But that ended up working in MATE but not XFCE, where the weirdness noted above happened, almost as if XFCE couldn't see the Cmd+Grave shortcut. I thought maybe it was crazy to simply say, "Cmd+Grave equals Cmd+Grave", but I tried it anyway, and it worked! 

I have not yet tried IceWM on this machine so can't say yet whether it would also work there. This is not the low-mem machine where it needed to run IceWM. I also don't know if I care to try and reinstall Budgie. There doesn't seem to be a proper "mint-meta" package available for it on Linux Mint 20. 

Now, this may be working only because I installed all these other DEs manually after starting with an XFCE ISO. I got some errors similar to what I've seen elsewhere (on a Raspberry Pi 4 with a Desktopified Ubuntu Server, I think?), as shown here in this screenshot. It says Budgie detected in the screenshot, but I got similar errors for MATE and Cinnamon, I'm pretty sure. 

![Screenshot_2020-08-12_12-56-43](https://user-images.githubusercontent.com/64876997/90218003-2ea80500-ddaf-11ea-9d72-2824e3c5f085.png)

I have also managed to get a pretty good global menu setup working in both XFCE and MATE at this point, to rival the excellent implementation found in Twister OS for the Raspberry Pi. I tried Enso a while back and found that it felt very much like a distro that needs another couple of years of active development. 

So as a final note I'll have to reiterate that it may be helpful to some users to simply allow them to apply the XFCE4 system shortcuts wherever they want to see if it works better for them. On the systems I've so far run MATE, Budgie and Cinnamon on there always seems to be something missing that causes errors in the Kinto install process, as seen in the red text in the screenshot and the "No such schema" issue just above it. 

I have no understanding of why my tweak of simply saying "RC-Grave=RC-Grave" works better than leaving the mapping out entirely, but it works. So I'm leaving this here for my future reference if nothing else. 

Oh, and I first tried to set it to M-F6 like in the not-xfce4 section, but that didn't work either. At least in XFCE.

**Comment by rbreaves** [comment]
I’m not too surprised that that worked actually the differing hotkeys on somethings was more of a left over from xkb w/ certain DEs.

Also I hadn’t developed a good Perl & regex based method for fully toggling DE specific hotkeys then. I need to do similar work on a few other hotkeys & refactor things to avoid more system level key remaps pre Kinto.

**Comment by RedBearAK** [comment]
My XFCE setup imploded at some point for unknown reasons and I had to start all over. But I still haven't been able to fix my volume and brightness control OSD popup. I googled around for a bit but can't even figure out what process is responsible for displaying the media key OSDs. They don't look anything like the notifications from the XFCE notification daemon. Do you have any clue what package controls this? 

Here is a screenshot of the new ugly OSD with text, with the nicer original graphical version below it. I've even tried to force reinstall `mint-meta-xfce` but that seemed to have no effect. 

![volume_OSD_old_new](https://user-images.githubusercontent.com/64876997/90292126-c64c3880-de2d-11ea-89fd-c0251c4f5f10.png)

**Comment by rbreaves** [comment]
If you would like to try out some additional testing v1.2 has now been released with a new GUI setup and system tray for DE's that support appindicators.. basically most DE's I care about besides gnome3 and kde lol. There is a GUI app that will install on all of them with same functionality as the system tray though.

Closing this ticket.
