### ISSUE TITLE
Just wanted to say

### ISSUE THREAD

**Issue by picolens** [rbreaves/kinto#263]
Excellent excellent excellent!

What a great idea. First time multi/os user here. Install on Linux was flawless. Works like a charm

Thank you :)

**Comment by rbreaves** [comment]
Thanks for letting me know!

I plan to make an update pretty soon that will give Linux users a tray icon similar to how it works on Windows, if not better in some regards. I still need to do more testing however, unfortunately I've been caught up the last couple of weeks which has prevented me from doing all the VM testing that remains to be done - I know I have issues in the alpha and dev branch to sort out before releasing it into master.
