### ISSUE TITLE
Kinto stops working randomly on Windows 10

### ISSUE THREAD

**Issue by threkk** [rbreaves/kinto#272]
**Describe the bug**
The run Kinto and enable the Windows keyboard for the mappings. It works and I can make use of it. About 30s or 1 minute after, it stops working and resets to the original key mappings even if Kinto is still running and with the correct mapping selected. I click again on the same mapping selected and it starts working again, until the process repeats. After 3 or 4 times, it might stop and simply works. Same thing happens when locking the computer. 

**Expected behavior**
Once selected, not resetting to the default key mappings.

**Install Type:** Bare Metal
**Distro:** Windows 10 v2004 (Build 19041.450)
**Branch:** master
**Commit:** 558e86d

**Comment by rbreaves** [comment]
I’ve not experienced that, & I do dog food it on Windows 10 the most. Did you manually install autohotkey or did you let Kinto install it for you? I think there’s a version of ahk out there that Kinto doesn’t work well w/ & could fail if used. Kinto always installs the right & latest version, assuming you haven’t installed it.

Could also just try & run it directly & see what it does ~/.kinto/kinto.ahk.

**Comment by threkk** [comment]
Hi! I used the installer (it would be nice to have an easy way of installing it without chocolatey) and even when I run it by executing the file in the kinto folder.

**Comment by rbreaves** [comment]
I use chocolatey to ensure that autohotkey, and strawberry perl are installed, granted having users opt to install those themselves could/may be easier then having them install chocolatey. I tend to be package driven on Linux & Mac (brew) and if I want to expand Kinto's functionality in the future then chocolatey may help extend functionality further and that helps me build it out more rapidly.

I may consider allow it to install cmd.exe as well later on but it is not high up on my priority list right now.

You might consider an earlier release for Kinto to see how it fares? I am not aware of an issue or bug in the current master branch though.

**Comment by threkk** [comment]
I am also a big fan of package managers, I am myself a big fan of `brew`, but on Windows I prefer `scoop` over chocolatey as it messes less with the system. I will try move to an earlier version to see if it works better for me.

**Comment by matteron** [comment]
Not that it's much help, but I can second this experience.  It seems like autohotkey restarts, doesn't recognize my keyboard as an apple one and sets the mapping to be the windows one.  I'm not entirely sure how to keyboard detection works though, so I could be wrong on this.

**Comment by rbreaves** [comment]
@matteron hmmm I need to finish what’s going on in the alpha branch. You can turn off the autodetect & autoset keyboard option in that branch. That’ll resolve that issue at least in one way.

It’s possible that a usb device being connected or disconnect could trigger some unexpected behavior.

**Comment by threkk** [comment]
I believe we might be onto something... I am using a Bluetooth keyboard, and I believe it sometimes disconnects to save battery when I don't type in a while. It is unnoticeable in most of the cases but could be related with the keyboard detection.

**Comment by matteron** [comment]
It could very well just be the keyboard restarting randomly, acting as a disconnect.  Windows doesn't mention a device being removed though.

**Comment by desmondyeoh** [comment]
I'm on the same Windows build and uses Windows-style keyboard. It **kept changing to Mac-style keyboard style after 30sec-1min**, even after I set it to use Windows-style again and again. And I wasn't using any Bluetooth or external keyboard, only the built-in keyboard on my HP 15au102tx laptop.

Hmmm I tried looking at the repo but couldn't get a clue on how to turn off autodetect and autoset keyboard option. Which part should I change? Thankss!

**Comment by rbreaves** [comment]
@desmondyeoh You should be able to checkout the alpha branch via the following.

    git checkout alpha

and then start the install over (on top of itself should be fine, and in powershell as admin).

    py .\setup.py

this is what it should look like in the alpha branch and by default autodetect I believe will be turned off.

![image](https://user-images.githubusercontent.com/10969616/92689551-cc3a1a00-f304-11ea-806a-6404292a6ec0.png)

**Comment by slreclps** [comment]
This works great, thanks!

**Comment by rbreaves** [comment]
Added a couple of more updates into alpha just now to solve a couple of problems that existed in the alpha branch. It appeared like the autodetect toggle would stay on if it was ever turned on - so I fixed that. Also the Ctrl-C sigint combo to kill programs in the terminals was broken, along with a few other defaults.

**Comment by rbreaves** [comment]
What was in Alpha is now finally officially released as v1.2 so I will now close this ticket.
