### ISSUE TITLE
Script error if non-numeric characters are entered

### ISSUE THREAD

**Issue by Yuribtr** [rbreaves/kinto#277]
**Is your feature request related to a problem? Please describe.**
When setup.py start to run, user prompted to enter choice value, which can be non-numeric if in case of user's mistake. In this case script is falling to error.

**Describe the solution you'd like**
To make soft and user-friendly reaction on mistake.

**Describe alternatives you've considered**
Message that no valid number was entered or return to beginning of script.

**Additional context**
This will my first pull-request ever. I will prepare fix ASAP.

**Comment by rbreaves** [comment]
The setup has now been completely rewritten w/ full GUI and new features added. Please try out the v1.2 release.
