### ISSUE TITLE
Basic code completion not working for Intellij on Ubuntu 20.04

### ISSUE THREAD

**Issue by amitkec123** [rbreaves/kinto#288]
Thanks for your marvelous work and help with this repo.

Currently the basic  (also smart) code completion is not working for Intellij on Ubuntu 20.04.
Both the keys launch the activies and working like "command + space"

K("Super-Space"): K("C-Space"),             # Basic code completion
K("Super-Shift-Space"): K("C-Shift-Space"), # Smart code completion

**Comment by rbreaves** [comment]
I'll try and take a look at that here in a bit. I need to clear some hard drive space first as my VMs have grown a lot.

Thank you for letting me know, I most just attempted to convert what I had for IntelliJ under Windows and it may be off as well - if the linux side is.

**Comment by rbreaves** [comment]
I have not tested this fully, but if you would like to checkout the hotfix branch and test out this fix you may. I will be testing this across a few other distros before merging into master.

```
git checkout hotfix
or
git checkout b72def9
```

**Comment by amitkec123** [comment]
Works like a charm!

Thanks again for your great work.
cheers!

**Comment by rbreaves** [comment]
I apologize, I had placed Cmd-Space in the wrong location for vscode 😅. It has been relocated now and merged into master.
