### ISSUE TITLE
Unclear how to configure xkeysnail to interact with dvorak natively or via setxkbdmap (gnome, linux)

### ISSUE THREAD

**Issue by thor314** [rbreaves/kinto#290]
In my .xinitrc (config file for X11 server) I have the line
`setxkbdmap dvorak -option ctrl:nocaps`
which appears to be overwritten by xkeysnail. My current hack around is to tolerate a qwerty login and open a terminal to load the command in my `.zshrc`. It's not clear from your README, how to configure xkeysnail to integrate with these tools.

**Comment by rbreaves** [comment]
I’ve not tested things w/ Dvorak & I wouldn’t expect setxkbmap to play nice w/ xkeysnail - use one or the other.

Xkb was used in the past for Kinto but xkeysnail tends to be a lot easier. Uncommenting the line in ~/.config/kinto/kinto.py that says caps2cmd is all you should need (skip chromebook).

Closing ticket as I have no plans to test Dvorak w/o a Dvorak keyboard. If you are able to bring that support to xkeysnail by updating its Keys.py file then I’ll happily integrate that fix.

**Comment by thor314** [comment]
what do you mean you don't have a "dvorak keyboard"? 

"caps2cmd" does not appear in the kinto.py file, and I do not see a keys.py file.

**Comment by thor314** [comment]
Clarify, are you saying I ought to create a keys.py file something along the lines of the following:
```
define_keymap(None,{ #what should I put here instead of None?
    K("q"): K("'"),
    K("w"): K(","),
    K("e"): K("."),
})
```
The above fails to run when I drop it into kinto.py.

**Comment by thor314** [comment]
Looks like it's possible for me to go into `kinto/xkeysnail/xkeysnail/key.py` and modify lines 25 thru 67. Is this what you meant? Additionally, can I help you add this functionality for future users in some way?

**Comment by thor314** [comment]
so I went into the above mentioned file and changed lines as follows, but when I restart xkeysnail, these changes aren't reflected. Am I modifying the wrong file? 
```
    MINUS = 40 #12
    EQUAL = 26 #13
    BACKSPACE = 14
    TAB = 15
    Q = 45 #16
    W = 51 #17
    E = 32 #18
    R = 24 #19
    T = 37 #20
    Y = 20 #21
    U = 33 #22
    I = 34 #23
    O = 31 #24
    P = 19 #25
    LEFT_BRACE = 12 #26
    RIGHT_BRACE = 13 #27
    ENTER = 28
    LEFT_CTRL = 58 #29
    A = 30
    S = 39 #31
    D = 35 #32
    F = 21 #33
    G = 22 #34
    H = 36 #35
    J = 46 #36
    K = 47 #37
    L = 25 #38
    SEMICOLON = 44 #39
    APOSTROPHE = 16 #40
    GRAVE = 41 #?
    LEFT_SHIFT = 42
    BACKSLASH = 43
    Z = 53 #44
    X = 48 #45
    C = 34 #46
    V = 52 #47
    B = 49 #48
    N = 38 #49
    M = 50
    COMMA = 17 #51
    DOT = 18 #52
    SLASH = 26 #53
    RIGHT_SHIFT = 54
    KPASTERISK = 55
    LEFT_ALT = 56
    SPACE = 57
    CAPSLOCK = 29 #58
```

**Comment by rbreaves** [comment]
That would be the correct file key.py, part of xkeysnail. After modifying it you’ll need to reinstall xkeysnail.

cd into xkeysnail
Re-Install Just xkeysnail from source.

‘’’
sudo pip3 install --upgrade .
‘’’

**Comment by rbreaves** [comment]
Hmmm.. that doesn't seem to make much sense to me, it ought to be aligning the keycode inputs to what you are specifying afaik. For further assistance you may want to open a support ticket with xkeysnail or search their issue tickets.

https://github.com/mooz/xkeysnail
