### ISSUE TITLE
Ubuntu 20.10: No module named `prekinto`

### ISSUE THREAD

**Issue by nmnellis** [rbreaves/kinto#296]
**Describe the bug**
On install getting the following error
```
~/kinto$ ./setup.py 
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    from prekinto import *
ModuleNotFoundError: No module named 'prekinto'
```

**Install Type:** ./setup.py
**Distro:** Ubuntu 20.10
**Branch:** master
**Commit:** 139cff1

**Comment by rbreaves** [comment]
Oh s*... I just relocated that file thinking I no longer use that file. Ok one sec, bringing it back.

**Comment by rbreaves** [comment]
This latest commit on master should resolve it. https://github.com/rbreaves/kinto/commit/d2ae2a0b1d8392e7dacbd1c03cc4d4557eddfac1

Going to test the install now.

**Comment by rbreaves** [comment]
Install went fine, closing. Also removed some repetitive output as well that I thought had been removed already.
