### ISSUE TITLE
"Congratulations you've made Tux cry" after detecting keyboard

### ISSUE THREAD

**Issue by nmlt** [rbreaves/kinto#297]
**Describe the bug**
After pressing the second key left of my space bar, the keyboard assistant window displays the error message (or is it? Because there's also a checkmark...) "Congratulations you've made Tux cry". After closing that window a command line interface opens.

**Expected behavior**
A clear message what went wrong or that the setup succeeded.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04
**DE:** Gnome
**Branch:** master
**Commit:** 464ba63

Logs and status if relevant 
```
# xkeysnail
Okt 28 13:46:56 computer systemd[1]: Started xkeysnail.
Okt 28 13:46:56 computer sudo[37366]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuse>
Okt 28 13:46:56 computer sudo[37366]: pam_unix(sudo:session): session opened for user root by (uid=0)
Okt 28 13:46:57 computer sudo[37382]: localuser:root being added to access control list
```

**Additional context**
- Keyboard layout (physical) is German QWERTZ (second key left of space bar is the windows key)
- Keyboard layout selected in GNOME is English (intl., with AltGr dead keys)

I'm really happy to have found this app. This was what I have been looking for in my linux installation!

**Comment by rbreaves** [comment]
Lol, no that's normal. I guess my poor sense of humor towards linux users that prefer their normal Ctrl key 😅. I guess later I'll add small text below that saying to close the window and everything should be up and running.

**Comment by rbreaves** [comment]
Also if you prefer your right alt key to be in its normal location you can go into the Tweaks under Edit or Customize (sys tray) menu and select the AltGr option.
