### ISSUE TITLE
Broken installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by bryanhpchiang** [rbreaves/kinto#298]
**Describe the bug**
Standard bare-metal Ubuntu 20.04 desktop. Followed instructions in repository to install kinto, but no changes in modifier key behavior. Note: when I ran ./setup.py, kinto failed to detect my existing Python installations that are in my PATH, and it installed python3 on its own. Not sure if this affects keymap behavior.

```
(base) bryan@ito:~/work/kinto$ which python
/home/bryan/miniconda3/bin/python
(base) bryan@ito:~/work/kinto$ which python3
/home/bryan/miniconda3/bin/python3
```

**Expected behavior**
Modifier keys following macOS behavior.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04
**DE:** Gnome
**Branch:** master
**Commit:** git rev-parse --short HEAD
464ba63

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```
● xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-10-28 20:16:10 PDT; 14s ago
   Main PID: 24738 (sudo)
      Tasks: 2 (limit: 19067)
     Memory: 16.8M
     CGroup: /system.slice/xkeysnail.service
             ├─24738 /usr/bin/sudo /bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/bryan/.config/kinto/killdups.sh && /usr/local/b>
             └─24748 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /home/bryan/.config/kinto/kinto.py

Oct 28 20:16:10 ito systemd[1]: Started xkeysnail.
Oct 28 20:16:10 ito sudo[24738]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /h>
Oct 28 20:16:10 ito sudo[24738]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 28 20:16:10 ito sudo[24754]: localuser:root being added to access control list

(base) bryan@ito:~/work/kinto$ systemctl --user status keyswap
Unit keyswap.service could not be found.
(base) bryan@ito:~/work/kinto$ journalctl --user-unit=keyswap.service -b
-- Logs begin at Fri 2020-10-09 21:57:35 PDT, end at Wed 2020-10-28 20:16:41 PDT. --
-- No entries --

**Screenshots**

**Additional context**

**Comment by rbreaves** [comment]
Looks like it's running according to that log. Can you throw it into Debug mode under help? And see what happens when you try to use the cmd key position like you would on a mac?

That might not resolve anything for the systemd service, but it would help us rule out whether or not xkeysnail and the setup in general went correctly or not.

**Comment by bryanhpchiang** [comment]
Fixed - kinto only supports /usr/bin/python3 so I just deactivated my conda environment and used the system-level python to start kinto.sh and then everything went as expected.

Everything works except emacs binding in text inputs (C-n, C-p, C-b, C-f). Is there any way to configure these? Thanks!

**Comment by bryanhpchiang** [comment]
Update: I wonder if there's a way to map the standard emacs bindings to the arrow keys.

**Comment by rbreaves** [comment]
You can map whatever you want however you want, the GUI app directs you to the config file, as does the system tray and DEs that support appindicators.

~/.config/kinto/kinto.py is the location of the file. By default I try and apply keymaps that are used most universally, emacs probably should be part of it. If you update your file and want to create a PR of the changes I'd review it and probably merge it. I don't use emacs bindings myself otherwise I'd probably have added it myself. Rather it be done by someone who does use emacs, I am not sure how extensive they are on macOS and I'd probably need to confirm the keybinds exists on macOS as well.

**Comment by rbreaves** [comment]
Also all of my python scripts should have this in the top line

```
#!/usr/bin/env python3
```

So regardless of where python3 is it is not a hardcoded path,, but I am not sure about xkeysnail which Kinto heavily uses to do most of the work.

**Comment by bryanhpchiang** [comment]
The basic emacs bindings are universal and built-in on macOS. If you navigate to any text input, bindings such as C-e C-a C-n C-p C-f C-b will let you navigate around without reaching for your mouse or arrow keys.

I'm tried to edit the configuration file, I added this component:

```
# L219
define_keymap(None, {
   K("RC-b"): K("Left")
...
})
```

Any suggestions on mapping key combinations to the arrow keys? Thanks!

**Comment by rbreaves** [comment]
I believe that ought to work, but when you place it under None that is only effective for GUI based apps, place it under the area near the bottom define_keymap TermStr if you want it applied to the terminal apps as well.

LC being your Physical Left Control key and the RC being the Cmd key essentially. Under the None (GUI) area LC or the physical Ctrl key is Super in that case.

**Comment by bryanhpchiang** [comment]
Got it, thanks! Beautiful tool.

My final configuration:

```
K("Super-b"):K("Left"),
K("Super-f"):K("Right"),
K("Super-n"):K("Down"),
K("Super-p"):K("Up"),
```
