### ISSUE TITLE
Kill input from current position to end of line

### ISSUE THREAD

**Issue by bryanhpchiang** [rbreaves/kinto#299]
On macOS, Ctrl-K universally kills from your current cursor position to the end of the line. Is there any way to replicate this on Ubuntu?

**Comment by rbreaves** [comment]
replicate what already happens when you pretty Cmd-Right perhaps?

This is what currently happens under the None (GUI area).

```
...
define_keymap(None,{
...
    K("RC-Right"): K("End"),                      # End of Line
    K("Super-e"): K("End"),                       # End of Line
...
```
Legend

Virtual = Physical

GUI
RC = Cmd
Super = Ctrl

Term
RC = Cmd
LC = Ctrl

**Comment by bryanhpchiang** [comment]
This moves my cursor to the end of the line, but it doesn't delete the text. Not even sure if this would be possible on Linux to be honest.

**Comment by rbreaves** [comment]
Oh I get you, and no that is completely possible, you can setup with the xkeysnail a multi-press combo and I do that with sublime text specifically for a particular combo that is one hotkey on macOS, but 2 on linux and windows.

```
K("C-M-v"): [K("C-k"), K("C-v")],           # paste_from_history
```

So yea just set up like an array contained in [ ] backets.

**Comment by bryanhpchiang** [comment]
Thanks so much - it works! Amazing how flexible it is. Originally I was trying to map it do K("C-Shift-Right"), since that highlights from the current position to the end of the line when kinto is activated. But it was only highlighting until the next word. And then I realized that it was because of the built-in command ```K("RC-Shift-Right"): K("Shift-End"),          # Select all to End of Line```, so my final result is just:


```
K("Super-k"): [K("Shift-End"), K("Backspace")],
```

**Comment by rbreaves** [comment]
Yea, that conflict could be avoided in autohotkey w/ a $ in front of it but not sure about xkeysnail. It’d probably take an update of some kind to prevent that from colliding. 

Glad it’s working out for you though!
