### ISSUE TITLE
Unable to enter "at" symbol

### ISSUE THREAD

**Issue by probonopd** [rbreaves/kinto#3]
Using this, I can no longer enter the "at" symbol which normally requires me to press RightAlt-Q on a German keyboard. I could not find a way to enter this symbol anymore.

**Comment by rbreaves** [comment]
Sounds like other language keyboards may have a need for only the left sided keys to swap. If that’s the case then a more appropriate keymap option needs to be found or created, w/ hopes it can be applied universally more or less.

Please review this gist & see if you can find a more appropriate altwin option that works for your region.

https://gist.github.com/rbreaves/f4cf8a991eaeea893999964f5e83eebb

If you can confirm a keymap that works, for GUI & Term then I will try to review & test it. I have a Japanese keyboard that I can test with & US English.

You may also want to try the suggestions here for altwin.

https://superuser.com/questions/246345/how-can-i-make-my-super-keys-windows-key-behave-more-like-ctrl-alt-shift-in-li

You can also look at my test.py script if you want to test out different keymaps or confirm what a key is being detected as.

‘’’
pip3 install —user pynput
./test.py gui 0 1 0 0
./test.py term 0 1 0 0
‘’’
The arguments are as followed.
{uitype} {applyrules} {windows_keyboard} {chromebook_keyboard} {mac_keyboard}

**Comment by probonopd** [comment]
Sorry, I have no real clue how this stuff all works...

**Comment by rbreaves** [comment]
That's fine I need to create some better debug tools that are easy to use. I created test.py as a simple and quick test for testing current and new keymap options while also having the ability  to test multiple keyboards at the same time.

A keymap that works individually does not guarantee that it'll operate as expected with 2 or more keyboards attached, unless someone runs a test on it. I am not going to speculate on why that is, because I honestly don't know - device id arguments do not appear to be applied properly within setxkbmap or xkbcomp so I avoid using them, if I can.

**Comment by probonopd** [comment]
> 2 or more keyboards attached

Have you  ever seen someone do this?

**Comment by rbreaves** [comment]
Me lol, I often attach my laptops to a monitor while keeping the screen open and keyboard available. Sometimes I use an external keyboard and sometimes I don't as I always have 3 to 5 computers running at my desk with 1 or 2 keyboards as well, and a 4-port kvm switch. I have 3 desktops and 4 laptops and some ARM based devices as well.

Also I am still not sure how to bring back your @ symbol, you could try looking at Autokey, but from having used it recently to solve your arrow key issue I don't see an option to specifically remap just the right or left alt or ctrl modifier. I know there's a way to fix your issue, but I am not sure what that fix would look like, the best solution would be a xkb filed based solution.

**Comment by rbreaves** [comment]
This might address your problem, I do not know if it is something I can or should integrate into Kinto though. It's a system level file for one thing, and so far I have been able to do a lot with Kinto without involving any system level or root privileges and I'd like to keep it that way.

The link I found says to do the following (I changed fr to de)

Modify the file /etc/default/keyboard to have :
XKBMODEL="macintosh"
XKBLAYOUT="de"
XKBVARIANT=""
XKBOPTIONS=""

And to blank out or comment out all other lines in the file.

https://stackoverflow.com/questions/26205801/how-to-use-a-french-macbook-pro-keyboard-with-ubuntu

My own file looks like this.

```
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
```

**Comment by rbreaves** [comment]
I don't think there's much I can do about this as it may be the result of simply applying the stock ctrl or altwin swap options of setxkbmap. Without more information I have to close this ticket, I have no actionable information that will allow me to resolve this issue.

**Comment by probonopd** [comment]
Thanks for all your effort @rbreaves. Highly appreciated.
