### ISSUE TITLE
how to remap alt + hjkl to arrow keys?

### ISSUE THREAD

**Issue by tzsword** [rbreaves/kinto#301]
When I use xmodmap configuration, super do not work

```
# .Xmodmap
keycode 64 = Mode_switch

keysym h = h H Left 
keysym l = l L Right
keysym k = k K Up
keysym j = j J Down
```
> kinto version: 
    Kinto v1.2-2 build 1aa23c2

> kinto keyboard type:
   Apple

> os version：
  Ubuntu 20.04.1 LTS

**Comment by rbreaves** [comment]
I doubt that xmodmap really needs to work. Please read this thread & or the ReadMe even on how to create shortcuts in Kinto & remove your xmodmap config.

https://github.com/rbreaves/kinto/issues/299

If you still have questions then let me know. Closing for now.
