### ISSUE TITLE
Sudo corrupt

### ISSUE THREAD

**Issue by charlyeds** [rbreaves/kinto#304]
I recently install kinto, and now when i try to make any sudo, it shows me

Segmentation fault: core dumped

I have to try uninstall kinto but no luck

What can i do?

thanks

**Describe the bug**

**Expected behavior**

**Install Type:** Bare Metal or VM
**Distro:** Name + Version
**DE:** Gnome, XFCE, KDE
**Branch:** master, dev
**Commit:** git rev-parse --short HEAD

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```

**Screenshots**

**Additional context**

**Comment by rbreaves** [comment]
Hmmm.. I guess you’ll need to reboot into your grub menu & load up into recovery & mount your partition & remove the limitedadmins file located at /etc/sudoers.d/

I’ve only heard of this occurring once before & to RedBearAK - he was targeting some rather esoteric distros. I only test against mainstream/popular distros.

I don’t mind making some changes to ensure something that severe won’t occur though.

**Comment by charlyeds** [comment]
Very thanks!! Sudo was restored. I could delete the limitedadmins file.
Please,  how can i restore the left ctrl key to original? I can't Ctr+C /Ctrl+V....
 I tried with setup but no luck, maybe i'll delete some file and i don't know where the backup is located
Thanks!

**Comment by rbreaves** [comment]
when the service doesn't run the remaps don't occur, so just running "sudo systemctl stop xkeysnail" is enough. Although the overlay key (super) won't be restored unless you uninstall it by re-running setup with the -r command as described in the read me. "./setup.py -r"

I will likely change that in a future update so that stopping the service will also restore your overlay key.

**Comment by rbreaves** [comment]
Pretty sure this is the actual fix the sudo corruption issue.


94595a3

**Comment by charlyeds** [comment]
Hi!
No luck. The sudo violation fault persists.

Thanks!

Desactiva este aviso poniendo la variable de config advice.detachedHead en false

HEAD está ahora en 51c3690 Update version to 0.3.0
Processing /media/DADES/USERS/UBUNTU/DOWNLOADS/kinto/xkeysnail
Collecting evdev
  Downloading evdev-1.3.0.tar.gz (25 kB)
Collecting inotify_simple
  Downloading inotify_simple-1.3.5.tar.gz (9.7 kB)
Collecting python-xlib
  Downloading python_xlib-0.28-py2.py3-none-any.whl (176 kB)
     |████████████████████████████████| 176 kB 3.8 MB/s 
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->xkeysnail==0.3.0) (1.15.0)
Building wheels for collected packages: xkeysnail, evdev, inotify-simple
  Building wheel for xkeysnail (setup.py) ... done
  Created wheel for xkeysnail: filename=xkeysnail-0.3.0-py3-none-any.whl size=17545 sha256=804aec0f567634af3f41b886fa6e117e2ee3cdfe5e30eed8cc9f7454ff974fea
  Stored in directory: /tmp/pip-ephem-wheel-cache-68h65zmh/wheels/1d/e9/ad/1db6d80b0f448ee477b42ab7aec3ba72218536b6f772c6f4b6
  Building wheel for evdev (setup.py) ... done
  Created wheel for evdev: filename=evdev-1.3.0-cp38-cp38-linux_x86_64.whl size=84768 sha256=7df3dcfc841694fa8e18d26ceba777aff8637b55f4582652ec23697ab0f1baf1
  Stored in directory: /root/.cache/pip/wheels/95/38/0d/c82d6e2bc6850898531415320b9cdc89e55f6209af1b02bedc
  Building wheel for inotify-simple (setup.py) ... done
  Created wheel for inotify-simple: filename=inotify_simple-1.3.5-py3-none-any.whl size=7688 sha256=c85c926d78b0b5b5ed05aff05073d9264c4181b9da29a5df34795e7403403ee9
  Stored in directory: /root/.cache/pip/wheels/85/b2/be/354e28439e9b15a9a77924041be045e499f11bb03493529246
Successfully built xkeysnail evdev inotify-simple
Installing collected packages: evdev, inotify-simple, python-xlib, xkeysnail
Successfully installed evdev-1.3.0 inotify-simple-1.3.5 python-xlib-0.28 xkeysnail-0.3.0
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
sed: no se puede leer ./xkeysnail-config/xkeysnail.service.new: Permiso denegado
sed: no se puede leer ./xkeysnail-config/limitedadmins.new: Permiso denegado
Service file added to /usr/lib/systemd/system/xkeysnail.service
./xkeysnail_service.sh: línea 544:  6781 Violación de segmento  (`core' generado) sudo chown -R root:root "$xkeypath"xkeysnail.service
Failed to set ownership...
./xkeysnail_service.sh: línea 544:  6788 Violación de segmento  (`core' generado) sudo chmod 644 "$xkeypath"xkeysnail.service
Failed to set permissions...
./xkeysnail_service.sh: línea 544:  6795 Violación de segmento  (`core' generado) sudo ln -s "$xkeypath"xkeysnail.service /etc/systemd/system/xkeysnail.service
Failed to create soft symlink...
./xkeysnail_service.sh: línea 544:  6804 Violación de segmento  (`core' generado) sudo ln -s "$xkeypath"xkeysnail.service /etc/systemd/system/graphical.target.wants/xkeysnail.service
Failed to create soft symlink for graphical target...
./xkeysnail_service.sh: línea 544:  6811 Violación de segmento  (`core' generado) sudo systemctl daemon-reload
./xkeysnail_service.sh: línea 544:  6819 Violación de segmento  (`core' generado) sudo systemctl disable xkeysnail
./xkeysnail_service.sh: línea 544:  6828 Violación de segmento  (`core' generado) sudo systemctl stop xkeysnail
./xkeysnail_service.sh: línea 544:  6849 Violación de segmento  (`core' generado) sudo pkill -f kintotray > /dev/null 2>&1
Adding xhost fix...

Kinto install is complete.

If the setup wizard fails to appear then please run this command.
~/.config/kinto/gui/kinto-gui.py

You can then either Google what dependencies you may be missing
or open an issue ticket.

Gnome may not support appindicators well, so by default you may need to install packages before enabling the System Tray.
You may try one of the following extensions.
    1) AppIndicator and KStatusNotifierItem Support
    2) TopIcons Plus

Note: you may want these supporting packages
'sudo apt install gnome-tweaks gnome-shell-extension-appindicator gir1.2-appindicator3-0.1'

**carles@UBUNTU-PC:~/Descargas/kinto$ sudo
Violación de segmento (`core' generado)
carles@UBUNTU-PC:~/Descargas/kinto$ sudo
Violación de segmento (`core' generado)**

**Comment by charlyeds** [comment]
Hi, problem was resolved. I have /home in a NTFS partition. It seems that the flow was not properly exemptioned when it tries to write in that partition type
Thanks for all! Kinto now works!

**Comment by rbreaves** [comment]
That would make sense, there are a number of permissions that I set while in the home directory, and then I relocate files afterwords. I could instead move the files to their system folder locations and then set those permissions, that might resolve the issue.
