### ISSUE TITLE
Upgraded to 1.2-2, now Apple keyboard shortcuts don't work at all

### ISSUE THREAD

**Issue by eperitus** [rbreaves/kinto#308]
**Describe the bug**
Ran through exact instructions from the video in the readme.  Now Apple shortcuts don't work at all.  They were working fine in an earlier version (1.1 I think?).

Tried clicking Keyboard menu, then Apple, restarting Kinto, none of the usual shortcuts work. (Alt/Cmd-Tab for the app switcher, Alt/Cmd-T to open a new tab, etc.)

Using Ubuntu 20.04 laptop with built-in Lenovo keyboard.

**Expected behavior**
Expected Apple keyboard shortcuts to work like they were before.

**Install Type:** Bare metal / laptop
**Distro:** Ubuntu 20.04 LTS
**DE:** Gnome
**Branch:** master
**Commit:** 1aa23c2

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```

**Screenshots**

**Additional context**

Reverting to the old version with git clone -b 1.1-12 works fine.

**Comment by rbreaves** [comment]
The installer should end the service, if running, before installing - if it were  running however then the remap wizard would definitely fail. I should probably encourage users to uninstall the previous first.

Could you try uninstalling the old & then installing the latest 1.2? Also running debug under help could be helpful as it will give you more info & we can go from there.

**Comment by rbreaves** [comment]
I did discovered an issue with the installer, resulted in a sudoers file being created before xkeysnail installs and that could create a problem, it may be worth trying again in 1.2-3. Closing ticket until I hear back.

```
git pull origin master
git fetch --tags
./setup.py
```

If you are unable to re-install or have any sudo issues you can run this and remove the 9th line referencing xkeysnail to fix sudoers.

```
pkexec nano  /etc/sudoers.d/limitedadmins
```
