### ISSUE TITLE
Debian: system tray not working

### ISSUE THREAD

**Issue by SWBZA** [rbreaves/kinto#309]
Hi.

I've just installed Kinto.  Thank you!  I've been looking for this app.

One issue: the option to select "Tray Enabled" under File in Kinto.sh seems to be disabled.  I can't select it - when I click on it, nothing happens.  Autostart, just above it, accepts a click and the square goes blue / unselect as expected.  I can't find how to fix this, as much as I've Googled.

Thanks in advance, 
Schalk

**Comment by rbreaves** [comment]
I did discovered an issue with the installer, resulted in a sudoers file being created before xkeysnail installs and that could create a problem, it may be worth trying again in 1.2-3.

If you are unable to re-install or have any sudo issues you can run this and remove the 9th line referencing xkeysnail to fix sudoers.

```
pkexec nano  /etc/sudoers.d/limitedadmins
```
