### ISSUE TITLE
Does Kinto work on KDE?

### ISSUE THREAD

**Issue by nemonein** [rbreaves/kinto#310]
Hello. Thank you for your effort.
I'm using KDE Neon(user edtion, up-to-dated version), and installed kinto.sh.
(KDE Neon is an Ubuntu based KDE distribution.)
However, it does not seem to work.

Here are the messages from Kinto console.
```
11월 09 23:24:48 nemo-desktop sudo[13222]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/nemokden/.config/kinto/killdups.sh &&  --quiet --watch /home/nemokden/.config/kinto/kinto.py
11월 09 23:24:48 nemo-desktop sudo[13222]: pam_unix(sudo:session): session opened for user root by (uid=0)
11월 09 23:24:48 nemo-desktop sudo[13224]: localuser:root being added to access control list
11월 09 23:24:48 nemo-desktop sudo[13223]: /bin/bash: --quiet: 명령어를 찾을 수 없음
11월 09 23:24:48 nemo-desktop sudo[13222]: pam_unix(sudo:session): session closed for user root
11월 09 23:24:48 nemo-desktop systemd[1]: xkeysnail.service: Main process exited, code=exited, status=127/n/a
11월 09 23:24:48 nemo-desktop systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
11월 09 23:24:51 nemo-desktop systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 88.
11월 09 23:24:51 nemo-desktop systemd[1]: Stopped xkeysnail.
11월 09 23:24:51 nemo-desktop systemd[1]: Started xkeysnail.
```

/bin/bash: --quiet: 명령어를 찾을 수 없음 means "could not find the command".

Any suggestions are welcome.

**Comment by rbreaves** [comment]
It appears something failed during the install xkeysnail and will need to be fixed. It had worked at one time, but perhaps was broken in the transition to 1.2.

```
root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/nemokden/.config/kinto/killdups.sh &&  --quiet --watch /home/nemokden/.config/kinto/kinto.py
```

This part here
```
&&  --quiet --watch /home/nemokden/.config/kinto/kinto.py
```

It should say ```&&  xkeysnail --quiet --watch /home/nemokden/.config/kinto/kinto.py```

If xkeysnail exists but the install must have failed.. I need to change the install to check for that it seems instead of assuming the install was successful it seems.

**Comment by nemonein** [comment]
Thank you for quick reply.
I'll wait for the next release.

For the record, xkeysnail is installed without any problem.

**Comment by rbreaves** [comment]
Hmmm that’d be even more odd. The script is designed to run a which xkeysnail command to add the full xkeysnail path to the systemd service & it appears when run the system did not report back anything like expected.. that’s why I assumed the xkeysnail install must have had a soft failure.

**Comment by rbreaves** [comment]
I did discovered an issue with the installer, resulted in a sudoers file being created before xkeysnail installs and that could create a problem, it may be worth trying again in 1.2-3.

```
git pull origin master
git fetch --tags
```

If you are unable to re-install or have any sudo issues you can run this and remove the 9th line referencing xkeysnail to fix sudoers.

```
pkexec nano  /etc/sudoers.d/limitedadmins
```

**Comment by nemonein** [comment]
Thanks, now I can run Kinto, but there are still problems.
I might open another issue for this.
