### ISSUE TITLE
Feature Request - Add support for f14 - f19 keys

### ISSUE THREAD

**Issue by wdfinch** [rbreaves/kinto#312]
Currently, the f14 - f19 keys are not recognized while running kinto in Ubuntu 20.04.1 LTS. I am not sure about other distros, but I expect similar behavior. Being as many users will be using an Apple keyboard which provides these keys, I think it would be great to add support to recognize them.

**Comment by rbreaves** [comment]
I believe that will need to be added xkeysnail or my fork of xkeysnail. Closing this enhancement request, it's addition may be mentioned in a future release, but it will be done xkeysnail directly.

https://github.com/rbreaves/xkeysnail

**Comment by wdfinch** [comment]
Sounds good. Thanks.
