### ISSUE TITLE
Can't get through new installer in MATE

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#315]
So the problem with your newfangled GUI installer is that there is often interference in various DEs because they want to take over meta keys like the "Win" key to activate the built-in application menu (The clones of the Windows Start menu that now exist in most Linux DEs). 

For instance, trying to set up Kinto 1.2-3 in MATE I can't get through the GUI installer which asks me to press the second key to the left of the space bar, which on this keyboard is "Win". But the Kinto installer can't detect that key because it keeps activating the MATE application menu. I think something similar happened in XFCE but I was able to track down the keyboard shortcut setting and stop that from happening. In MATE I have been searching for a while and still can't figure out where to change this setting. It doesn't seem to exists anywhere in the MATE Keyboard Shortcuts app. 

Anyway, the point is that the Kinto installer really needs to provide a backup strategy for identifying the keyboard and mapping keys when this sort of interference is going on. And it shouldn't be too hard to provide the user with some simple instructions on where to look in common DEs like XFCE, MATE, Cinnamon, etc., to cancel out the interfering keyboard shortcuts. I'm still finding I have to go fix the shortcut for the Alt+Tab window switching, and I'm still having no luck with the Alt+Grave function. I always had to manually edit the kinto.py file to fix that and now it seems to be very different so I'm not sure how to edit it. 

This is on a standard and very fresh install of Linux Mint 20 on a Lenovo m93p, So there can't be anything from previous 1.1 versions causing me any problems, and the MATE and XFCE shortcuts were set to the Mint defaults while installing Kinto.

**Comment by rbreaves** [comment]
I might make mention of the need to unmap the overlay key, assuming the user is using a DE I do not know how to unmap the overlay key on. I thought Mate would get recognized the same as gnome, but perhaps not. Checking this now and will make sure I know which command needs to run.

I have no current plans to change the GUI installer, I'd rather fix it by disabling the Super key for all supported officially supported DE's and/or warn the user to make sure the Win/Super is unbound. Too much confusion is created when I request users to set their keyboard or keys manually versus just having them press 1 or 2 keys and then setting everything based on that.

**Comment by rbreaves** [comment]
echoing out the DE name via this near the top of the xkeysnail_service.sh is sufficient to figure out how to add whatever DE support someone may want to add.

xkeysnail_service.sh
```
echo $dename
pause
```

Modified line 76 to include mate as I should have done already.
https://github.com/rbreaves/kinto/commit/6101213537cda03a9728f7b80c02a7e72360287e
```
if [[ $dename == "gnome" || $dename == "budgie" || $dename == "mate" ]]; then
```

**Comment by RedBearAK** [comment]
I finally discovered where the shortcut is, at least in Linux Mint MATE. I guess maybe it's actually a special Linux Mint menu plugin (not sure), which is why I couldn't find it in the standard MATE keyboard shorcut app. 

I got there finally by right-clicking on the Mint menu icon on the taskbar and going into the settings for the menu. 

Sometimes I really hate Linux. It's such a Frankenstein's monster of miscellaneous parts. 

Anyway, the central problem is that you need to be able to always disable or at least detect and warn the user when there is interference from the DE happening. If you can get past that interference, I'm sure the GUI installer will work fine. 

But I can't approve of the screen that (I'm guessing?) indicates "success" in the GUI installer. I have to tell you that when I first saw that screen with the Tux silhouette, the giant green checkmark, and the "Congratulations you made Tux cry", I was very, very confused. 

There is no button to close the window, no clear indication that the install succeeded, and when you close the window with the X in the corner there is another sort of terminal window behind it that also has to be closed. Which has some fairly confusing text in it. 

The way this is presented, I'm still not certain my installs of Kinto have actually succeeded without errors. It's very unnerving.

**Comment by rbreaves** [comment]
I have gotten that feedback at least once before, I would think the green circle and checkmark would be fairly indicative that it was successful. At any rate the installer has been properly fixed for Mate as of now. Updated it to also include a warning about the overlay key for other DE's that may not yet have been added. I also have a video available for anyone that wants to see the install setup before or after they initiate it, so I don't feel the crying & cursing penguin is that much of an issue - just my poor attempt at humor.

A bigger issue was resolved with today's update though that involved the sudoers.d file. I ensure that xkeysnail is in fact installed before it continues - before the script assumed too much and it no longer does that. It will immediately stop if that's an issue.

**Comment by rbreaves** [comment]
Also the Kinto terminal looking GUI app that appears does so primarily because and in case the system tray fails to appear for any reason. Even if the system tray process is set to run there is no absolute guarantee the DE supports it even if I think that it does. I do try and detect it properly though and any DE that supports AppIndicators should support it. I know it is particularly useful on stock Ubuntu with Gnome3 and KDE because they lack AppIndicator support by default.

**Comment by RedBearAK** [comment]
>I have gotten that feedback at least once before, I would think the green circle and checkmark would be fairly indicative that it was successful. At any rate the installer has been properly fixed for Mate as of now. Updated it to also include a warning about the overlay key for other DE's that may not yet have been added. I also have a video available for anyone that wants to see the install setup before or after they initiate it, so I don't feel the crying & cursing penguin is that much of an issue - just my poor attempt at humor.

Primary issue is that the graphics just end up looking like a jumbled mess. There's too many things mixed together, and the text is ambiguous in meaning. 

There's no problem with wanting to put a funny graphic of Tux crying because you are making him type like a Mac. I kind of figured that's what you're going for, but it took me a while. The real issues is that there's nothing separate from that, that cleanly and clearly says something simple like, "Kinto is now installed and running. Check the icon in system tray for configuration options. Have fun!" And then along with that you need to conform to a fairly universal UI standard and provide a single GUI button that says something like "Close" or "Done" that closes the installer window. The lack of any button to close the window is a huge contributor to the feeling that the installer "failed" partway through. 

>Also the Kinto terminal looking GUI app that appears does so primarily because and in case the system tray fails to appear for any reason. Even if the system tray process is set to run there is no absolute guarantee the DE supports it even if I think that it does. I do try and detect it properly though and any DE that supports AppIndicators should support it. I know it is particularly useful on stock Ubuntu with Gnome3 and KDE because they lack AppIndicator support by default.

Think about this from a Linux newbie perspective. What is the user supposed to do with this extra terminal window that doesn't close when you close the main GUI installer? You know I'm a user capable of successfully editing a sudoers file without crashing the system, and even I don't immediately know what to do with this window. It just sits there giving the impression that something went wrong during the install process. 

Consider shunting the text to an error log or into the terminal where we ran setup.py in the first place. Or at the very least try and detect when it's actually necessary to keep that window open, if it's really necessary for some reason, and somehow explain what the user is supposed to do with it besides closing it. 

>A bigger issue was resolved with today's update though that involved the sudoers.d file. I ensure that xkeysnail is in fact installed before it continues - before the script assumed too much and it no longer does that. It will immediately stop if that's an issue.

That sounds like a very good improvement. Those sudoers problems are awful when they happen.

**Comment by rbreaves** [comment]
Well I may change the wording a little later on, it isn't a pressing issue. There were a number of challenges getting it as far as it is and the decision to no longer have users set up various tweaks during the setup was in part to simplify the install and to prepare it for packaging into various repos in the future. Between the setup dialog, system tray and GUI app there were a lot of variables that had to be tested against one another and possible routes users could go.

For the number of people I believe to be downloading and using the project I'd say the number of complaints are pretty low, new users may have been re-installing it twice though as I am not sure how any could have gotten around the xkeysnail sudoers.d issue that was created recently. I don't think that issue existed on 1.1 and maybe not on the initial 1.2 release either but I haven't gone back to check either. I just know the order of things were not proper. I think before I had only been referencing xkeysnail without the path and then felt for security reasons it is better to define it like I do for most everything else. That's fine as long as the install of it has already occurred.

Also I pretty well assume when people see the 2nd window and notice that it has a green Active status in the bottom right corner they'll recognize that everything went fine. If it doesn't then it'll stay red - I want users to be able to easily report issues to me. One change I need to make though is making sure users can copy the text in the VTE based window as that does not seem to be the case now, I assume I can enable that somehow. They could screenshot it though. Additionally Kinto itself does not start until the Setup install has been completed (aka closed) and while users may not see a button to indicate the Window can be closed with the enter key I don't really see the issue with having them click the X button either. It is somewhat modeled after wizards on macOS more or less and yes - they don't give users very much options either or indication of what is going on in the background. It is what it is mostly, but I do try and at least direct them to both the GUI app and the system tray if I feel their DE is capable of a system tray. I also give additional output in the terminal window they run the setup file from to help them enable system trays on some specific DEs.

**Comment by RedBearAK** [comment]
>Additionally Kinto itself does not start until the Setup install has been completed (aka closed) and while users may not see a button to indicate the Window can be closed with the enter key I don't really see the issue with having them click the X button either. It is somewhat modeled after wizards on macOS more or less and yes - they don't give users very much options either or indication of what is going on in the background. 

I would find it highly unusual to have an installer or any other interactive dialog in macOS or Windows that fails to have a GUI button to dismiss the window. It is a UI standard. 

>Also I pretty well assume when people see the 2nd window and notice that it has a green Active status in the bottom right corner they'll recognize that everything went fine. If it doesn't then it'll stay red - I want users to be able to easily report issues to me. One change I need to make though is making sure users can copy the text in the VTE based window as that does not seem to be the case now, I assume I can enable that somehow. They could screenshot it though.

I see what you're trying to go for there. But please realize that you're probably suffering from a warped perspective on the technical level of most of the users who attempt to install Kinto. The people who manage to make their way here to your GitHub and leave bug reports are on a much higher level technically than the average computer user, even in Linux. You'll probably never hear from most of the users who have problems with the installer, because they don't have the technical skills to have any clue what's going on and try to file a bug report. They just give up as soon as it fails to work. 

So I disagree with the importance of cleaning up the install process. If you want Kinto to become widely used.

**Comment by rbreaves** [comment]
Well regardless I feel it was more important to get it pushed out, even at the state it was at, and there were plenty of other UI and backend related issues that had to be ironed before the 1.2 release that would have also been much more annoying to the end users had I not resolved them. Of course in all cases it's an app mostly developed by me, and as always I will happily accept any PRs to help further the goals of this app. And you can always look at the commits that I make to better understand how you or someone else might have gone about resolving an issue within this app.

GUI app development is also a little bit different of a beast than backend work or scripting and to be honest this is really my first time working with Gtk3 to any real extent, and in general I don't get to work on desktop based GUI apps much compared to mobile or web development.

**Comment by rbreaves** [comment]
Typically speaking I do not like making big changes like in the 1.2 release and would prefer more incremental updates, because yes - you do realize that the larger the release the greater the risk that something might not work as expected. But getting the GUI installer in place wasn't minor and in part because of architectural changes that went a long with it for a future repackaging into repos.
