### ISSUE TITLE
Adding in emacs bindings by default

### ISSUE THREAD

**Issue by bryanhpchiang** [rbreaves/kinto#336]
I've written emacs bindings for kinto on both Windows and Linux. These are part of macOS by default - wondering if these should be built into kinto by default as well? Thanks!

**Comment by rbreaves** [comment]
Probably should be, I just don’t use emacs myself. I’d you provide a PR I will review it & accept it if there are no conflicts or issues that I can see.

**Comment by bryanhpchiang** [comment]
These bindings are universally available on macOS / extremely common for text editing (they're just named emacs style). 

Windows: https://gist.github.com/bryanhpchiang/3b128368358d365d36ce03c3b2f8d28d#file-kinto-ahk-L332
Linux: https://gist.github.com/bryanhpchiang/98ab70cb906a0616973a2c3703243400#file-kinto-py-L220

**Comment by rbreaves** [comment]
Wonder if I should apply it to terminals or not too.. I feel like that might create issues though. Adding it to the GUI side of things I see little issue as I don’t think Super based hotkeys (while on the Left Control key) causing any issue.

**Comment by rbreaves** [comment]
While adding the ahk modifications I am not sure why your file has $#Space in it.. mine ha $^Space already.. I suspect you must have made changes to Cmd+Space for some reason and then ended up re-implenting, except without the $ symbol which prevents the possibility of a looping remap, in some cases.

Also not touching the Capslock remap on the Windows side atm, it does exist on the Linux side and I will try and meet parity with that later, but it needs to be implemented in the same manner via a tweaks panel.

**Comment by rbreaves** [comment]
@bryanhpchiang I should have caught this before merging but those emacs remaps on the Windows side should have been done a little differently. There are global remaps and then there are terminal remaps and while the linux side was modified by you correctly the windows side needed it to be excluded from when the terminal apps are active.

That change has now been made in this latest commit. https://github.com/rbreaves/kinto/commit/e7d66d36eedf3d7b1d20aa606ca70281fe88cf0a

**Comment by bryanhpchiang** [comment]
Good catch - thanks!
