### ISSUE TITLE
Keyboard profiles (Win laptop keyboard + Mac keyboard)

### ISSUE THREAD

**Issue by hagaram** [rbreaves/kinto#341]
Hi,
just to let you know this project rocks!, there were some hiccups to make it work on Arch --> I might try to create pull request to address issues I've encountered.

I've got laptop with generic built-in keyboard and also Mac keyboard which I used to use for Hackintosh. The thing is, that during configuration, we select second button to the left of spacebar. 

On Laptop it is 
```
KeyPress event, serial 40, synthetic NO, window 0x3800001,
    root 0x17e, subw 0x0, time 1363174, (744,76), root:(1615,560),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x3800001,
    root 0x17e, subw 0x0, time 1363329, (744,76), root:(1615,560),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

On Mac keyboard it is
```
KeyPress event, serial 41, synthetic NO, window 0x3800001,
    root 0x17e, subw 0x0, time 1543253, (-167,345), root:(704,829),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 41, synthetic NO, window 0x3800001,
    root 0x17e, subw 0x0, time 1543328, (-167,345), root:(704,829),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Rerunning the config isn't convenient.
Is there some "built-in" functionality at the moment, which would help distinguish between keyboards?

I've been thinking about udev rules which  would detect the keyboard and change configuration prior to running xkeysnail service on boot.

The same would go for unplugging, whicih would reset the configuration to one used for laptop and restart xkeysnail service.

**Comment by rbreaves** [comment]
Thank you for your feedback, and I believe what you are wanting has already been requested in this thread, so I am going to close this ticket. I don't have an eta for when I will be making the next update to address this specific issue, but changes will need to occur in the setup files. To get you by however you can edit the xkeysnail.service file with the names of your keyboard devices I believe via the --device parameter and simply run two instances of xkeysnail within the service itself.

vi /lib/systemd/system/xkeysnail.service

https://github.com/rbreaves/kinto/issues/335

Closing this ticket as I believe it to be a duplicate.
