### ISSUE TITLE
Cmd+option+i to open developer tools in Firefox

### ISSUE THREAD

**Issue by ukutaht** [rbreaves/kinto#347]
Sorry don't mean to bombard issues but I've just switched from Mac to Elementary OS and I'm trying to write down all shortcuts I'm trying to hit from memory and that don't work with Elementary + Kinto.

On Mac, I used to open developer tools with cmd+option+i which I think is the only way to do it. On elementary+kinto I have to hit cmd+shift+i to open them.

**Comment by rbreaves** [comment]
It's totally fine, I appreciate the feedback and I am actually feeling a little embarrassed that this one is not already part of Kinto as I use that combo pretty often myself.. although I also often just right click an element and click inspect too when I want to open the dev tools which might be why I never tested this specific combo.

Hit me with all of the missing combos you want, although I hope you won't find too many more of them lol as I want your experience with Kinto to be a good one and fairly complete already. And now that you mention it.. I guess I should create a new thread just for reporting missing shortcuts so things can start to be addressed in that manner. Might encourage more feedback as well if it is pinned.

**Comment by rbreaves** [comment]
Future requests can be made on #348 and I provided a quick template that users can use.

**Comment by ukutaht** [comment]
@rbreaves thanks for the update. With this change I can hit `Cmd+Control+i` to open devtools but the shortcut I remember from Mac is `Cmd+Option+i`

**Comment by rbreaves** [comment]
Oops lol 😅.. I wasn’t paying close enough attention it seems - will double check & fix later today..
