### ISSUE TITLE
Logitech MX Keys (Ubuntu/Linux)

### ISSUE THREAD

**Issue by lasersocks** [rbreaves/kinto#352]
I have the MX master keys keyboard and I can't get Kinto to work properly with it. No matter how I set it up with the Kinto configuration tool I can't get the keys to map like a mac. The laptop keyboard maps correctly and works as expected but I can't get the keys to map correctly with the external keyboard. 

I am using the MX Keys keyboard with the unified receiver. I can also see it through the Solaar app. All the keys function correctly, I just can't remap the alt/cmd opt/start and control keys to match a mac/my laptop keyboard. 

I've also tried switching between mac/pc mode with function+o and function+p but still can't get it right.

**Comment by rbreaves** [comment]
Please read this already opened thread on the issue. Manually editing the service file should enable functionality. I will need to test w/ an MX keyboard or accept a PR for the keyboard install properly.

https://github.com/rbreaves/kinto/issues/335

**Comment by lasersocks** [comment]
OK thank you.
