### ISSUE TITLE
on Azerty keyboard, pressing physical alt+a key closes application, instead of selecting all text

### ISSUE THREAD

**Issue by BrunoRoemers** [rbreaves/kinto#361]
**Describe the bug**
I use an Azerty keyboard (not sure about the exact variation) and noticed that [this line](https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py#L229) causes applications to quit when I hit the physical key combination `alt+a`.

I ran xkeysnail with an empty config file (`sudo systemctl stop xkeysnail && sudo xkeysnail --watch empty-file.py`) and when I hit the physical keys `alt+a`, it is logged as `LM-Q`, which triggers the rule mentioned above. I suspect that `LM` is mapped to `LC` somewhere along the way. Xkeysnail does not seem to distinguish between azerty and querty layouts, which is why `LM-Q` pops up in the logs, instead of the expected `LM-A`. (comparing azerty with querty keyboards, the `a` key and `q` key are interchanged.)

I commented out the mentioned mapping and restarted xkeysnail (`sudo systemctl restart xkeysnail`), after which the physical key combination `alt+a` selects all text, and `alt+q` still quits the active application.

My suggestion is to remove the respective mapping, but I'm not sure why it was added and hence what implications removing it would have.

**Expected behavior**
Pressing the physical key combination `alt+a` should select all text (i.e. `LC-A` should be sent to the application).
Pressing the physical key combination `alt+q` should still close the application (i.e. `M-F4` should be sent to the application).

**Install Type:** Bare Metal + Azerty keyboard
**Distro:** Ubuntu 20.04.1 LTS
**DE:** Gnome
**Branch:** master
**Commit:** 15adc5b

**Comment by rbreaves** [comment]
I hate directing you elsewhere but given that the config is sound this really needs to happen on the xkeysnail level & their key.py file.

https://github.com/mooz/xkeysnail

Closing ticket, if they get Azerty support the I’ll upstream it.

**Comment by redoxate** [comment]
Hello, Sorry to bump this issue, but I am still reproducing

**Comment by redoxate** [comment]
For people encountering this issue, commenting lines containing` K("RC-q") / K("RC-Q") `did the trick for me (Keyboard type: Mac on Ubuntu)
