### ISSUE TITLE
How to user Macbook keyboard Command keys (F3 & F4)

### ISSUE THREAD

**Issue by alechangbiao** [rbreaves/kinto#362]
I would like to use Macbook keyboard Command Key (F4) to bring out the ubunut dashboard and SCALE Key (F3) to show all the windows. 

How to do that though, I've searched around google and couldn't find a solution.

Please kindly help :)

**Comment by rbreaves** [comment]
I’d suggest you look at this PR. Different MacBooks have different media key layouts so no immediate plans to merge the media key remaps until I feel like it can be addressed across any Laptop model.

https://github.com/rbreaves/kinto/pull/326/files
