### ISSUE TITLE
Awesome! (and question about donations)

### ISSUE THREAD

**Issue by agoddard** [rbreaves/kinto#375]
This project is just such a breath of fresh air - thank you so much for your work on it. Also, I might be just doing it wrong, but when I try to follow any of the links for donating keyboards or cash to the project, I get stuck because i don't know how to ship the donation to you. It'd be ace if there was a more streamlined way (or maybe I just need more detailed instructions) on the best way to get this done.

Thanks again!

**Comment by rbreaves** [comment]
I'm glad to hear that you're getting a lot of utility out of it!

I'm honestly not entirely sure how the donations/wishlists work, but I believe if you purchase something on there then Amazon or the vendor will notify me and/or ship it out to me, as well as remove it from my list if it is an actual item or keyboard. Not sure about gift cards, if it does remove that then I might need to add a high quantity to that one.

I only mentioned shipping direct in my readme in case someone has an extra keyboard or something they'd like me to support. In that case they can hit me up on twitter. https://twitter.com/gbit86

**Comment by rbreaves** [comment]
Closing issue, it seems I needed to add my address to the wishlist/donations list 😅. Happens in private on my side but it did prevent donations till now I believe.
