### ISSUE TITLE
Can't install using readme.md 

### ISSUE THREAD

**Issue by vFondevilla** [rbreaves/kinto#378]
Hello there! Just a heads-up, it seems that the last readme.md update is not correct as it's referencing a non-existent bash script, so I cloned the repo and ran the python installer.

```
victor@blckhl-lnx:~/kinto$ curl -fsSL https://raw.githubusercontent.com/rbreaves/kinto/master/install.sh
curl: (22) The requested URL returned error: 404 
``` 

Greets!

**Comment by polyglotdev** [comment]
it appears to be missing the `install.sh` on `master`. I am trying to read through code to see if maybe he has replaced it with something else.

**Comment by rbreaves** [comment]
I sincerely apologize @vFondevilla @polyglotdev, why I shouldn't edit code late at night lol. That was intended to only go in a new branch - certainly not ready for master!!

That is where the install is headed - a single line, but currently you have to do a few steps. I have rolled back the changes, so please do this ```git reset --hard HEAD~2``` to remove the last 2 commits that should have NEVER been on the master branch. Thank you for letting me know this occurred, completely my mistake!!
