### ISSUE TITLE
Fix the Alt+Grave function in XFCE, MATE and Cinnamon

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#382]
In earlier versions of Kinto I had worked out how to manually change the `kinto.py` file to reactivate the expected behavior of Alt+Grave (the equivalent of Cmd+Grave in macOS) to switch between only the windows of a single application. 

For reasons I don't understand the default behavior of Kinto has always been to set up Alt+Grave to behave like Shift+Ctrl+Backslash, which just switches between open windows in reverse of Ctrl+Backslash. In my experience while using XFCE, MATE and Cinnamon (on Linux MInt) this is simply not the right way to use the physical Alt+Grave (mapped to Ctrl+Grave) shortcut. All of these DEs seem to have the appropriate [cycle between a single application's windows] function available. 

The manual edits I used to make to `kinto.py` would fix this, but of course the changes I made would get clobbered when updating and reinstalling Kinto. The ultimate solution to this is to integrate an option in the Kinto installer to treat Alt+Grave as separate from Shift+Ctrl+Grave. 

But for the moment I would appreciate some tips on what lines to edit in the current iteration of `kinto.py` to make this work properly.

**Comment by rbreaves** [comment]
I remember this being brought up previously & I don’t mind changing behaviors but the reason I though was because that combo is also a reverse cycle of all windows if you start tabbing normally & then switch via ~.

xkeysnail to fully support both needs modification. In the meantime it’s behavior could be exported to the tweaks menu on Linux.

**Comment by RedBearAK** [comment]
Oh, that's right, the behavior of the tilde key in macOS when you don't let go of the `Cmd` key after Cmd+Tabbing, which I never discovered in nearly two decades of using macOS (because I always let go of the `Cmd` key between shortcuts). I don't remember ever reading about that feature in any list of "Amazing hidden features you don't know about in macOS" that I ever saw. And I went through quite a lot of them. 

I can see why you would want to keep that the default if that's what you've been used to for many years, but my primary navigation technique was always just Cmd+Tabbing between a couple of different applications and then Cmd+Graving between open windows/documents when necessary. So every time I hit Alt+Grave and it just does a reverse Alt+Tab, it weirds me out. 

Oh, and the other thing is that while I saw the Kinto icon in the task bar on XFCE, once I installed MATE and Cinnamon and logged into those I have not seen it, and when I tried to launch Kinto.sh from the main application menu it just brought up that terminal window (`kinto-gui.py`). So I'm not sure how to fix that and get the icon back in the task bar so that I would have access to the tweaks menu. 

I'm going to jump back into XFCE and see if it will still show up in the task bar tray there. 

But back to the point, yes it would be fantastic to have an option to change the Alt+Grave behavior in the tweaks menu. I would also argue that since the standard way of reversing the function of many different keyboard shortcuts is applying the `Shift` key, most people will be much more familiar with just using Shift+Alt+Tab to reverse cycle windows. Like, if you want to "Find" in reverse you just do Shift+Cmd+G and so forth. But if there is at least an option to modify the Alt+Grave behavior, everybody can be happy. 

I wonder if we could set up a bounty somewhere for someone to take the time to fix this in xkeysnail. 

Thanks again for creating Kinto, it makes Linux and Windows so much more usable. I feel like I go from walking to jumping in a sports car every time I install it on a new OS.

**Comment by RedBearAK** [comment]
OK, so this goes right back to the whole "usability" thing I brought up regarding the new v1.2 installer a few months back. 

Because the window that the `Kinto.sh` "application" brings up looks like a terminal window, I expected the menus in that window to just be TERMINAL MENUS. In other words, I thought they were irrelevant so I **literally never looked at them**. 

It is only now that I realize the menus in that very confusing terminal-looking window actually apply to Kinto. 

There's two ways you can take this. You can either assume that I am some sort of idiot, or you can assume that you really need to read a book about designing software interfaces for actual humans who aren't also software developers. Since I am normally the person in the room explaining how software or hardware works to the other people in the room, I am not used to being this confused with a software interface. But that does not rule out the possibility of me being some sort of idiot. 

Anyway, I finally checked out those menus after logging into XFCE and finding that the Kinto icon also no longer appears in the tray, same as in MATE and Cinnamon. In the `File` menu I see the option `Tray enabled`. When I try to click on it with the mouse cursor, I can't activate it. If I highlight it with the arrow keys and then use the spacebar, it shows a check, but the Kinto icon still doesn't appear, and using the `Restart` option changes the box back to unchecked. 

So something appears to be interfering with the loading of the tray icon for me, on Linux Mint 20.1, in all of the DEs I'm using. 

But at least I know one way to get to the "tweaks" options you're referring to.

**Comment by rbreaves** [comment]
I wasn’t aware that you hadn’t noticed the Kinto terminal app was actually the alternative GUI.

Trust me when I say THAT was not an ideal solution or app design for Kinto & I don’t blame you for not liking it, I don’t like it either, but it serves a very utilitarian purpose. Some DEs do not support a system tray & in lieu of that I need to provide something & since I might not be able to predict all the ways Kinto can fail I felt it was best to allow users to interact w/ the service & see the output at the same time.

I also interpret it to some degree to indicate active or inactive & I color code it as well. I also did extensive testing of it w/ the system tray to make sure they didn’t trip each other up if you use both, that really did add some complexity, but was worth the effort.

Ideally Kinto would ONLY have a system tray - there’s no need for a full on app to exist but it exists because of DE’s that want to get rid of system trays because they think devs have abused them. Some have I’m sure but it’s a very dumb reason & it’s the reason the full on terminal GUI app to exist at all.

I don’t believe I need a lesson in good UI design, rather the devs that want to kill off system trays need that lesson.

Regardless I also built it w/ the terminal built in to lessen the number of trips or back & forth a user of Kinto will likely need when posting a ticket, if they see the output then they’re more likely to give me that output. As far as I can tell it works 100% the way that it should aside from a few early vte dependency issues that I had to work out on some distros.

Users very rarely ask me what commands to run to do X since it’s all built in now & they usually provide the initial output if something fails after the install. I consider v1.2 to largely be a success in terms of users & me getting straight to the point of an issue.

Only improvement I can make, related to errors, is adding opt in automatic reporting.

**Comment by RedBearAK** [comment]
I totally understand the need for some sort of GUI. The only reason it was confusing is because it just looks very much like a standard terminal window. Which had me thinking its only purpose was showing some troubleshooting info about the Kinto process. 

I did see that colored active/inactive at the bottom, that's nice. 

If instead of having the options hidden in menus they could all be presented within the window, with the terminal display of the Kinto process shown in a separate area down at the bottom of the window, that IMHO would be a much more user friendly way to present the GUI. In other words, make it look like the typical dialog you see when bringing up the "preferences" for pretty much anything in Linux or macOS. 

Like so: 

![Cinnamon_Window_preferences](https://user-images.githubusercontent.com/64876997/106404358-02288980-63df-11eb-9384-72634b27317f.png)

But with Kinto options. 

I'm sure you're very familiar with the typical Ubuntu style installer dialog. It has a way to unhide "Details" during the installation of the OS, but by default those details are hidden to make the UI cleaner. If something similar were done with the terminal part of the window full of text that would be ideal. 

If you want people to be able to easily submit a bug report then definitely some kind of automatic reporting or at least a button to copy the relevant text into the clipboard would probably be pretty helpful to a lot of users. 

I think you're still underestimating the number of people who just take one look at any kind of software with a "scary" or confusing UI and give up trying to figure anything out. Most of that type of user will never try to contact you or submit a bug report. 

Do you want me to file a separate bug report so we can work on figuring out why the tray indicator doesn't seem to want to run on my system? I'm absolutely certain I saw it once when I initially install Kinto on this new system.

**Comment by RedBearAK** [comment]
I tried to manually run the command that's attached to the startup item for the Kinto tray, and got `Permission denied`. 

Then I tried doing `chmod +x` on the `kintotray.py` file just because I noticed it wasn't green (executable). Suddenly it worked and the indicator shows up in the tray. 

At the moment I'm in Cinnamon. I'm going to try some logouts and switching DEs and see what happens.

**Comment by RedBearAK** [comment]
But when it did run there was all this nonsense displayed in the terminal. Just FYI. 

```
/home/kris/.config/kinto/kintotray.py:45: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  checkbox_autostart = Gtk.CheckMenuItem('Autostart')
/home/kris/.config/kinto/kintotray.py:46: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  restart = Gtk.MenuItem('Restart')
/home/kris/.config/kinto/kintotray.py:47: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  stop = Gtk.MenuItem('Stop')
/home/kris/.config/kinto/kintotray.py:48: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  keyboards = Gtk.MenuItem('Keyboard Types')
/home/kris/.config/kinto/kintotray.py:55: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edit = Gtk.MenuItem('Customize')
/home/kris/.config/kinto/kintotray.py:58: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  tweaks = Gtk.MenuItem('Tweaks')
/home/kris/.config/kinto/kintotray.py:59: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  rightmod =  Gtk.CheckButton('AltGr on Right Cmd')
/home/kris/.config/kinto/kintotray.py:60: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  vsc2st3 = Gtk.CheckButton('ST3 hotkeys for VS Code')
/home/kris/.config/kinto/kintotray.py:61: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  caps2esc = Gtk.CheckButton('Capslock is Escape when tapped, Cmd when held')
/home/kris/.config/kinto/kintotray.py:62: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  caps2cmd = Gtk.CheckButton('Capslock is Cmd')
/home/kris/.config/kinto/kintotray.py:63: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  button_config = Gtk.MenuItem('Kinto Config (shortcuts)')
/home/kris/.config/kinto/kintotray.py:64: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  service = Gtk.MenuItem('Kinto Service')
/home/kris/.config/kinto/kintotray.py:66: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  button_syskb = Gtk.MenuItem('System Shortcuts')
/home/kris/.config/kinto/kintotray.py:67: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  button_region = Gtk.MenuItem('Change Language')
/home/kris/.config/kinto/kintotray.py:68: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  systray = Gtk.CheckMenuItem('Tray Enabled')
/home/kris/.config/kinto/kintotray.py:69: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  helpm = Gtk.MenuItem('Help')
/home/kris/.config/kinto/kintotray.py:72: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  debug = Gtk.MenuItem('Debug')
/home/kris/.config/kinto/kintotray.py:73: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  opengui = Gtk.MenuItem('Open Kinto')
/home/kris/.config/kinto/kintotray.py:74: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  support = Gtk.MenuItem("Support")
/home/kris/.config/kinto/kintotray.py:75: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  about = Gtk.MenuItem('About')
/home/kris/.config/kinto/kintotray.py:186: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item_quit = Gtk.MenuItem('Close')
/home/kris/.config/kinto/kintotray.py:404: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.rightmod =  Gtk.CheckButton('AltGr on Right Cmd')
/home/kris/.config/kinto/kintotray.py:405: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.vsc2st3 = Gtk.CheckButton('ST3 hotkeys for VS Code')
/home/kris/.config/kinto/kintotray.py:406: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.caps2esc = Gtk.CheckButton('Capslock is Escape when tapped, Cmd when held')
/home/kris/.config/kinto/kintotray.py:407: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.caps2cmd = Gtk.CheckButton('Capslock is Cmd')
```

**Comment by RedBearAK** [comment]
Played around a bit between Cinnamon, MATE and XFCE and the Kinto tray icon now appears to be loading fine in all DEs and appears to be fully functional. I can stop/restart Kinto and disable the tray icon and then use the alternate GUI to re-enable it. It comes right back. It shows black when Kinto isn't running, and white when Kinto is active. Seems to be doing everything it's supposed to do. 

Literally the only thing I did was look in the `.config/kinto` folder and make `kintotray.py` executable with `chmod +x kintotray.py`. That's it. That's all I did, after getting the `Permission denied` when trying to run it manually. 

Linux Mint 20.1 (64-bit), still based on Ubuntu 20.04. 

Still experiencing the character-eating bug at the login screen after the first login after bootup.

**Comment by rbreaves** [comment]
Yea, I apologize about that, another user also reported exactly what you have recently so I have updated it. I think when I re-organized the files I must have done so under Windows instead of linux and that caused it to lose its permissions :/. That has been resolved now though.

https://github.com/rbreaves/kinto/issues/383

**Comment by rbreaves** [comment]
And thanks for highlighting the deprecation warnings, I will try and take a look at that later. It would be good to ensure that I resolve that before future updates of python3.

By reading this link I am guessing they want more verbosity to clearly express what is happening...

https://wiki.gnome.org/action/show/Projects/PyGObject/InitializerDeprecations?action=show&redirect=PyGObject%2FInitializerDeprecations

So I guess something like ```debug = Gtk.MenuItem('Debug')``` will turn into something like ```debug = Gtk.MenuItem.new_label('Debug')```. I am not sure though, I will have to go through it.

**Comment by RedBearAK** [comment]
@rbreaves 

Fixed the Alt+Grave behavior, I think by pretty much doing what I did before when `kinto.py` was arranged differently. Probably should have found the right line a long time ago, but I found the new file quite confusing to go through and just never got around to it until now. 

Here's the fix. Search for the "None" define group: 

```
define_keymap(None,{
```

Replace the commented line for xfce4, that maps the Grave function to "reverse cycle windows", with the line below it that just maps Ctrl+Grave to Ctrl+Grave: 

```
    # K("RC-Grave"): K("RC-Shift-backslash"),       # xfce4
    K("RC-Grave"): K("RC-Grave"),       # xfce4
```

This fix appears to work perfectly in Xfce, MATE and Cinnamon with no changes, as soon as the keyboard shortcut is set up correctly in the corresponding settings app for each DE. 

And here's a copy of my full working `kinto.py` as of version 1.2-6, for future reference. This has the working Alt+Grave (switch within single application) as well as the code blocks to make most of the common file browser apps behave like the Finder. (Renamed to "txt" because GitHub keeps complaining it doesn't support the "py" filetype. Pfft.)

[kinto.py.txt](https://github.com/rbreaves/kinto/files/6095162/kinto.py.txt)

**Comment by RedBearAK** [comment]
Resolved.
