### ISSUE TITLE
Same shortcut for both desktop environment and application.

### ISSUE THREAD

**Issue by susonthapa** [rbreaves/kinto#389]
First of all, thank you for such an awesome tool. In mac `cmd + w` closes the tab as well as closes the window. I was wandering if we can reproduce this behavior in linux. I am using KDE and I have mapped `ctrl + w` to close the window. I want to know if it's possible to somehow pass this key event to apps like firefox without the KDE intercepting it so that firefox can close the tab instead of KDE closing the firefox window.  And for other apps let KDE handle it.

**Comment by rbreaves** [comment]
I hadn’t really considered that, I’d have to do testing. I don’t know of any way to interact w/ an app though to know if all tabs are closed. I feel this is more of an implementation detail individual apps would have to be expected to have built in.

Mac apps obviously adhere more to UX standards set by Apple & given Windows & Linux rarely tries to enforce UX standards it might not be easy to implement such a thing. Xkeysnail would need to support more than just detecting the active Window app name but to actually know it’s status. That’d also become even harder to carry over in Wayland.

**Comment by rbreaves** [comment]
I misunderstood what you said there at first. My advice is to use Cmd-Q to close apps, or set a different catch-all hotkey for KDE that you can the manually modify ~/.config/kinto/kinto.py to remap to Cmd-W while not using Firefox & then when Firefox is running you don’t run remap cmd-w so the real cmd-w works like normal.

No interception needed if KDE is technical not set to Ctrl-w in the first place & cmd-w can still trigger whatever you set it to. Look at how normal GUI apps remap vs the terminal apps & you’ll probably get what I mean.
