### ISSUE TITLE
WM support?

### ISSUE THREAD

**Issue by bryanhpchiang** [rbreaves/kinto#394]
Love Kinto - have been using it for a few months, can't live without it. Only problem is that default window management on GNOME is terrible. Is there any way to make Kinto compatible with other WM extensions / solutions (ex. i3)?

First issue I ran into was starting Kinto manually without using the taskbar.

**Comment by bryanhpchiang** [comment]
Wondering if I can do this in a simpler way: avoid using a tiling WM, write some preset configurations with `wmctrl`, and then define keybindings with kinto to launch these scripts?

**Comment by rbreaves** [comment]
I keep meaning to try the various tiling window managers but I simply haven’t gotten around to it.. as long as they still use x11 & thus report the active window then I’m not sure why Kinto wouldn’t work w/ them.. although I have no idea if the system tray can work under i3 & similar no tiling managers have been tested by me thus far.

I will try & change this in the future though, I think i3 is certainly popular enough to test against at least.

**Comment by bryanhpchiang** [comment]
The main concern I see is that i3 bindings would overlap with common macOS bindings (polluted global shortcut space). For example, Super+W would try the layout in i3 but would close a browser tab otherwise. 

Is there some way to map key bindings to launch custom shell scripts in `kinto.py`?

**Comment by rbreaves** [comment]
Well yea, if i3 has a wm_class name. Should be about to use xprop -spy to get the wm_class name of i3 & the create a block of code in the same way sublime text or other apps have they keymaps defined.

Actual binary names though don’t matter so if it’s wmctrl.. get the wm_class name instead. Also if you do it the same way I do it for the terminals it won’t be case sensitive either.

**Comment by bryanhpchiang** [comment]
Thanks for the advice re: DEs; I ended up just installing a GNOME tiling extension that doesn't conflict with kinto - closing for now, if you have the chance to experiment with i3 in the future I can imagine that'd be useful for many.

**Comment by ivotron** [comment]
> Thanks for the advice re: DEs; I ended up just installing a GNOME tiling extension that doesn't conflict with kinto - closing for now, if you have the chance to experiment with i3 in the future I can imagine that'd be useful for many.

hi @bryanhpchiang , would it be possible to know the name of the extension you installed? thanks!
