### ISSUE TITLE
Apple Keyboard not detected

### ISSUE THREAD

**Issue by spamoom** [rbreaves/kinto#4]
I'm using the wireless magic keyboard (full size, british). Doesn't appear that the script correctly picks up the keyboard (hid_apple.conf doesn't even exist)

```
sam@sam-xps:~/bin$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SYNA2393:00 06CB:7A13 Touchpad          	id=11	[slave  pointer  (2)]
⎜   ↳ PS/2 Synaptics TouchPad                 	id=16	[slave  pointer  (2)]
⎜   ↳ Sam’s Mouse                           	id=18	[slave  pointer  (2)]
⎜   ↳ Logitech G203 Prodigy Gaming Mouse      	id=21	[slave  pointer  (2)]
⎜   ↳ Logitech G203 Prodigy Gaming Mouse Consumer Control	id=22	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=12	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=13	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=14	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=15	[slave  keyboard (3)]
    ↳ Sam’s Keyboard                        	id=17	[slave  keyboard (3)]
    ↳ Logitech G203 Prodigy Gaming Mouse System Control	id=19	[slave  keyboard (3)]
    ↳ Logitech G203 Prodigy Gaming Mouse Keyboard	id=20	[slave  keyboard (3)]
    ↳ Logitech G203 Prodigy Gaming Mouse Consumer Control	id=23	[slave  keyboard (3)]
```

You can see the keyboard (which was named on a mac) with id=17

Any suggestions to how to force this to be detected as a mac keyboard?

**Comment by rbreaves** [comment]
The id for Mac or Windows keyboards is actually irrelevant as long as the hid_apple driver loads.

That’s your actual issue as the keymaps Kinto uses are intended to be the same (for either Mac or Windows), but can only be the same if opt & cmd are flipped via the hid_apple driver.

I can provide you with a proper keyswap w/o a functioning hid_apple driver & which files to edit, in a few minutes, & it sounds like I may want to modify my installer to set this up automatically - if it’s common place for wireless apple keyboards to not use the hid_apple driver.

**Comment by rbreaves** [comment]
Ok to get you up and running quickly, assuming the install completed successfully, even though it did not grab the correct id.

You'll want to edit these 2 files, you can use vi, nano or your editor of choice.
~/.xkb/keymap/kbd.mac.gui
Find the line that looks like this
```
xkb_symbols   { include "pc+us+inet(evdev)+altwin(ctrl_alt_win)+mac_gui(mac_levelssym)" };
```
And change the "altwin(ctrl_alt_win)" to "ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)"

~/.xkb/keymap/kbd.mac.term
Find the line that looks like this
```
xkb_symbols   { include "pc+us+inet(evdev)+altwin(swap_alt_win)+mac_term(mac_levelssym)"        };
```
And change "altwin(swap_alt_win)" to "altwin:alt_super_win".

That should completely resolve your issue, I shouldn't have made the assumption that the hid_apple driver will always properly load, but I did and that is what led to this problem.

Going forward I will make an update to ask the user if they are using a Mac style keyboard (any keyboard with an actual Command key), if they are then I will check for the driver being loaded. It'd be better to set the keyboard correctly than to have a single keymap that works for both Windows and Mac Keyboards, assuming it is not possible to always load the hid_apple driver.

The following command will check if the hid_apple driver is loaded or not.

```
lsmod | grep hid_apple
```

https://stackoverflow.com/questions/9845877/how-to-determine-if-a-specific-module-is-loaded-in-linux-kernel

**Comment by rbreaves** [comment]
Updated my gist file to reflect this, since it is likely that others will run into this.

https://gist.github.com/rbreaves/f4cf8a991eaeea893999964f5e83eebb

**Comment by rbreaves** [comment]
Issue resolved in dev and master as described in work around. Installer has been updated to detect hid_apple driver and will change the keymap accordingly, if needed. Closing ticket.

**Comment by spamoom** [comment]
Awesome - thanks @rbreaves!
