### ISSUE TITLE
Setup fails on stock Ubuntu 20.04.x and 20.10.x (live boot only)

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#403]
Kinto setup is failing spectacularly in ways that I really did not expect on stock Ubuntu Desktop 20.04.2 LTS, in ways that other Ubuntu-based distros seem unaffected by. First problem is a bog-standard command like `sudo apt install python3-pip` fails with `Package not available`. Find a solution to that in some forum, apparently this is a known problem, fix it, then other things fail. 

None of this nonsense happens on Lubuntu 20.04.2, or Linux Mint 20.x, which is based Ubuntu 20.04. 

I have lost all patience with (stock) Ubuntu's bizarre behavior for the moment so this is just an FYI in case you want to run it in a VM sometime and modify the setup script to get past all the errors. I'm only running it from a bootable USB drive with the Live USB image on it, so it's possible this is only a problem when trying to install Kinto in the "Try Ubuntu" environment without doing a regular install first, but I can't imagine why it would be any different if I did a full install to a disk inside the machine. Using Lubuntu from the Live USB didn't give me any of these issues. 

Stock Ubuntu just doesn't make any sense. In fact it reminds me of all the stuff we had to go through to get Kinto running on MX Linux last year. 

On to testing KDE Neon with the new 5.21 update. Supposed to be real fancy-pants and pretty, finally. I guess we'll see.

**Comment by rbreaves** [comment]
Yea.. I think some distros have been changing the python3 package name on me lately. Hard to keep up w/, most users already have it so it’s not reported often.

May just need to find a more reliable way to install it tbh, or have it go through a list of possible names & hide errors unless they all fail.

**Comment by RedBearAK** [comment]
@rbreaves 

Yes, seems like that will be a necessary step to having a reliable install process. 

I wonder if it wouldn’t make more sense to come at this in reverse. By which I mean query each relevant type of package system for the package names that contain the specific support files and/or commands that are required for the install to succeed. Parse out every package name, then ask for the results to be installed. Maybe deduplicate the list if you think any package manager has a chance of stumbling over being asked to install the same package more than once. Seems unlikely but I wouldn’t take the chance. 

This would make the setup script highly adaptable to any number of package renaming or reorganizing shenanigans over time, because the package names returned would be dynamically generated. Just have to make sure you’re checking for each critical file that could conceivably by isolated into its own package. 

I’m assuming this would only be necessary for the main apt/yum/rpm and other package systems, and the packages installed via python/pip would generally be more stable as far as naming.

**Comment by RedBearAK** [comment]
@rbreaves 

In another sign that stock Ubuntu is madness, the KDE Neon install went off without a single problem. It prompted the download of 165MB worth of other packages, but there were no issues and the GUIs came right up. The mapping seems to be working fine, including Alt+H minimizing and even Alt+Grave "switch windows of a single application". Haven't stumbled on any shortcut that needs to be manually fixed yet. Before the remapping Alt+Space was activating a little drop-down that was probably what they call "krunner", but now it opens the main menu. So that's nice. 

One guess which distro and version KDE Neon has as its base. I didn't even realize until I installed it. I was assuming it was probably some RPM-based distro like Fedora. But no. Ubuntu 20.04. 

Oh, the tray indicator is not launching. Looks like the "AppIndicator3" problem. I forget whether this is a known issue for KDE and a "won't fix", but I assume so. But the GUI window of course works fine. 

This new version of KDE seems very clean and surprisingly performant. I may have to give it a full install and spend some real time in it to see what I end up stubbing my toes on.

**Comment by rbreaves** [comment]
I could certainly start to make suggestions of what available packages may fix a person's problem - of course I would never want to just install it. I would rather they do that in another tab or to then give them all possible suggestions for what remains and then end the installer and let them run those commands and then come back into the installer. I would want it to be very intentional by the user and not over automate that process.

**Comment by rbreaves** [comment]
> Oh, the tray indicator is not launching. Looks like the "AppIndicator3" problem. I forget whether this is a known issue for KDE and a "won't fix", but I assume so. But the GUI window of course works fine.
> 
> This new version of KDE seems very clean and surprisingly performant. I may have to give it a full install and spend some real time in it to see what I end up stubbing my toes on.

Yea.. it is one distro I wish I had the time to fix with a proper system tray tbh. It might not even need that much work, I just don't know that for sure and I don't dog food it like Ubuntu Budgie. I have no plans to install it on metal again either. It is possibly one of the best KDE based distros out there aside from FerenOS.

**Comment by RedBearAK** [comment]
> I could certainly start to make suggestions of what available packages may fix a person's problem - of course I would never want to just install it. I would rather they do that in another tab or to then give them all possible suggestions for what remains and then end the installer and let them run those commands and then come back into the installer. I would want it to be very intentional by the user and not over automate that process.

I have to say that I don't understand the reasoning behind what you're saying here at all. The Kinto setup just triggered the installation of something like 30 or 40 different packages on this fresh KDE Neon install without asking for any kind of input from me.  And I have no problem with that. Why wouldn't every user want Kinto to do what was necessary to get itself functioning? Every package installed in Linux pulls its requirements along with it. That's assumed. 

> My only gripe is that it is too customizable and one can easily get lost in the interface. Love the customizability still, but hate the way things are laid out and duplicated. If they could hide the complexity better it would be better.

It's my understanding from the videos I watched about the 5.21 update that one of the main accomplishments has been a de-stupiding of the settings apps, making things organized more intuitively. That and the really clean new theme was what prompted me to finally redownload the latest Neon image and try it out again. The regular User Edition already has the 5.21 update, and it looks quite good.

**Comment by RedBearAK** [comment]
@rbreaves 

I'm going to try and put this together in a PR for `setup.py`, but you probably shouldn't expect me to figure that out right away. 

Wanting to finally put this to bed, I spent several cycles in an Ubuntu 20.10 live environment to make sure that all of these packages are necessary. They are. 

```sudo apt install curl gcc git python3-dev python3-setuptools```

Yes, `gcc` is not installed, and will cause `setup.py` to fail. The python packages will each independently pull along `python3-distutils` as a dependency, but neither will install the other package, and both need to be installed. 

If there is no response to `which pip` (apt install python3-pip continues to fail with "no target"): 

This is the deprecated way to install `pip` after installing `python3-setuptools` (could stop working anytime, so do not recommend as a solution for `setup.py`): 

```sudo python3 -m easy_install install pip```

What is the recommended replacement for the deprecated `easy_install` method? "Use `pip` instead." LOL. Very helpful. 

So to install `pip` without relying on `easy_install` (hopefully this will work for the foreseeable future) this seems to be the recommended method: 

```curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py```

(This is why it was necessary to install `curl`.)

I'm sure you'll want to modify that to save `get-pip.py` in a temp file with a randomized name. 

Then finally, actually get `pip` installed: 

```sudo python3 /tmp/get-pip.py --upgrade```

Sudo is required to get pip installed system-wide instead of user's home. 

After this `setup.py` should successfully complete. 

So, all together now, this is what I have to do in a new boot of Ubuntu Desktop 20.10 to get through `setup.py`. Every piece of this appears to be absolutely necessary, in this order, for success: 

```
sudo apt update
sudo apt install curl gcc git python3-dev python3-setuptools
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
sudo python3 /tmp/get-pip.py --upgrade

cd ~/Downloads
git clone https://github.com/rbreaves/kinto
cd kinto
./setup.py
```

Also you need to add the "universe" repo in order to get the `gnome-tweaks` package recommended at the end of the install. I think universe also contains the actual `python3-pip` package, but I figured you didn't want to have to try to add a new repo just to get Kinto installed.

**Comment by RedBearAK** [comment]
@rbreaves 

I think I found the relevant section in `xkeysnail_service.sh`: 

```
if ! [ -x "$(command -v pip3)" ]; then
	echo "Will need to install python3-pip..."
	sudo ./linux/system-config/unipkg.sh python3-pip
fi
```

This is going to need to check for the availability of the `python3-pip` package and then fall back to the more universal `get-pip.py` method if necessary. I'll try to get that working. 

And then just below that: 

```
if ! [ -x "$(command -v python3-config)" ]; then
	if [ "$distro" == "ubuntu" ] || [ "$distro" == "debian" ] || [ "$distro" == 'linuxmint' ]; then
		pydev="python3-dev"
	elif [ "$distro" == "fedora" ]; then
		pydev="python3-devel"
	fi
	if [ "$distro" == "gnome" ] || [ "$distro" == "fedora" ] || [ "$distro" == "debian" ] || [ "$distro" == 'linuxmint' ]; then
		echo "Will need to install $pydev..."
		sudo ./linux/system-config/unipkg.sh "$pydev"
	fi
fi
```

I don't know about "debian" in general but it seems fine for Mint to extend this from just installing `python3-dev` to installing `python3-dev python3-setuptools`. 

But before that and the `pip` section, Ubuntu needs to be prompted to install `curl gcc git`. I'm including `git` for the case where the user just downloads the ZIP from GitHub rather than doing a `git clone`. Not sure if it's really necessary though. 

I'll try to find a way to do this as concisely as possible.

**Comment by RedBearAK** [comment]
@rbreaves 

No doubt there is something horribly wrong that I missed or a cleaner way to do part of it, but here is my PR for fixing Kinto install on Ubuntu 20.04.x and 20.10.x. It allowed me to complete the setup on a fresh full install of Ubuntu 20.10 without doing anything manually:

https://github.com/rbreaves/kinto/pull/429

I saw that there was an attempt to invoke `pip3` much higher in the `xkeysnail_service.sh` file, so I moved the `if` statement for installing `pip` to just before that. Line 212 of the current file. 

Down below that where things like "python3-dev" get installed, I first set up a block that installs `gcc` on Ubuntu, then separated Ubuntu from Debian an Linux Mint so that it installs both `python3-dev` and `python3-setuptools` only on Ubuntu. I note in the PR that it is possible that Mint and other Ubuntu-based distros may need to be moved to the new Ubuntu `if` section in the near future as they follow along with Ubuntu's packaging changes. In other words, they may also soon need the addition of `python3-setuptools` to complete setup. 

I did not try to set up a test to check whether `python3-pip` is an available package for other distros. I concentrated on just forcing Ubuntu to use the universal `get-pip.py` installation option from `pypa.io`. 

I tried to save the `get-pip.py` file into `/tmp` and install from there, but that kept failing for reasons I don't understand, so I just went with a local in-folder file which then gets removed after installing `pip`. 

Pretty sure this is my best effort for now.

**Comment by RedBearAK** [comment]
@rbreaves 

Tested this on a fresh live ISO boot by just downloading the ZIP of my PR branch, because I couldn't figure out how to `git clone` just that particular branch rather than the main fork. Setup failed, but only due to not having git installed, which for some reason is required to get all the way through. Once I installed git, setup completed. Nothing else was manually installed. 

So for the cases that someone installs by downloading the ZIP file from the GitHub page rather than following the instructions to use `git`, I advise adding another line to install `git`. A lot of software on GitHub is downloaded that way, so it's probably not going to be too unusual to have someone do that. There are some unfortunate "fatal" errors right at the beginning of setup if you're not installing from a git clone. Those should be cleaned up sometime. 

The second live boot test I had a failure due to a flakey download of `pip` via the `get-pip.py`. But re-running setup worked the second time. Seemed like the `get-pip.py` file only downloaded partially the first time for some reason. Maybe bad wifi or something. Might want to look at a condition that kicks out or retries the download if it fails with an error.

**Comment by RedBearAK** [comment]
Tried it again this morning and had another failure on the install of `pip` with the `get-pip.py` script. Incomplete download again, resulting in a traceback error. Not sure what could be causing that. 

Going to try and make the removal of the downloaded file conditional on successful termination of the pip install process, just using the terminal "&&" technique. Don't know if that will help or if I'll need to figure out a more involved python error handling technique to retry the download/install a couple of times if it doesn't complete. 

```sudo python3 get-pip.py --upgrade && rm get-pip.py```

**Comment by RedBearAK** [comment]
Will also be testing with a daily ISO image of 21.04 instead of waiting for release. Might as well. 

I'll edit this with an update.

**Comment by RedBearAK** [comment]
Failed test on Enso, which is identifying as Ubuntu. Discovered that Ubuntu would set the `$pydev` variable but was never included in the line that actually triggers the install of `python3-dev`. Updated PR.

**Comment by RedBearAK** [comment]
Success, finally. 

Tested in a clean Enso 0.4 live boot: Setup completes with no hitches. 

Tested in a clean Ubuntu 20.04 live boot: Setup completes with no hitches. 

Tested in a clean Ubuntu 21.04 dev live boot: Setup completes with no hitches. 

Testing by downloading the ZIP file from https://github.com/RedBearAK/kinto/tree/patch-5 which should contain the latest version of the code from PR #429. So when I run the test there has been nothing installed yet, including `git`.

**Comment by RedBearAK** [comment]
@rbreaves 

When you have a moment sometime. No hurry. 

QUESTION: Something was scratching at my brain since last night, since I saw this line that was keeping Ubuntu from installing `python3-dev` properly: 

```
if [ "$distro" == "gnome" ] || [ "$distro" == "fedora" ] || [ "$distro" == "debian" ] || [ "$distro" == 'linuxmint' ]; then
```

And changed it to this: 

```
if [ "$distro" == "ubuntu" ] || [ "$distro" == "gnome" ] || [ "$distro" == "fedora" ] || [ "$distro" == "debian" ] || [ "$distro" == 'linuxmint' ]; then
```

I think this might have been a typo but I need your confirmation. The `if` statement to install `python3-dev` has "gnome" in it, but is comparing it to `$distro` rather than `$dename`. It's always `$dename` everywhere else. 

Is there a distro out there that actually self-identifies as "gnome"? I was going to guess Fedora since I've seen someone describe it as the "purest GNOME desktop experience you can get", but you've also got "fedora" as a test condition, so that wouldn't make too much sense. 

Or was that A) actually meant to originally say "ubuntu" instead of "gnome" with no "gnome" on that line at all, or was it B) meant to be there but supposed to use `$dename` when comparing to "gnome"?

**Comment by RedBearAK** [comment]
Tried to test Fedora 33 but the default in the live boot is Wayland. Can't find a way to change it to Xorg without a full install. 

Can't find a way to install over a dual-boot macOS/Ubuntu drive without erasing the disk. The custom partitioning screen is being very obtuse, even for a Linux installer. 

So, can't test setup on Fedora for the moment.

**Comment by RedBearAK** [comment]
We is very bad at if-then-else logics, yes we are, precious! 

![happy_wait_gollum](https://user-images.githubusercontent.com/64876997/111829279-527d7d00-88a1-11eb-97cf-804ba78540e8.gif)

Should have immediately found a distro for testing that didn't identify as "Ubuntu". Didn't properly structure the if-then-else for installing `pip`. So KDE Neon failed to install `pip` right at the beginning. 

Also, looks like KDE Neon needs git installed, so adding it to the Ubuntu test to install `gcc` and `git`. That let it finish. 

Putting the fixes in the PR now.

**Comment by RedBearAK** [comment]
Setup appears to work fine in elementary OS live boot. 

Epiphany browser is unresponsive to two shortcuts: Ctrl+Q and Ctrl+N. Can't see a way around Ctrl+N, but Ctrl+Q can be made to work by mapping to Alt+F4 (M-F4) specifically for Ephiphany. 

This is strange behavior because it seems limited to Epiphany and both shortcuts are supposed to be active in its default shortcuts scheme. Also the keyboard shortcuts dialog for Epiphany refused to close with either Ctrl+W or Ctrl+Q until I remapped Ctrl+Q. 

But the Kinto install via this branch worked without any problems.

**Comment by RedBearAK** [comment]
Testing installer branch on Mint 20.1 MATE edition is successful. 

Except the keyboard shortcut to minimize/hide windows needs to be manually changed to "Mod4+H" using the Cmd+H or Alt+H keys before it will actually work. 

This default setup for MATE will of course not work properly if the user happens to log out and try to use either Cinnamon or Xfce desktops.

**Comment by RedBearAK** [comment]
Testing installer branch on Xubuntu 20.10 live boot: Passed. 

Have to fix Alt+Tab in Window Manager afterward, but that's normal.

**Comment by RedBearAK** [comment]
Testing installer branch on Pop OS 20.10 live boot: Passed.

**Comment by RedBearAK** [comment]
Testing installer branch on Manjaro 20.2 (Cinnamon): Passed. 

Had to remember to right-click on the Cinnamon menu icon and "configure" to get to the special keyboard shortcut. Both "Super_L" and "Super_R" were bound on this one, blocking the setup dialog from finishing.

**Comment by RedBearAK** [comment]
@rbreaves 

Installer fixes that I'm actively testing are now combined with Finder mods and `unipkg.sh` updates in PR #437. Closing the older PRs.

**Comment by RedBearAK** [comment]
Testing installer branch on Ubuntu Unity 20.10: Passed.

**Comment by RedBearAK** [comment]
Testing installer branch on Kubuntu 20.10: Passed.

**Comment by RedBearAK** [comment]
Testing installer branch on openSUSE Tumbleweed: Passed, with caveats (see below). 

openSUSE Tumbleweed needs a specific package installed, different from Lubuntu but similar, the `vte` library. Support for this is already added to my installer branch. 

``` 	sudo ./linux/system-config/unipkg.sh typelib-1_0-Vte-2.91```

Tumbleweed also needs `export DISPLAY=:0 && ` added to the `ExecStart` command to avoid `cannot connect to display ""` error and constant fail-retry loop on the `xkeysnail` service. 

Doesn't work: 
```
ExecStart=/usr/bin/sudo /bin/bash -c '/usr/bin/xhost +SI:localuser:root && /home/kris/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kris/.config/kinto/kinto.py'

```

Does work: 
```
ExecStart=/usr/bin/sudo /bin/bash -c 'export DISPLAY=:0 && /usr/bin/xhost +SI:localuser:root && /home/kris/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kris/.config/kinto/kinto.py'
```

**Comment by RedBearAK** [comment]
Testing installer branch on Fedora 34 Beta: Works, but...

Setup goes fine and the GUI appears, but the `xkeysnail` service gets stuck in a fail-retry loop with a "permission denied" error related to `/usr/bin/sudo`. Also, for some reason `systemctl` refuses to see the service file when it's in `/usr/lib/systemd/system`, giving a "unit not found" error. It gets detected after being copied to `/etc/systemd/system`, but still won't initiate properly. 

The only way to start the `xkeysnail` service at the moment is to copy-paste and run the contents of the `ExecStart` command manually in a terminal. That produces no "permission denied" error and keyboard mapping starts working. 

Weird. Starting a new issue thread for this.

**Comment by RedBearAK** [comment]
Put in some work to get the installer working on Manjaro 21 KDE (Minimal).

**Comment by rbreaves** [comment]
I’ll try & review your PRs & threads tomorrow. Sorry I’ve kinda been ignoring your progress - I just haven’t been wanting to get to deep into any rabbit holes while I’ve been busy w/ other things.

**Comment by RedBearAK** [comment]
@rbreaves 

No worries. I just hope at least some of it is actually usable. Had time to fix a lot of mistakes along the way already. Try not to scream too loud when you take a look.

**Comment by RedBearAK** [comment]
Current installer iteration in PR #437 is working on openSUSE Tumbleweed, including fixing the service file so that it will work immediately after install. See issue #436 for full info on the problems resolved. And issue #444 for the one remaining minor glitch I can't get past yet.

**Comment by RedBearAK** [comment]
Added a new logic at the beginning of the installer script to try and make sure the user is actually in an X11/Xorg environment. It can be bypassed by the user if they choose to do so, but requires input (y/n) and puts up some warnings about Kinto/xkeysnail not working in non-X11 environments if "x11" was not detected.

**Comment by yaomtc** [comment]
Ah, I found the option - I mistook the Kinto.sh app for just a terminal. Thanks.
