### ISSUE TITLE
[REQUEST] Add Ctrl+Win+f = F11 (Toggle fullscreen) to "None" keymap?

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#413]
I've noticed there are different keyboard shortcuts in Linux apps for going "fullscreen". But a common one seems to be F11. This is one of those shortcuts that is too random for me to find it intuitive or memorable, so I'd like to ask that a Ctrl+Win+F mapping be added to the top of the "None" define_keymap group. 

```
define_keymap(None,{
    K("RC-Win-f"): K("F11"),                   # KKF - Toggle fullscreen
    K("RC-Space"): K("Alt-F1"),                   # Default SL - Launch Application Menu (gnome/kde)
    K("RC-F3"):K("Super-d"),                      # Default SL - Show Desktop (gnome/kde,eos)
    K("RC-LC-f"):K("M-F10"),                      # Default SL - Maximize app (gnome/kde)
    # K("Super-Right"):K("C-M-Right"),              # Default SL - Change workspace (budgie)
    # K("Super-Left"):K("C-M-Left"),                # Default SL - Change workspace (budgie)
```

I'm open to discussion of anything this might interfere with. 

The equivalent on macOS seems to be Ctrl+Cmd+F, which from the key positions would be physical Alt+Ctrl+F (logical Ctrl+Super/Win+F under Kinto). 

Thoughts?

**Comment by rbreaves** [comment]
You keep referencing an older version of Kinto - the none reference was replaced, it looks like this now, so RDP and VM software can be better supported. Also this does highlight a mistake - I already tried adding support for this, but clearly I mixed up Super with LC (Win as a modifier name does not exist, so you meant Super in your above example).

```
# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Space"): K("Alt-F1"),                   # Default SL - Launch Application Menu (gnome/kde)
    K("RC-F3"):K("Super-d"),                      # Default SL - Show Desktop (gnome/kde,eos)
    K("RC-LC-f"):K("M-F10"),                      # Default SL - Maximize app (gnome/kde)
    # K("Super-Right"):K("C-M-Right"),              # Default SL - Change workspace (budgie)
...
```

**Comment by RedBearAK** [comment]
I should have known. 

Well, I will have to go back in again with a new file and try to figure out what to splice back in from my working backup.

**Comment by RedBearAK** [comment]
@rbreaves 

(Read to the bottom before trying to answer any part of this. It's weird. Very weird.) 

OK, so I commented out my shortcut and tried that other line, with LC modified to Super: 

```
    K("RC-Super-f"):K("M-F10"),                      # Default SL - Maximize app (gnome/kde)
```

This shortcut worked **exactly once**, to maximize a terminal window, then stopped working everywhere. Even if I restart Kinto, the shortcut will not work again. 

I can do (logical) Alt+F10 (physical) Win+Fn+F10 all day long and it toggles the maximize state. 

I tried unmapping the "Volume down (Quiet)" shortcut from "Alt+Audio lower volume", thinking maybe there was a similar conflict to the F9/Mute key. Since this is Cinnamon it didn't work, just like the ongoing conflict I still have with Alt+F9 in Cinnamon. 

Guessing that it would work in MATE though, just like I was able to get rid of the conflict with Alt+Mute there. But no luck in Cinnamon. 

Anyway, we're sort of talking about two different things here. F11 is for toggling the "fullscreen" mode that takes over the whole screen and blocks docks and menus and notifications from appearing. I don't actually care for the true fullscreen mode that much, but I was trying to make things match up with the corresponding shortcut in macOS. 

I've tried all variations of setting the "toggle maximization state" to either "Alt+F10" or "Alt+Audio lower volume" and using the corresponding "M-Volumedown" in `kinto.py`, but nothing makes it work again beyond that very first time. 

This is very analogous to the problem I was having with "Alt+F9". When I try to set the shortcut with physical Alt+Ctrl+F it just results in "Ctrl-Super L" showing in the Cinnamon keyboard app. 

But I don't understand why it still won't work when I make it correctly say "Alt+F10" by pressing Win+Fn+F10. Theoretically, that should work. 

So, I don't know if Cinnamon is different, but it has no shortcut set for just "maximize window", and this "Alt+F10" is set on "toggle maximization state". Maybe that's because they also have an "unmaximize window" shortcut option? That seems to be mapped to "Alt+F5" by default. Kind of a strange setup. Seems redundant. 

Hey, so you know you said there is no "Win" shortcut? That was actually working fine for me with the "fullscreen" toggle, so I tried to switch "Super" with "Win" and now I can use (physical) Alt+Ctrl+F (logical) Ctrl+Win+F over and over again. It's not only working as "Win", it doesn't appear to be conflicting with anything in Cinnamon. 

Oh, except it doesn't work in a terminal window. That very first and only time that Ctrl+Super+F worked for me was in a terminal window. But neither that or the new one works in a terminal window. 

Boy, keyboard remapping really is an adventure sometimes. In that I get hopelessly lost a LOT. 

You know what's funny? I only tried to implement the Ctrl+Super+F shortcut to have a more intuitive option for making my terminal fullscreen. And now I can't even get "toggle maximization state" to work in terminals. Ironic. 

I tried mapping to just "F8" by itself, but then when I press (physical) Alt+Ctrl+F the shortcut app registers it as just "Super-Control R". 

So: 

- Works, but only when using "Win" instead of "Super"
- Can't set shortcut by pressing the actual keys being mapped
- Doesn't work in any terminal window

? 

Jumping Jupiter, now suddenly it's working in my terminal windows and I HAVE NO IDEA WHY. 

Oh, hey, random thought. Maybe the process that was conflicting after that very first time somehow eventually "let go" of the shortcut or crashed, so it suddenly started working in terminals again. Just throwing that wild guess out there. 

And I guess that conflict just doesn't happen for some reason if I use "Win" instead of "Super". 

????

**Comment by RedBearAK** [comment]
Now it's misbehaving again. Works in terminal windows, works on the Kinto.sh GUI window, stopped working on the Keyboard settings window and VSCodium window. Doesn't work on Chromium window. 

But the usual Win+Fn+F10 (Alt+F10) always works, everywhere. 

I literally have done nothing to my Kinto settings for like an hour or more. I've been doing other things. Something is just making the Kinto mapping behave very inconsistently across different applications. 

Still in Cinnamon, on Mint.

**Comment by RedBearAK** [comment]
@rbreaves 

OK, I finally took some time to re-do the setup under Cinnamon and went through the process of figuring out exactly what has to be fixed to make everything work again with the latest version of `kinto.py`. Diffed the old and new files and stripped out everything that was unrelated. 

Good news is that what makes Kinto seem immediately and horribly "broken" in Cinnamon is pretty much just that the Alt+Tab and Alt+Grave shortcuts flat out don't work after a new install, and they can't be mapped correctly in the keyboard shortcut app. It's one of those "only registers as Control R" problems. It seems much worse than it is because I'm constantly trying to Alt+Tab without even thinking about it. Meanwhile all other shortcuts I commonly use seem to work fine. 

The other good news is that it is (relatively) easy to fix, and still just comes down to toggling the "non-xfce4" lines off and the "xfce4" lines on. Except for the Alt+Grave lines. 

If you ever get rid of those descriptive labels, I will be pretty effectively screwed when trying to search for the right lines to change. 

`diff kinto.py kinto.py.new-notworking`

```
259,263c259,263
<     K("M-Tab"): pass_through_key,                 # Default not-xfce4 - Cmd Tab - App Switching Default
<     K("RC-Tab"): K("M-Tab"),                      # Default not-xfce4 - Cmd Tab - App Switching Default
<     K("RC-Shift-Tab"): K("M-Shift-Tab"),          # Default not-xfce4 - Cmd Tab - App Switching Default
<     K("RC-Grave"): K("M-Grave"),                  # Default not-xfce4 - Cmd ` - Same App Switching
<     K("RC-Shift-Grave"): K("M-Shift-Grave"),      # Default not-xfce4 - Cmd ` - Same App Switching
---
>     # K("M-Tab"): pass_through_key,                 # Default not-xfce4 - Cmd Tab - App Switching Default
>     # K("RC-Tab"): K("M-Tab"),                      # Default not-xfce4 - Cmd Tab - App Switching Default
>     # K("RC-Shift-Tab"): K("M-Shift-Tab"),          # Default not-xfce4 - Cmd Tab - App Switching Default
>     # K("RC-Grave"): K("M-Grave"),                  # Default not-xfce4 - Cmd ` - Same App Switching
>     # K("RC-Shift-Grave"): K("M-Shift-Grave"),      # Default not-xfce4 - Cmd ` - Same App Switching
277c277
<     # K("RC-H"):K("M-F9"),                          # SL - Minimize app xfce4
---
>     K("RC-H"):K("M-F9"),                          # SL - Minimize app xfce4
280,281c280,281
<     # K("RC-Tab"): K("RC-backslash"),               # xfce4
<     # K("RC-Shift-Tab"): K("RC-Shift-backslash"),   # xfce4
---
>     K("RC-Tab"): K("RC-backslash"),               # xfce4
>     K("RC-Shift-Tab"): K("RC-Shift-backslash"),   # xfce4
282a283
>     K("RC-Grave"): K("RC-Grave"),       # xfce4
494,495c495,496
<     # K("RC-Tab"): K("RC-backslash"),               # xfce4
<     # K("RC-Shift-Tab"): K("RC-Shift-backslash"),   # xfce4
---
>     K("RC-Tab"): K("RC-backslash"),               # xfce4
>     K("RC-Shift-Tab"): K("RC-Shift-backslash"),   # xfce4
496a498
>     K("RC-Grave"): K("RC-Grave"),       # xfce4
```

What always makes this confusing for me is that these lines are spread out in different areas of the file. There's no "xfce4" toggle that can just be flipped off or on. That would be... handy. 

But once I do the above swaps and then add the new line: 

```K("RC-Grave"): K("RC-Grave"),       # xfce4```

While leaving this line commented out: 

```# K("RC-Grave"): K("RC-Shift-backslash"),       # xfce4```

Then everything is good. All is right with the world. 

This is ignoring the addition of my code blocks to make file managers act like the Finder. Which I am finding myself already surprisingly dependent on. I guess I got way too acclimated to the Finder's behavior over the last couple of decades. It's now super frustrating whenever the Finder-mod mappings aren't active. Having to fall back to the mouse to do common file tasks almost makes my skin crawl. 

I find myself very curious about this line that also maps Ctrl+H, and why it doesn't seem to cause any conflict with the "minimize window" shortcut further down that goes to Alt+F9. I think I've tried commenting it out in the past while troubleshooting the Ctrl+H problem, but that didn't seem to help in any way. I'm just leaving it alone for now and it doesn't seem to be an issue. 

```    K("RC-H"):K("Super-h"),                       # Default SL - Minimize app (gnome/budgie/popos/fedora)```

Attached here is a copy of my new `kinto.py` with no Finder mods: 

[kinto.py - No Finder mods.zip](https://github.com/rbreaves/kinto/files/6107676/kinto.py.-.No.Finder.mods.zip)

And one complete version with the Finder mods. Which I will now be using. 

[kinto.py - With Finder mods.zip](https://github.com/rbreaves/kinto/files/6107677/kinto.py.-.With.Finder.mods.zip)

Hallelujah, I am now fully on v1.2-6, with the VM and remote fixes. (This means you'll release a new version tomorrow. LOL.)
