### ISSUE TITLE
[REQUEST] Rearrange the Kinto.sh GUI menu to match tray icon menu

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#415]
I've been restarting Kinto quite a lot while testing my `kinto.py` mofidifications. I found it a bit fiddly having Restart in the middle of the menu, so I tweaked the GUI menu to make it more closely match the tray icon menu, with Restart and Stop at the top. 

If you don't mind I'd like to ask you to make this a permanent change so it will stay that way the next time I upgrade or install Kinto on a new distro. 

![Kinto_GUI_menu](https://user-images.githubusercontent.com/64876997/110227980-d4d16e80-7ea9-11eb-8112-3dff356b1c30.png)

![Kinto_GUI_menu_modded](https://user-images.githubusercontent.com/64876997/110228532-50cdb580-7eae-11eb-9b19-25d477ddb74b.png)

Created pull request #414 to go along with this.

**Comment by rbreaves** [comment]
The PR has been accepted, close this issue. Thanks.
