### ISSUE TITLE
SVG icon is fuzzy in Alt+Tab switcher

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#416]
Best to use screenshots, I think: 

![kinto_icon_fuzzy_Alt-Tab](https://user-images.githubusercontent.com/64876997/110279859-4979db00-7f86-11eb-9219-1015193ed775.png)

The Kinto.sh "application" icon is extremely fuzzy in the Alt+Tab switcher (Cinnamon) as if it's a raster image being "enlarged" from a 16x16 tray indicator size icon. Which is odd because it's an SVG file, and it's "huge" and very clear when I look at it in Inkscape. 

![kinto_icon_Inkscape](https://user-images.githubusercontent.com/64876997/110280905-1e908680-7f88-11eb-94a1-fbed830ab81f.png)

On the Plank dock, however, it is shown at a good size (64x64 pixels) and very clear. Enlarged to 96x96 and noticed that the only icon fuzzy on Plank is Chromium. But only the round one on the right. Hmm. Interesting. But the Kinto.sh icon looks fabulous at any size. 

![kinto_icon_Plank](https://user-images.githubusercontent.com/64876997/110279866-4b439e80-7f86-11eb-9d99-4899b1e59190.png)

Ulauncher shows the Kinto.sh icon looking nice and sharp. 

![kinto_icon_Ulauncher](https://user-images.githubusercontent.com/64876997/110280455-4df2c380-7f87-11eb-81fd-77ced1516f1a.png)

But Albert launcher shows it as the fuzzy "enlarged" version instead. (Albert shows the Chromium icon as sharp, but it's showing the "squarish" version that you see on the dock to the left of the round one. I have no idea where that comes from.) 

![kinto_icon_Albert](https://user-images.githubusercontent.com/64876997/110280489-5e0aa300-7f87-11eb-877f-b5c2f25f7110.png)

Nemo-preview shows the original image at the indicator tray size. Which is odd since you would think an SVG would be previewed at a nice big and clear size. What with it being a vector image with no real "size". 

![kinto_icon_Nemo-preview](https://user-images.githubusercontent.com/64876997/110280507-6531b100-7f87-11eb-8ad3-1ea3b77c7b03.png)

I don't know how to fix this, I'm just letting you know something odd is happening. If there is some sort of embedded "preferred size" in the SVG that's making it be rendered as a 16x16 size under some circumstances, you might need to make a separate SVG file for the main application icon.

**Comment by rbreaves** [comment]
More symlinks or files likely need to be created to have complete coverage of sharp iconography. Not a priority for me atm, but if anyone finds the resource locations that it needs to be linked to then I will look into including it. If changes or additional files need to be created then I am fine with that too.

I am not aware of the default dimensions of the svg being a limitation, it's a vector but despite that I do not know how the various applications may or may not interact with it.

**Comment by RedBearAK** [comment]
Well, good luck fixing it. I just spent a few hours trying various things to get the icon to behave in a rational manner. I failed pretty hard. 

There is an attribute "viewBox" that seems to have a strong effect on how the SVG image is scaled, at least on Plank. But I gave up on that and tried to just export a 512x512 PNG with Inkscape. 

Turns out the icons for other applications sit on a 512x512 transparent background but the visible image is more like 440x440. Except to make the Kinto icon look the same size as the others when it's on the dock, I had to scale it to 460x460. 

But even after modifying the .desktop file in `/usr/share/applications` to point to the new PNG file, it only looks sharp in the Alt+Tab switcher **when launched via the Cinnamon menu**. When using Albert or Ulauncher, it's still fuzzy. Same as the screenshot above. 

I know they all see the same modified .desktop file because I can delete it from `/usr/share/applications` and it will disappear from all the launchers. 

No part of this makes any sense. As usual. 

Oh, wait, I think something else actually got better (Albert): 

![kinto_icon_sharp_Albert](https://user-images.githubusercontent.com/64876997/110894556-8b679180-82a4-11eb-9840-5403170e99df.png)

So I guess it's just still fuzzy in the Alt+Tab switcher, mainly. 

Also I added: 

```Comment=Make Linux Type Like a Mac!```

to the .desktop file, and that worked. As you can see in the Albert screenshot. I think it might be better to put something like, "Enable Mac-Style Keyboard Shortcuts" as the official description.

**Comment by RedBearAK** [comment]
Resolved.
