### ISSUE TITLE
macbook pro 2007(portuguese pt)

### ISSUE THREAD

**Issue by JoaquimFMF** [rbreaves/kinto#417]
I am using my macbook pro 2007(portuguese pt) with linuxmint and i have installed kinto. However, I can't write / access some characters: @, € ... on mac os, for example, i had to press "alt + 2" to get @

What should I do? 
![mac_keyboard](https://user-images.githubusercontent.com/22475866/110475699-21e75780-80d9-11eb-85fc-cdd26391dd88.jpg)

**Comment by rbreaves** [comment]
Closing, as this is better suited for xkeysnail and can then be upstreamed into my fork of it and thus Kinto. As mentioned local changes can be made as well to add support - if the user wants to do that and share the PR directly with the xkeysnail or just post those results then I will happily make the PR request on their behalf, although I like to be able to test things out personally.
