### ISSUE TITLE
[QUESTION] Purpose of Ctrl+Dot mapping to Ctrl+Shift+Dot? 

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#425]
I was wanting to see if I could map Cmd+Dot to Ctrl+C in terminals, but there is already a mapping there for "RC-Dot" to "C-Shift-Dot". 

```
    K("RC-COMMA"): K("C-Shift-COMMA"),
    K("RC-DOT"): K("C-Shift-DOT"),
```

Not sure what the purpose of this is meant to be since it seems to just type right angle bracket ">" in my terminal. I can't seem to find reference online to a Ctrl+Shift+Dot shortcut for terminals. 

Or Ctrl+Shift+Comma either. Are these actually meant to output angle brackets? 

I'm having no luck mapping to Ctrl+C. It comes out as Ctrl+Left_Bracket in the terminal.

**Comment by rbreaves** [comment]
No particular purpose other than complete coverage for a shift variation during term usage. I don't want to predict all of the terminal based hotkeys - but I do know that even if it does nothing.. it does not harm my cause as far as I can tell. Most, if not all, linux terminals treat GUI based modifications as needing Shift from what I can tell and that is what Cmd should do.

**Comment by RedBearAK** [comment]
@rbreaves 

> No particular purpose other than complete coverage for a shift variation during term usage. I don't want to predict all of the terminal based hotkeys - but I do know that even if it does nothing.. it does not harm my cause as far as I can tell. Most, if not all, linux terminals treat GUI based modifications as needing Shift from what I can tell and that is what Cmd should do.

Your words let me see the pattern now. 

But I figured out why my terminal mapping to Ctrl+C wasn't working. For some reason it's being unexpectedly overridden by this line I put in the former "None" block, even though I'm trying it out in xfce4-terminal, which is definitely in the "terminals" string. So I was actually getting the "Escape" character entered into the terminal. 

```
# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-DOT"): K("Esc"),                          # Mimic macOS Cmd+dot = Escape key (not in terminals)
```

To test I changed it to: 

```
# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-DOT"): K("LC-C"),                          # Mimic macOS Cmd+dot = Escape key (not in terminals)
```

And suddenly I'm getting Ctrl+C from Ctrl+dot, in the terminal. Even though I disabled all Ctrl+dot mappings inside the terminal block. I can't understand why it's mapping this way inside a terminal application. 

I wanted Ctrl+dot to be "Escape" in GUI apps, and "Ctrl+C" inside terminals. This is how it works throughout macOS. It's a perfect intuitive shortcut because most of the world calls the period character a "full stop", so it's very easy to remember. But as long as I have the mapping to Escape in the former "None" block, the mapping inside the terminal block seems to be getting canceled out. So I can't have them both active at once. 

I feel like something's not right here. I should be able to define one mapping for GUI apps and one for terminals, and they shouldn't interfere with each other, right? The WM_CLASS of the terminal window is correct. 

I made this, specifically targeted at xfce4-terminal: 

```
define_keymap(re.compile("xfce4-terminal", re.IGNORECASE),{
    K("RC-Dot"): K("LC-C"),
}, "xfce4-terminal Cmd+dot mapping")
```

If I place this below the former "None" block (the "not in remotes" block), it gets overridden by the Escape key mapping in the "not in remotes" block. 

If I move it above the "not in remotes" block, it suddenly works in the terminal... and it also does not appear to override the Escape key mapping for a GUI application. So the GUI mapping is overriding the terminal mapping if it comes first, but not vice versa if I switch the order in the `kinto.py` file. 

But I'm not having any trouble that I know of from other shortcuts in the terminal. So I'm not sure what this is about. 

The only solution I can think of at the moment is to put a secondary "termStr" block just above the "not in remotes" block, dedicated to this single shortcut. Like this: 

```
# Opera C-F12

define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("RC-Dot"): K("LC-C"),                     # Map Ctrl+Dot to Ctrl+C in terminals
}, "xfce4-terminal Cmd+dot mapping")

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-DOT"): K("Esc"),                          # Mimic macOS Cmd+dot = Escape key (not in terminals)
    K("RC-Space"): K("Alt-F1"),                   # Default SL - Launch Application Menu (gnome/kde)
    K("RC-F3"):K("Super-d"),                      # Default SL - Show Desktop (gnome/kde,eos)
    K("RC-Super-f"):K("M-F10"),                      # Default SL - Maximize app (gnome/kde)
    # K("Super-Right"):K("C-M-Right"),              # Default SL - Change workspace (budgie)
    # K("Super-Left"):K("C-M-Left"),                # Default SL - Change workspace (budgie)
```

Strange and redundant, but it works. I get the expected behavior in GUI apps and terminals.

**Comment by rbreaves** [comment]
Yea.. I don’t think the GUI block ought to impact terminals at all. I will recheck this behavior because perhaps None vs “not in remotes” is the cause & terminals should be added to remotes to ensure that mapping isn’t happening.

**Comment by RedBearAK** [comment]
@rbreaves 

Had a thought. While it would be good to find out what the conflict is, isn't the fundamental problem here that there will always have to be at least one block of mappings that is "untargeted" (i.e., "generic")? Meaning, it will apply to anything that isn't specifically singled out with a targeted identifier definition. Wasn't that kind of the whole point of the "None" block? 

My Finder mod experiments taught me that if I have to override something specific, I have to include the overriding line higher in the file than the line that needs to be overridden. Which is kind of backwards from what I expected, but I guess that's common with code that's not just interpreted sequentially line-by-line like a simple no-functions shell script. 

So isn't simply moving the "termStr" code block above the former "None" block (and any other "generic" or "untargeted" code block) one of the best approaches to make sure this doesn't happen again? 

I realized this morning that all the shortcuts that I was testing in the terminal and saying they were "working" (like X/C/V, new window, new tab, close tab/window) are not actually defined in the GUI block, since they didn't need to be because they "just worked" right away with the modifier key remapping. That's why they weren't overriding all the terminal Ctrl+Shift shortcuts. There was no immediately apparent major conflict after changing the "None" block, only because of the limited overlap of common shortcuts between the two blocks. 

And that's also why moving that one remapping above the "not in remotes" block didn't interfere with the generic GUI mapping for the same shortcut. Because mine was properly limited by its scope only to terminals. So moving the entire "termStr" block to the same place shouldn't be harmful to anything. Just like my file manager mod blocks didn't harm anything, because they only work in the specifically named file managers. 

So I feel like it should be standard procedure to put the block that is most generically "untargeted" at the very end of the file, with all other "targeted" blocks always above it, not just the terminal block. Maybe with a nice big warning line above and below it saying not to put any new keymap definitions below that section in the file. That way users know that if they want to customize for some specific application or purpose, it needs to go above that to be sure it will override generic key mappings. 

Thoughts? Does this make any sense?

**Comment by rbreaves** [comment]
You're missing a key extension of the remotes variable, I extend it to terminals and vscode as well to ensure the normal GUI remaps don't apply to them. They still ought to get what they need though generally.

```
remotes = ["org.remmina.Remmina","xfreerdp"]
remotes = [client.casefold() for client in remotes]

# Add remote desktop clients & VMs for no remapping
terminals.extend(remotes)
mscodes.extend(remotes)

```

**Comment by RedBearAK** [comment]
@rbreaves 

Cmd+Dot mapping for terminals and GUIs has been integrated in current Kinto.

GUI mapping inappropriately overriding terminal mapping was solved. 

Closing this issue. Nice work.
