### ISSUE TITLE
is it possible to make my mac have same keyboard function as linux/pc?

### ISSUE THREAD

**Issue by chovy** [rbreaves/kinto#439]
I have a mac for work but I want to swap the keys for ctrl/alt

so they are the same as linux/pc

will this app let me do that?

**Comment by rbreaves** [comment]
No & currently there are no plans to bring it to macOS as there’s no point. Also macOS already has what you need built in to remap all the modifier keys w/o any 3rd party tools, but it can also be done via the right terminal commands or karabiner-elements. Kinto just doesn’t make any sense for macOS.
