### ISSUE TITLE
Delay when lauching guake terminal

### ISSUE THREAD

**Issue by FranzFelberer** [rbreaves/kinto#45]
Dear all,

thanks for the great tool. I have some issues using it with the guake terminal.
* The response is quite delayed when using the shortcut (standard F12) for toggle visibility. (2-3sec)
* I would like to the super (command) key + D to toggle visibility. I can't figure out how to do so.

Using Ubuntu 19.10

**Comment by rbreaves** [comment]
That seems to be odd to me, that the response would be delayed, regardless of the keymap that is loaded, mac_gui or mac_term, the F keys are not yet being remapped any at all.

There is a very slight delay on input however while the new keymap is being loaded, most people will not notice it at all however. It's difficult for even me to pick up on it, as I can only do so under very specific circumstances that involves wordwise with the web browsers.

Reading up on how to toggle Guake I guess you have two options that would probably work. You can fix it in the xkb files or use xbindkeys. If you use xbindkeys you may want to also append the fix to the onInput field.

If you use the xkb method then you will need to make sure you are using the current Dev version or figure out the difference of the symbols order as I have just re-ordered them slightly to make more sense and I added 7 more combination levels than what I had before. https://github.com/rbreaves/kinto/commit/3f4b5241eb29ce43211d2165f05fb7b8d6d0ebab

## xkb

```
// Template
// replace key <KEY> {
//     type[Group1]= "ONE_LEVEL_CTRL",
//     symbols[Group1]= [
//         Base,
//         Alt,
//         Shift Alt,
//         Control,
//         Shift Control,
//         Super,
//         Shift Super,
//         Control Alt,
//         Super Control,
//         Super Alt,
//         Super Control Alt
//     ],
//     actions[Group1]= [
//         NoAction(),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Mod1),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Mod1+Shift),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Control),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Control+Shift),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Super),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Super+Shift),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Control+Alt),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Super+Control),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Super+Mod1),
//         RedirectKey(key=<KEY>,modifiers=NewMod,clearmods=Control+Mod1)
//     ]
// };
```

AC03 = d

nano ~/.xkb/symbols/mac_gui
```
...
replace key <AC03> {
        type[Group1]= "ONE_LEVEL_CTRL",
        symbols[Group1]= [
            d,
            D,
            d,
            D,
            d,
        ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            // Pass Alt/Shift + G normally
            RedirectKey(key=<AC05>),
            RedirectKey(key=<AC05>),
            // Cmd/Ctrl+D = F12
            RedirectKey(key=<FK12>,clearmods=Control),
        ]
    };
...
```

## xbindkeys
nano ~/.config/kinto/.guake-gui
```
﻿"guake -t"
   Control + D + Release
```
nano ~/.config/kinto/.guake-term
```
﻿"guake -t"
   Control + Shift + D + Release
```

And then update your user_config.json file
nano ~/.config/kinto/user_config.json
```
...
"name": "gui",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1;xbindkeys -f $HOME/.config/kinto/.guake-gui"
...
"name": "term",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1;xbindkeys -f $HOME/.config/kinto/.guake-term"
...
"name": "firefox",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1;xbindkeys -f $HOME/.config/kinto/.guake-gui;"
...
...
"name": "chrome",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1;xbindkeys -f $HOME/.config/kinto/.guake-gui;"
...
```

**Comment by rbreaves** [comment]
If you use xbindkeys you could also add it as a tweak, but I need to make sure that the tweak order occurs after the run_off/onInput commands, otherwise it could kill a tweak that has been added via xbindkeys. Granted tweaks are only ran once, so if you are in chrome or Firefox then it absolutely needs to be added  after the run_offInput command (unless that command is changed to only kill specific scripts running, which it probably should specify.)

**Comment by FranzFelberer** [comment]
Thanks for your detailed answer. I will work trough it and give you feedback.
About the delay: as soon as any GUI program is running there is a noticeable delay. If no GUI program is open no noticeable delay.

**Comment by rbreaves** [comment]
To see if you can lessen the delay I'd suggest that you edit the user_config.json file slightly to see if it can speed it up, take out the "setxkbmap -option;" from the run fields. It's likely not needed, but I have it there just to make sure any cache is cleared before applying another xkbcomp. I believe it can be a source of delay.

nano ~/.config/kinto/user_config.json
```
"run":"setxkbmap -options;..."
```

**Comment by FranzFelberer** [comment]
Thanks for your answer:
* xkb: if I switch to dev strange things are happening in the terminal. The arrow keys don't search history anymore but increase/decrease the height of the terminal...
* uninstall results in:
Removed /home/franz/.config/systemd/user/default.target.wants/keyswap.service.
sed: can't read /home/franz/.Xsession: No such file or directory
Is that a hint?
* removing "run":"setxkbmap -options;..." seems to improve the lag slightly

**Comment by FranzFelberer** [comment]
Some weird things are going on. leaving the guake terminal (fn+F12) to use firefox the first time I use cmd+c it opens the developer tools (as if it would copy/reapply the last keys again)

**Comment by FranzFelberer** [comment]
* using the xbindkeys method kind of works but:
  *  opens the terminal
  * closes the terminal but reopens it again
  * doesn't work in input fields (when the cursor/mouse is in this one)

Maybe i should add that I use the hide on lose focus option in guake (main window settings)?

**Comment by rbreaves** [comment]
If you checked out the specific version in dev that I mentioned it is possible that I broke some keybindings.. I don't think it is broken in the latest version of dev. I just re-installed the latest to make sure my arrow keys work as expected and they do appear to.

It sounds like when you leave the terminal it is not picking up that Firefox is is the active Window, hence cmd+c is actually cmd+shift+c. I would suggest that you monitor the output of the service while it is running and you are switching windows. It is odd though, because even if your Firefox app had a different name than what I would expect it should still trigger a gui keymap. It is odd that you are being left on gauke.
```
journalctl --user -f -u keyswap.service
```

And I am not sure what you may need to do if you go the xbindkeys route, I provided what I could without testing it myself, but I will do a quick install of the app and see how it behaves on my system.

**Comment by FranzFelberer** [comment]
Hello,

same behaviour with the latest dev commit.
The arrows do not search history but change the size of the terminal.

**Comment by rbreaves** [comment]
I am not sure why that would be the mapping for the arrow keys while holding down the Cmd key position should map to PageUp and PageDown and it does on my terminals I've tested it with.

It's that 3rd action you see where it is clearing the Control+Shift and only initiating PageUp or PageDown.

```
    // Page Up
    replace key <UP> {
        type[Group1]= "ONE_LEVEL_CTRL",
        symbols[Group1]= [
        Up,
        Up,
        NoSymbol ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            RedirectKey(key=<PGUP>,clearmods=Shift+Control)
        ]
    };
    // Page Down
    replace key <DOWN> {
        type[Group1]= "ONE_LEVEL_CTRL",
        symbols[Group1]= [
            Down,
            Down,
            NoSymbol
        ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            RedirectKey(key=<PGDN>,clearmods=Shift+Control)
        ]
    };
```

I have made an additional commit today, but nothing that would impact this, the commit is prepping the Alt+Tab window switching for use with the terminal and the gui apps, so not even fully implemented just yet (not all distros use Alt+Tab and I need to make sure I keep track of defaults before I go changing any system settings. One thing I am proud of is that Kinto, so far does not make system level changes.).

**Comment by rbreaves** [comment]
I see what you mean now.. looks like the multi level types were creating some sort of conflict that I cannot see with xbindkeys.. it is as if the control key is held down when it isn't. The latest dev branch should fix it. https://github.com/rbreaves/kinto/commit/e8a8c0ed569b6e650b1bafbdc582b5caba7f5d00 @FranzFelberer 

Add this to bother your gui and term symbols files like I mentioned earlier if you want Cmd + D to activate guake

```
    replace key <AC03> {
        type[Group1]= "ONE_LEVEL_CMD",
        symbols[Group1]= [
            d,
            D,
            F12
        ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            // Cmd/Ctrl+D = F12
            RedirectKey(key=<FK12>,clearmods=Control)
        ]
    };
```

**Comment by FranzFelberer** [comment]
Great, thanks a lot. I can confirm the problem with the arrow keys is gone and the CMD + d works now. I thinks also the lag has improved.

**Comment by FranzFelberer** [comment]
Unfortunately basic things like CMD + C, CMD + V doesnt work any more.
