### ISSUE TITLE
Kinto with mouse 7 keys: problems on copy-paste

### ISSUE THREAD

**Issue by suikoy** [rbreaves/kinto#464]
First of all congratulations for this project, it's really amazing!!!
I'm on linux at the moment (KDE Neon) but I am so comfortable with macOS shortcuts that I'm trying Kinto with my mechanical windows keyboard (with AltGr tweak) and the result is perfect :)
It is really a pleasure to be able to use cmd+a cmd+c etc also on linux.
Just a problem/question: I have a 7 key mouse (Logitech G402) and from long time I used this _xbindkeysrc_ configuration:

```
 #### 1' side mouse button (b:8) ---> copy
"xte 'keydown Control_L' 'key v' 'keyup Control_L'"
  b:8

#### 2' side mouse button (b:9) ---> paste
"xte 'keydown Control_L' 'key c' 'keyup Control_L'"
  b:9    
```
without problems. But now with Kinto enabled, it does not work anymore...
I tried a lot of combinations but none work :-(
So some advice to fix it would be much appreciated, thanks

**Comment by rbreaves** [comment]
Not sure which keyboard layout you are using but depending on that you could try a few things.. have it press Alt or Win/Super instead & see if that fixes it. Or update the xkeysnail.service file to be explicit to the keyboard device you are using, more info in the xkeysnail repo on that (parameters).

**Comment by suikoy** [comment]
Yes I tried everything from Alt or Super to the combo CTRL+INS (that is another way to copy) but no luck with xbindkeysrc. 
I think that the problem is the command 'keydown' with Kinto in the middle but I'm not sure...
Anyway my keyboard has italian layout but the position of control win alt c or v keys is the same to the english layout. 
Ok I will try with some customisation with xkeysnail...
If you have any other suggestions / ideas please tell me, thanks

**Comment by rbreaves** [comment]
All I can suggest is to edit ```/lib/systemd/system/xkeysnail.service``` w/ the device parameter similar to '--devices "Logitech MX Keys"' .

May need to run the xkeysnail command directly and normally with kinto not running so that you will see it tell you what your keyboard device name is.

You can then save it and reload it. ```sudo systemctl daemon-reload```

https://github.com/rbreaves/kinto/issues/335

**Comment by suikoy** [comment]
Ok thanks for your suggestion now the mouse is working property!!
What I have done:
#### 1. identify keyboard input id
From the terminal:
`sudo apt install evtest -y && sudo evtest`

After some attempts, I found that my keyboard was:
`/dev/input/event6:      Gaming KB  Gaming KB`

#### 2. backup & edit service file
`sudo cp /lib/systemd/system/xkeysnail.service ~/xkeysnail.service.bck`
`sudo vi /lib/systemd/system/xkeysnail.service`

#### 3. add --devices option
`ExecStart=/usr/bin/sudo /bin/bash -c '/usr/bin/xhost +SI:localuser:root && /home/mark/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --devices /dev/input/event6 --quiet --watch /home/mark/.config/kinto/kinto.py'`

#### 4. restart service and kinto
`sudo systemctl daemon-reload` 
(I restarted kinto from the tray icon)

Enjoy copy-paste from mouse buttons :-D

**Comment by rbreaves** [comment]
I am not sure that event number won't change on you on reboots, so it might be advisable to change that to the actual device product name instead as this guy had done.

https://github.com/rbreaves/kinto/issues/335

**Comment by suikoy** [comment]
I tried the reboot and everything it's fine. I had some problems to identify the device name of my usb keyboard so evtest offers me a simple solution
