### ISSUE TITLE
Right Super Key question

### ISSUE THREAD

**Issue by zaphod80013** [rbreaves/kinto#478]
Just started looking at Kinto tonight as a replacement for my current remap solution, trying it on a fresh pop 20:10 install it looks awesome apart from the system tray but run into a key mapping problem. 

I'm extremely Left handed so hardly ever use the meta-keys on the right side of the keyboard and have never used a numeric keypad. I have a 2019 16" MBP (Work machine) and 2 System 76 GalagoPro  machines (a new GALP5  & my old GALP3) that run POP_OS I currently use AutoKey to remap key in the Tilix to match (as closely as possible) the key in iTerm2. My main keyboard is a Macally keyboards with separate right and left Super (CMD) keys keycodes 133/134 respectively. I map the Right Super to application overview since I never use it otherwise. (On the GALP3 I map Menu (135) to the same role.

I was hoping to free the mapping of Right-Super to retain it's existing function but couldn't find it in the config, looking at the install log it look as if it may have a hardcoded mapping outside the config file.

Is there a way to unmap it to restore the original functionality as Right-Super so I can continue to use it for Application Overview?

Also I map cmd-K to a clear screen & scrollback buffer in the terminal which is currently a shell printf for the escape sequence. how would I go about mapping the a python function to the same task.

If these have been asked before, a link to the relevant answer would be appreciated.

**Comment by rbreaves** [comment]
You should be able to edit this kinto.py file here and find anything that looks like and comment it out. That will restore the right Super key.
```
Key.RIGHT_META: Key.RIGHT_CTRL,
```
To restore the app overview hotkey you can do this, but I am not sure what the right super specified looked like. Kinto normally wipes this out on install as cmd-space is the combo for this behavior on either side.

```
gsettings set org.gnome.mutter overlay-key 'super'
```


https://github.com/rbreaves/kinto/blob/master/linux/kinto.py
```
...
# [Global modemap] Change modifier keys as in xmodmap
define_conditional_modmap(lambda wm_class: wm_class.casefold() not in terminals,{
...
}
...
# [Conditional modmap] Change modifier keys in certain applications
define_conditional_modmap(re.compile(termStr, re.IGNORECASE), {
...
}
...



```

**Comment by zaphod80013** [comment]
Thank you for the incredibly quick response. I'll give it a try after work tomorrow, again thanks.
