### ISSUE TITLE
[QUESTION] Multiple stroke keys

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#496]
@rbreaves 

Do you understand what this "multiple stroke keys" syntax is supposed to do, in practical terms? 

### Multiple stroke keys

When you needs multiple stroke keys, define nested keymap. For example, the following example remaps C-x C-c to C-q.

```
define_keymap(None, {
    K("C-x"): {
      K("C-c"): K("C-q"),
      K("C-f"): K("C-q"),
    }
})
```

Does this code make `xkeysnail` wait for either A) Ctrl+C or B) Ctrl+F after detecting Ctrl+X, and then send Ctrl+Q to the application window only after you type the second shortcut after Ctrl+X? That's the only way I can think of to interpret the description. 

If that's the case, what if you never type the second shortcut? Or if you forgot that you typed Ctrl+X and then tried to use Ctrl+C to copy something? The app would quit because `xkeysnail` would send Ctrl+Q? 

Or am I completely misunderstanding what "multiple stroke keys" does? 

This can't be used to fix the problem with "Enter key to rename" in file managers, right?

**Comment by rbreaves** [comment]
If Ctrl-x is not followed by an expected key then it should cancel out of monitoring for the next keypress. If you were to install certain terminal based apps this behavior will probably be apparent - aka sudo apt install tmux. (maybe emacs, but I don't ever use emacs myself)
