### ISSUE TITLE
Allow capslock and swapescape

### ISSUE THREAD

**Issue by binamkayastha** [rbreaves/kinto#50]
Amazing application!
The only really annoy thing thing is that swapescape no longer works:
`setxkbmap -option caps:swapescape`

I think this has to do with how setxkbmap actually works, but I was wondering if there was a way to:
A) avoid conflicts with setxkbmap
B) allows us to swap capslock and escape key through kinto (I've tried mucking around in the user_config.json but to no avail)

**Comment by rbreaves** [comment]
For which keyboard type? Windows and Mac will likely need the same or similar xkb option added, but Chromebooks would need a different config.

**Comment by rbreaves** [comment]
The latest commit now includes the capslock and escape swap option.. I've actually been wanting to apply it any ways. I am not going to update the setup installer just - and until I do that I won't be mentioning in the release notes or incrementing the release number.

https://github.com/rbreaves/kinto/commit/7e676938eee51f1d4b3e47a3a000fac252b7e548

How you apply is like the following, after the Kinto install that you have already done you will not be editing your user_config.json file at all, but the xkb files rather in your user profile.

What I did.
Step 1) Pull the option(s) you want out of the source file(s). 
cd /usr/share/X11/xkb/symbols/ & find the file
or 
vi usr/share/X11/xkb/symbols/capslock
2) Extract
```
...
hidden partial modifier_keys
xkb_symbols "swapescape" {
    key <CAPS> { [ Escape ] };
    key <ESC>  { [ Caps_Lock ] };
};
...
```
3) Added the partial to the mac_gui file (could also go into term, but in reality the term keymap can also reference mac_gui and in this case I let it be so).
vi ~/.xkb/symbols/mac_gui
Add partial anywhere in file (this was done in the latest commit.

What you'll need to do.
Step 1) Edit your keymap files
vi ~/.xkb/keymap/kbd.mac.gui
Change
```
xkb_keymap {
...
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)"	};
...
};
```

to
```
xkb_keymap {
...
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)+mac_gui(swapescape)"	};
...
};
```
Do the samething with term.
vi ~/.xkb/keymap/kbd.mac.term

You can do the browser files too if you want.. probably don't really need to though.

**Comment by binamkayastha** [comment]
Oh my gosh you're a beast! Thank you so much, it worked for me.
I have a windows keyboard, and don't own a chromebook so I can't check if it works there :(

The amount of mental relief that this program gives me is absolutely phenomenal.

**Comment by raicem** [comment]
Hi! Thank for this amazing tool @rbreaves. Makes my life so much easier. 

Just wanted to document how to swap capslock and esc after upgrading to the latest version with `xkeysnail` for dummies like me.

If your old capslock and esc configuration was in `xkb`, it will not work now that you are using `xkeysnail`. Therefore you have to update your `xkeysnail` configuration. Luckily, it's very easy. This configuration lives in the `~/.config/kinto/kinto.py` file. You can take a look at how to configure this config file from [here](https://github.com/rbreaves/kinto#shortcut-creation-xkeysnail) and [here](https://github.com/mooz/xkeysnail#how-to-prepare-configpy).

If you just want to swap capslock and esc, here is what I added to my `kinto.py` config file.

https://gist.github.com/raicem/9991bd6c0b4e4590e4167ff72df2b870

This just swaps it. You can also do things like, if the capslock is pressed and released it behaves like esc but if you hold capslock button it behaves like a normal capslock key. I saw that option here: https://gist.github.com/ponimas/6c39c66232be04d0e421a9d054db648d#file-xkeysnail-py-L21
