### ISSUE TITLE
Kinto not working on elementary OS with Logitech MX Keys

### ISSUE THREAD

**Issue by arumihsok** [rbreaves/kinto#503]
**Describe the bug**
I'm trying to install Kinto on elementary OS .
I entered in the terminal the installation instructions on README.md, and had Kinto installed. After the command finish doing its thing (the installation), a window (Kinto.sh) shows up and it is trying to do something, on a loop. There is a status indicator on the bottom right displaying "inactive" most of the time, and the program doesn't work as expected.

Apparently it's trying to find my keyboard with no success. Any way to solve this?

**Expected behavior**
I wanted the keyboard to emulate macOS modifier keys on elementary OS. Meaning cmd on elementary OS = cmd on keyboard, for example.

**Install Type:** Bare Metal
**Distro:** elementary OS 5.1.7 Hera
**DE:** Pantheon
**Branch:** master I guess
**Commit:**

**Screenshots**
![Screenshot from 2021-05-06 12-43-59](https://user-images.githubusercontent.com/59707759/117327432-f8dd0c00-ae68-11eb-9bd2-d19f8516ce4b.png)

Did not find a way to copy the log so I decided to post a screenshot instead.

**Comment by rbreaves** [comment]
On my phone atm or I’d link you, but sorta - you need to edit the xkeysnail.service file to include a --device parameter for your specific keyboard. You ought to be able to find past open tickets that discuss this in more detail.
