### ISSUE TITLE
syslog: TERM environment variable not set

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#515]
Just randomly opened up `/var/log/syslog` for reasons unrelated to Kinto and saw this, it's happening every couple of seconds: 

```
May 13 10:44:37 aspire5-ubuntu2104 kintotray.desktop[198324]: TERM environment variable not set.
May 13 10:44:39 aspire5-ubuntu2104 kintotray.desktop[198338]: TERM environment variable not set.
May 13 10:44:41 aspire5-ubuntu2104 kintotray.desktop[198341]: TERM environment variable not set.
```

Edit: Closed the tray app and re-enabled from the GUI, and those messages changed to talking about `gnome-shell`. Maybe this is specific to a GNOME environment. But they stopped while the tray app was disabled, and resumed when I enabled it. 

```
May 13 11:23:24 aspire5-ubuntu2104 gnome-shell[210258]: TERM environment variable not set.
May 13 11:23:26 aspire5-ubuntu2104 gnome-shell[210267]: TERM environment variable not set.
May 13 11:23:28 aspire5-ubuntu2104 gnome-shell[210276]: TERM environment variable not set.
```

**Comment by RedBearAK** [comment]
Possible solution: Since this was happening so frequently, I theorized that it was being triggered mostly by the "polling" function. 

Tried inserting "export TERM=xterm-color; " in front of the shell command that gets run by the `Popen` function, inside the class that polls to check Kinto status. 

Original: 
```
        kinto_status = Popen("while :; do clear; pgrep 'xkeysnail' && echo 'active'; sleep 2; done", stdout=PIPE, shell=True)
... 
        kinto_status = Popen("while :; do clear; systemctl is-active xkeysnail; sleep 2; done", stdout=PIPE, shell=True)
```

Change to: 
```
        kinto_status = Popen("export TERM=xterm-color; while :; do clear; pgrep 'xkeysnail' && echo 'active'; sleep 2; done", stdout=PIPE, shell=True)
... 
        kinto_status = Popen("export TERM=xterm-color; while :; do clear; systemctl is-active xkeysnail; sleep 2; done", stdout=PIPE, shell=True)
```

This resolves the errors in the log and seems to allow the icon to still mirror the current status of the `xkeysnail` service. Whether starting/restarting/stopping from the menu or from the terminal with `systemctl`. 

A similar error shows up whenever the GUI window is open, presumably for the same reason, the polling function. 

... and confirmed. I applied the same change to `kinto-gui.py` and don't see anything about `TERM` in `syslog` anymore. Of course. 

Not sure if this is the best possible way to solve the problem, but at least it pinpoints the exact source of the error that's filling up the log.

**Comment by rbreaves** [comment]
I think there may be a way to pass in the actual user based env vars via the root account it is using.. I imagine that is the cause. I bet it is set for the regular logged in user - but not the sudo/root user. But nice find, I know that does need to be eliminated out of the log.
