### ISSUE TITLE
Jetbrains Webstorm, alt is ctl+shift

### ISSUE THREAD

**Issue by mbonig** [rbreaves/kinto#518]
**Describe the bug**
When using Jetbrains' Webstorm the alt key registers as ctl+shift. 

**Expected behavior**
As with all my other apps I expected alt to register at ctl/cmd.

**Install Type:** Bare Metal 
**Distro:** Ubuntu 21.04
**DE:** i3
**Branch:** master
**Commit:** 9fb72c9

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```
Show's active and running.

**Screenshots**

![image](https://user-images.githubusercontent.com/1559437/119292452-a7c16c00-bc0d-11eb-97e4-895fe7c650cb.png)

In this screenshot I've tried setting up a new shortcut, this is what I got when I hit 'alt-c'

**Additional context**
I remove the entire jetbrains section from my ~/.config/kinto/kinto.py file.

**Comment by rbreaves** [comment]
I don't really understand how this is happening for you, that type of behavior should only be seen in Terminals - not Jebtrains (or even the terminal in jetbrains - I can't detect those yet).

The only modifier key w/ C combo is the Super-C one, but Super is located on your physical Ctrl key during Kinto usage. When you press the physical Alt key w/ C you should be getting Ctrl-C. When you press middle modifier key (Win key on some & Alt on others) w/ C then that should register as Alt-C.

There's no scenario that I can see where Ctrl+Shift+C should be happening from inspecting the current config.

```
# Keybindings for IntelliJ
define_keymap(re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE),{
    # General
...
    # VCS/Local History
    K("Super-v"): K("M-Grave"),                 # VCS quick popup
    K("Super-c"): K("LC-c"),                    # Sigints - interrupt
},"Jetbrains")

```

Only the terminals group would do this remapping.

```
define_keymap(re.compile(termStr, re.IGNORECASE),{
...
    K("RC-C"): K("C-Shift-C"),
...
}, "terminals")

```

**Comment by mbonig** [comment]
Do you think there could be some toss-up happening with i3?

**Comment by mbonig** [comment]
I found the issue!  In your terminals definition you have 'st' as a terminal name:

https://github.com/rbreaves/kinto/blob/master/linux/kinto.py#L24

I believe this was regex matching against 'jetbrains webSTorm', causing the terminal shortcuts to being applied there. Once I removed that line then Webstorm started working as expected.

**Comment by rbreaves** [comment]
I will take a look at this later! But thank you - I should be able to fix this relatively soon.

**Comment by rbreaves** [comment]
Done. That was a really nice catch/find! I don't think it was that long ago that someone had contributed the ST terminal, I've never used it myself - apparently a light weight xterm alternative. I was really to blame though - I did not write the regex correctly to enforce whole matches only like I should have. That is the case going forward though 😅.

**Comment by mbonig** [comment]
no problem. I love this repo so anything I can do to help =-}
