### ISSUE TITLE
end of line start of line everywhere

### ISSUE THREAD

**Issue by imduffy15** [rbreaves/kinto#52]
Hi,

Is it possible to get ctrl+a and ctrl+e do start of line and end of line everywhere just like OSX?

**Comment by rbreaves** [comment]
Hmmm.. I had not noticed but yes, that'd be a simple thing to fix. I'll make a hotfix update for it and merge it to master shortly.

**Comment by rbreaves** [comment]
I was going to hotfix it, but that would have really require backporting changes in the dev branch and I didn't feel like doing that. I believe you should be fine on the Dev branch if you use Gnome or xfce, but KDE is problematic. The dev branch actually adds in a number of other mac like shortcuts listed in my Translation Table post https://github.com/rbreaves/kinto/issues/44.

I will be adding these 2 to the table as well. One thing the dev branch does not do fully yet is also undo the DE level shortcuts if the service ends or kinto is removed, so I have to work that out plus KDE issues before I can merge it to master for a release.

**Comment by imduffy15** [comment]
Amazing! Thank you, will try it out. 

I’d love to get to know your project better and hopefully contribute to it.

**Comment by rbreaves** [comment]
That'd be pretty awesome, I'll accept any contributions that you and others make as long as it makes the keyboard more similar to a mac. I might allow for other modifications as well if it is done in an optional sort of way though.

**Comment by rbreaves** [comment]
@imduffy15 I discovered a bug with my implementation of Ctrl+A/E today, apparently chrome decided that it wanted to do Select-All on that combo, so I updated dev just now to prevent that from occurring. It appears like it is fine, but let me know if the latest in dev doesn't resolve it. https://github.com/rbreaves/kinto/commit/b9042356536bfd3835be4ac4af0a0349fccd6354
