### ISSUE TITLE
Mac Keyboard PT Layout

### ISSUE THREAD

**Issue by jareis** [rbreaves/kinto#544]
Hello,

I'm using Linux with a mac keyboard PT Layout. Some of the keys are not correctly mapped. Is there any location where I can correct the mapping?

By the way.... thank you for the solution.

**Comment by rbreaves** [comment]
The kinto repo pulls xkeysnail from my fork and kinto branch of it. If you were to fork off of mine you can make whatever changes you want to the key.py and there may be other issue tickets on here that can help assist in that endeavor. If people come up with good multi-language type patches to extend xkeysnail then I will happily pull those changes in. Those changes would occur on the xkeysnail project however.

https://github.com/rbreaves/xkeysnail/blob/kinto/xkeysnail/key.py

The original
https://github.com/mooz/xkeysnail/blob/master/xkeysnail/key.py

Closing for now, if anyone sends me PRs for other languages, on my xkeysnail fork, or submits PRs to mooz concerning this then it will be upstreamed into my fork and thus Kinto.
