### ISSUE TITLE
[Windows] How to make lang switch on cmd+space?

### ISSUE THREAD

**Issue by neronmoon** [rbreaves/kinto#548]
Hey! Just trying to use kinto and its great!
On mac i use non-default setup: cmd+space to switch language and ctrl+space to open spotlight. 
Kinto how can i make it with kinto?

**Comment by rbreaves** [comment]
Linux

~/.config/kinto/kinto.py

```
...
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Space"): K("Alt-F1"),                   # Default SL - Launch Application Menu (gnome/kde)
    ...
```

Windows

~\\\.kinto\kinto.ahk

```
...
; Cmd+Space Alternative
    $^Space::Send ^{Esc}
...
```

Without knowing your DE or OS I do not know what app or hotkey would trigger a language but I probably wouldn't know that any ways. Changing those lines are what you would want.

**Comment by neronmoon** [comment]
Ok! Thanks, looks like i made it
```
    ; Cmd+Space Alternative 
    $#Space::Send ^{Esc}
    $^Space::Send #{Space}  
```
