### ISSUE TITLE
I can't copy/past with Cmd+C / Cmd+V

### ISSUE THREAD

**Issue by taikio** [rbreaves/kinto#554]
**Is your feature request related to a problem? Please describe.**
I am using Elementary OS 5.1 on a Macbook Air 2017. I can use the Cmd key to open application drawer, switch between windows and workspaces. But the script don't overrides the Copy/Past functionality, for this tasks i need to use Control key

**Describe the solution you'd like**
I wish I could use Cmd+C / Cmd+v shortcuts to copy and paste

**Describe alternatives you've considered**
if possible, could you overwrite these shortcuts as was done with the others?

**Additional context**

**Comment by rbreaves** [comment]
I’m really confused by this.. Kinto is set to use the Apple Keyboard Type in the app? Are you sure you weren’t already remapping your copy & paste keys??

I’m almost certain I’ll be closing this ticket & that this is user error. The terminal also needs you to disable natural copy & paste if it isn’t already.

**Comment by taikio** [comment]
After installation I restarted the system and the shortcuts were already activated. I can't run the app, when I run the command `~/.config/kinto/gui/kinto-gui.py` in the terminal I get the following error:

```bash
Traceback (most recent call last):
  File "/home/welker/.config/kinto/gui/kinto-gui.py", line 7, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

**Comment by rbreaves** [comment]
VTE, that's an old error. Read through this issue ticket, it will surely get you where you need to be. More info about your distro would be appreciated so proper support can be added for it later.

https://github.com/rbreaves/kinto/issues/402

**Comment by rbreaves** [comment]
This is also related, so this VTE thing has been a known issue, needing to be updated.

https://github.com/rbreaves/kinto/issues/494

**Comment by taikio** [comment]
The Issue mentioned above helped me to resolve the problem. I uninstalled Kinto completely, and before reinstalling I installed the libs `gir1.2-vte-2.91`,  `gir1.2-notify-0.7` and added my user to `systemd-journal` group.

For some reason the Cmd+Tab shortcut was not working, so I went to the settings and re-signed it and it worked again.

Thanks for your support @rbreaves
