### ISSUE TITLE
[question] Dead keys in super button for tildes

### ISSUE THREAD

**Issue by kyuumeitai** [rbreaves/kinto#56]
Hi there, great work! works great on Manjaro Gnome.
The altgr (right key after the space) was the dead key by default in english (macintosh) distribution keyboard. You press it altgr + e , vowel and you gain an accented e (é) the altgr + n (ñ) and so on.

Wondering if I can put the dead key in super key with that behaviour? Thank you!

**Comment by rbreaves** [comment]
I suppose that'd be possible, I don't really deal with altgr personally, and when you say it is the dead key by default for english (macintosh) do you mean an english (macintosh) xkb layout under linux or how it behaves under macOS?

The file you probably want to edit is the following. And you probably want to update types, symbols and maybe geometry.

Append the following to the file.
type: +numpad(mac)
symbols: +us(mac)
maybe geometry: macintosh(macbook78) ? (Really dependent on your keyboard/laptop)
https://ubuntuforums.org/archive/index.php/t-2264826.html

~/.xkb/keymap/kbd.mac.gui
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete+mac_gui(addmac_levels)"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)+mac_gui(mac_appcycle)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

If editing that file works for you (and then toggling from terminal to gui to confirm) let me know and I will make an update for accent support.

**Comment by kyuumeitai** [comment]
> I suppose that'd be possible, I don't really deal with altgr personally, and when you say it is the dead key by default for english (macintosh) do you mean an english (macintosh) xkb layout under linux or how it behaves under macOS?

I mean the english (macintosh) in Gnome settings, I don't know the internals, but has that dead keys in 
https://imgur.com/a/7prKUeG

https://www.thoughtco.com/panish-accents-and-symbols-in-ubuntu-3080298

**Comment by rbreaves** [comment]
I think this is now the case with xkeysnail and can now be easily accessed and enabled via the Tweaks menu, either under Edit or Customize depending on sys tray or the gui app. So marking as solved.
