### ISSUE TITLE
How to map CAPS+ijkl to arrow keys

### ISSUE THREAD

**Issue by chocological00** [rbreaves/kinto#562]
OS: Ubuntu Budgie 20.04

Kinto version: 1.2

Hi, first of all, thank you for making this! I am really liking it so far. :>

I'm trying to port my custom keymaps from other mapping software to kinto.py, since using both seems to conflict in some occasions.

One of my custom keymap is mapping `CAPS + i/j/k/l` as arrow keys (up, left, down, right respectively). The way I achieved this in the previous mapper was to make `CAPS` work as a `HYPER` modifier key, and mapping `HYPER+i/j/k/l` as arrow keys. 

I might be missing something obvious since I'm new to xkeysnail, but it seems like xkeysnail isn't supporting `HYPER`. Is there any good way to make `CAPS` behave as a completely new modifier key? If not, what's the best way to make `CAPS+i/j/k/l` to work as arrow keys?

**Comment by rbreaves** [comment]
Should be quite a few examples in the ~/.config/kinto/kinto.py file.

line 104 would let you remap caps to Ctrl if you want as well. Also you can read up on xkeysnail from the mooz repo of xkeysnail.

https://github.com/rbreaves/kinto/blob/master/linux/kinto.py#L104

**Comment by chocological00** [comment]
Seems like mooz/xkeysnail isn't supporting `Hyper` :<. I think [this](https://github.com/pat-flew/xkeysnail/commit/663729c18b2c446932b29eedf7b368e323276e90) might work, but I didn't want to bother swapping out kinto's dependencies. (This method would also behave weirdly with Japanese IMEs).

For now, I remapped `CAPS` to `ALT` and assigned `Alt+i/j/k/l` to arrow keys.

Thanks for your help!

**Comment by rbreaves** [comment]
Yea, I recall some prior conversation about Hyper, and I can certainly look into merging pat's PR into my fork of xkeysnail. That is a nice catch though on that commit. https://github.com/pat-flew/xkeysnail/commit/663729c18b2c446932b29eedf7b368e323276e90

https://github.com/rbreaves/kinto/issues/421
https://github.com/mooz/xkeysnail/issues/118

**Comment by bjohas** [comment]
Hi @rbreaves - I would still love to have Hyper incorporated into (your fork of) xkeysnail. Esp. with Ubuntu 22.04 LTS, I'll revisit a bunch of keyboard mappings, and I would love to have Hyper in xkeysnail :)

**Comment by rogdex24** [comment]
@chocological00 can you please share the snippet on how you remapped CAPS to AltGr and assigned AltGr+i/j/k/l to arrow keys. I'm trying to do so but struggling with it, it would be of great help.

thanks in advance
