### ISSUE TITLE
Middle click doesn't work when kinto is enabled

### ISSUE THREAD

**Issue by the-sushi** [rbreaves/kinto#567]
**Describe the bug**
I can't use middle click to pan around in programs that I'm normally able to, such as Unity or Tiled, with Kinto enabled.

**Expected behavior**
I expected middle click to remain unchanged.

**Install Type:** Standard
**Distro:** Arch Linux
**DE:** XFCE 
**Branch:** master -- Kinto v1.2-10 build e69e529

**Comment by rbreaves** [comment]
May need to open this issue with xkeysnail. There's nothing specific in my config that would modify the mouse wheel click, but the xkeysnail app may be doing something that is impacting your middle click. Closing this ticket, although should it be fixed on xkeysnail then I merge that fix into the branch of xkeysnail that I base Kinto on.

https://github.com/mooz/xkeysnail/issues
