### ISSUE TITLE
Question about tab navigation (intellij / chrome)

### ISSUE THREAD

**Issue by andyd0** [rbreaves/kinto#569]
Hi! Seems like a recent update to kinto has enabled Chrome tab navigation. Before this, I would use `Ctrl-<arrow key>` to move an active window around. I know there is an override as well for Intellij.

I see this for intellij

```
#Right::Send !{Right}           ;Go to next editor tab
#Left::Send !{Left}             ;Go to previous editor tab
```

and for browsers...
```
  ;Tab Navigation
  ^+[::send ^{PgUp}
  ^+]::send ^{PgDn}
  ^!Left::send ^{PgUp}
  ^!Right::send ^{PgDn}
```

If I remove these lines > disable kinto and re enable, the behavior still stays. If I use setup, any changes are overridden with a new file autohotkey file.

How do I override this behavior so I can go back to being able to move windows around as I can with other apps?

**Comment by rbreaves** [comment]
You probably need to exit Kinto completely & then restart it via the vbs script in ~\.kinto or shortcut in the startup folder location.

**Comment by andyd0** [comment]
that worked...thanks!
