### ISSUE TITLE
Any way to preserve some global hotkeys?

### ISSUE THREAD

**Issue by maqdev** [rbreaves/kinto#57]
For example, I'm using Super+Space to switch the keyboard inputs or Super + Escape to open Search menu. Is there any way to preserve those hotkeys globally?

**Comment by rbreaves** [comment]
There are 2 ways to handle it, I think. Whether you use gnome, KDE or xfce the Super key position will be mapped to actually be Alt under GUI or Term based apps.

So just setting the Alt combo would be sufficient & gnome & KDE May allow you to keep Super bound to it as well if you want both, but you may need to set it via the terminal to keep both.

The other method is more important for binding a combo to the physical Alt/Cmd or physical Ctrl key. Those keymaps change based on the app type.

To set a keybind that may change you could still specify multiple keybinds under Gnome or KDE, but not xfce (could point to sh script to trigger an action though). The other way is to edit the user_config.json before install & reset you keybind like I do for Cmd+Space Activity Overview in gnome. It’s fine to install on top of itself.

```
	{
		"id": 2,
		"type": ["gnome3"],
		"active": false,
		"intent":"gui_term",
		"name":"Gnome Activities Overview",
		"description":"Cmd+Space activates Activities Overview",
		"run":"",
		"run_term":"gsettings set org.gnome.desktop.wm.keybindings panel-main-menu \"['<Control><Shift>Space']\"",
		"run_gui":"gsettings set org.gnome.desktop.wm.keybindings panel-main-menu \"['<Ctrl>Space']\""
	},
```

**Comment by rbreaves** [comment]
I believe the earlier explanation should be sufficient in how to go about setting multiple hotkey combos or the DE tweaks in a way that keeps consistency of physical hot keys.
