### ISSUE TITLE
How to change key positions?

### ISSUE THREAD

**Issue by sudhirkhanger** [rbreaves/kinto#579]
Hi there,

The key positions on my Dell Precision 5510 is different from a typical MBP layout. How can I set my Dell to have same layout?

Key positions from left to right

| Dell | Ctrl | Fn | Win | Alt | Spacebar | Alt | Ctrl | Arrow keys |
|-------|------|-----|-------|------|--------------|------|-----|----------------|
| Mac | Fn | Ctrl | Option | Cmd | Spacebar | Cmd | Option | Arroy keys |

If I want keys on my Dell to be in physically same place as Mac what's the best possible way to do it. I did try remapping alt to win in KDE system settings but it doesn't seem to have any effect.

```
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6820HQ CPU @ 2.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
```

**Comment by rbreaves** [comment]
Before running the installer you are to undo all other remaps you’ve done - at the very least to your modifier keys.

After that the installer will properly configure you on Linux. Windows will prompt for which style keyboard you currently use as I have not ported the same UI type installer to Windows.

**Comment by sudhirkhanger** [comment]
I am not using xkb explicitly. I would be using without awareness of it if it's used by Kubuntu by default. But it seems so to me.

1. Should I remove the xkb package?
2. Are you saying Kinto will automatically map **Alt to Cmd**, **Win** and **Right-Ctrl** to **Option**, and switch **Ctrl** and **Fn** so that it matches the Mac.

```
$ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc101
layout:     us
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc101)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+inet(evdev)"     };
        xkb_geometry  { include "pc(pc101)"     };
};
```

**Comment by rbreaves** [comment]
Xkb is just part of x11 & setxkbmap to me is synonymous (the same thing). You don’t need to remove it, it’s just another & different layer to the input stack.

xkeysnail uses uinput/evdev - much closer to the hardware. It manipulates/intercepts & translates input immediately. And yes Kinto literally remaps most everything automatically - needs keymappings at their defaults initially to work best - fill in the gaps after installing Kinto, not before. Also Fn excluded - OS has no knowledge of Fn, that’s in the hardware.

**Comment by sudhirkhanger** [comment]
@rbreaves anything specifically I can to do to ensure key mappings are at their defaults. I have not made any key map changes but you can see that the keys are not properly placed.

Is there a way to reset key mappings to defaults and then reinitialize Kinto?

**Comment by rbreaves** [comment]
During an uninstall of Kinto I offer an option to reset most DEs back to their default factory keymappings if you want to try that. There's an option to restore your original keymaps or the factory ones essentially.
