### ISSUE TITLE
Can't disable kinto

### ISSUE THREAD

**Issue by torma616** [rbreaves/kinto#58]
`systemctl --user disable keyswap` makes `systemctl --user status keyswap` display "disabled; vendor preset: enabled)," but the keyswap.service is still active on computer reboot.

**Comment by torma616** [comment]
Removing the "[Install]" section seems to make it work. Then again, my system just alerted my that there are updates available, so I'll update and report back.

**Comment by torma616** [comment]
Update seemed to fix the issue!

**Comment by rbreaves** [comment]
After you disable a service you also still have to stop the service. I just double checked it and verified though, on either logout and login or reboot once the service is disabled it will stay disabled, no editing of the service is needed.

May I ask why you needed to disable the service? Is there something about Kinto that does not meet your needs or specific setup?

**Comment by torma616** [comment]
@rbreaves I really like this, but the delay when switching between terminal and non terminal apps was bugging me to the point where I think I'd rather just have `setxkbmap -option altwin:ctrl_alt_win` be set as my default and not have it switch layouts based on focus.

If there was a way to accomplish this while still retaining the wordwise changes, please let me know!

**Comment by rbreaves** [comment]
Thank you for you the feedback, I am honestly not sure what the cause of your delay would be. It's nearly imperceptible in my VMs and my 2 chromebooks, hence why I've made it - to lessen delay time compared to other methods I have tried.

One thing you could try to do, if you want, is edit the user_config.json file and remove the "setxkbmap -option;" command that simply resets to defaults just before setting the actual custom keymap and see if that speeds things up for you. That's my only real suggestion at the moment as there will always be some level of small delay when apply xkb keymaps via xkbcomp or setxkbmap.

**example**
Change
nano ~/.config/kinto/user_config.json
```
{
    "config": [
        {
            "name": "gui",
            "run": "setxkbmap -option;xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.gui $DISPLAY 2>&1 | grep -v XF86FullScreen",
            "run_onInput": "",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1",
            "symbols": "",
            "types": "",
            "de": [
                2
            ],
            "appnames": [
                ""
            ]
        },
        {
            "name": "term",
            "run": "setxkbmap -option;xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.term $DISPLAY 2>&1 | grep -v XF86FullScreen",
            "run_onInput": "",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1",
            "symbols": "",
            "types": "",
...
```

To
```
{
    "config": [
        {
            "name": "gui",
            "run": "xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.gui $DISPLAY 2>&1 | grep -v XF86FullScreen",
            "run_onInput": "",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1",
            "symbols": "",
            "types": "",
            "de": [
                2
            ],
            "appnames": [
                ""
            ]
        },
        {
            "name": "term",
            "run": "xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.term $DISPLAY 2>&1 | grep -v XF86FullScreen",
            "run_onInput": "",
            "run_offInput": "killall xbindkeys > /dev/null 2>&1",
            "symbols": "",
            "types": "",
...
```

**Comment by rbreaves** [comment]
@torma616 If you just want to keep the gui mode with wordwise enabled all the time this command is all you need to run on login. You wouldn't need to run the Kinto service at all and could just leave it disabled, but browsers may not replicate the shortcuts of a mac quite as well because Kinto also changes keymaps based on text input fields being active or not so wordwise and back & forwards won't conflict.

```
xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.gui $DISPLAY
```

The keymap file itself ought to look something like this, but may differ due to your keyboard type.
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete+mac_gui(addmac_levels)"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

**Comment by torma616** [comment]
I'm not sure what is causing the delay either. All I know is that when I switch from a terminal to a gui app, I completely lose keyboard for a bit, sometimes only a moment, other times about 20 seconds.

**Comment by rbreaves** [comment]
@torma616 Oh I meant to ask you to check your kinto service log and post it here. Might give me some clues about what is going on.

```
journalctl --user-unit=keyswap.service -b
```
