### ISSUE TITLE
CMD+Spacebar = doesn't do anything - HELP!

### ISSUE THREAD

**Issue by buzuddha** [rbreaves/kinto#580]
Hello,

I'm very happy so far with Kinto but I don't have a way to get the super menu. I'm on Arch with Gnome and rely on the super button for calling/searching programs/files in a spotlight-like fashion. Is there anyway I can get the cmd+space to be equivalent to gnome's super key?

Thanks again!

**Comment by rbreaves** [comment]
Open up the keyboard shortcut binding type settings area and simply rebind your cmd+space combo. Kinto usually rebinds it successfully, but in some cases it does fail to work, the unbinding of the Super/Win is likely more reliable than the rebinding of cmd+space to the app launcher. I do tend to try and use the default start like menu in every linux DE.

I know there are things like Alfred and spotlight alternatives but I keep things stock as much as I can. Closing, but if you continue to have issues then let me know.

**Comment by buzuddha** [comment]
All good! Thanks!
