### ISSUE TITLE
CapsLock to Ctrl on Windows

### ISSUE THREAD

**Issue by clementnuss** [rbreaves/kinto#583]
Hi,
thanks for this wonderful project, makes my life much happier having to work on a windows machine :)

I searched a bit on this in the other issues, but couldn't find smth working in my case.
I'd like to remap the caps lock key to the Ctrl key, when in terminal mode mostly.

Can this be done with `kinto` on Windows ?

Best regards,
Clément

**Comment by rbreaves** [comment]
Sure, just follow this example.

Instead of
```
$CapsLock::LWin
```
do this
```
$CapsLock::LCtrl
```

https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk#L295

If you only want to apply it to terminals then I guess you'd want to only add it to this area instead.

https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk#L673

**Comment by clementnuss** [comment]
Thanks for your advice 👍🏻 

I forgot to mention that I still wanted to be able to use the CAPS_LOCK functionality.
I tried adding
```
$CapsLock::LCtrl
$`LCtrl::CapsLock
```

where you described but this had funny side effects!
I finally went for the solution described [here ](https://www.mavjs.org/post/swap-ctrl-and-capslock-on-windows/) and it works perfectly :) (the original solution comes from [here](https://superuser.com/a/997448))
