### ISSUE TITLE
restore original file

### ISSUE THREAD

**Issue by dacorsa** [rbreaves/kinto#588]
i have installed kinto on ubuntu and now after remove it, left win key doesn't work anymore, can you tell me the kinto application what file modify in /home/user ??

Thanks

**Comment by rbreaves** [comment]
There are plenty of past tickets that cover this already, uninstaller should have fixed it unless you attempted to remove it w/o uninstalling or some other failure occurred while running the uninstaller.

https://github.com/rbreaves/kinto/issues/550#issuecomment-885740258

**Comment by dacorsa** [comment]
Thanks rbreaves for your answer, but i use ubuntu-studio that use KDE, so it doesn't use dconf, what file i have to restore in kde? 
This not works:

gsettings set org.gnome.mutter overlay-key 'super'

Thanks for your reply
