### ISSUE TITLE
Shortcut to insert the "at" or "@" sign with popOS 20.04

### ISSUE THREAD

**Issue by circark** [rbreaves/kinto#596]
Hello

Can't find a way to insert the sign "@" under popOS using kinto.
I tried to insert it as a custom shortcut with: 

`xdotool key --window '$(xdotool getactivewindow)' Ctrl+Shift+U2B50`

But it is not working ... 
Any idea how to solve this? I'm using a Thinkpad X1 Carbon 6th Gen. Normally, the "standard" way to insert this sign (@) is to press "ALT Gr" and 2.
thanks for the help

**Comment by rbreaves** [comment]
Look under tweaks, I think you can disable remapping on the right side.

**Comment by circark** [comment]
thanks, this solved my issue!
