### ISSUE TITLE
Missing file during installation and trouble with remapping

### ISSUE THREAD

**Issue by nbrookie** [rbreaves/kinto#6]
Hi there, thank you for for effort with this super useful key remapping!

I have run into two issues:

1) I get a missing file error when running the install script, specifically `cp: cannot create regular file '/home/nick/.config/autostart/keyswap.sh': No such file or directory`. Here is the install script output if that helps:

```
➜ ./install.py          


                      K!nt◎
            - F!x the dɑmn kɐyb◎ɑrd. - 

Press Enter to begin...

What type of keyboard are you using? (If Mac and Windows then select Mac)
    1) Windows
    2) Chromebook
    3) Mac
3

Would you like to swap Command back to Super/Win and Ctrl key back to Ctrl when using terminal applications? (y/n)
Note: For a more mac like experience & less issues with terminal based interactions y is recommended.
y
Setting up mac keyswap as a service.
You can disable and remove the service by using the following command in the Kinto directory.
./uninstall.sh
cp: cannot create regular file '/home/nick/.config/autostart/keyswap.sh': No such file or directory
Created symlink /home/nick/.config/systemd/user/default.target.wants/keyswap.service → /home/nick/.config/systemd/user/keyswap.service.

An Apple keyboard with the hid_apple driver was detected.
Please run the following commands to swap alt/option and Command.
Your Kinto keymapping will not work right on Apple keyboards without it.

echo '1' | sudo tee -a /sys/module/hid_apple/parameters/swap_opt_cmd
options hid_apple swap_opt_cmd=1" | sudo tee -a /etc/modprobe.d/hid_apple.conf
update-initramfs -u -k all
```

The above was easily fixed with `mkdir -p ~/.config/autostart/` and rerunning the install script again.

However this brings us to problem 2.

2) The keys are not remapping correctly in mac gui environments, like firefox etc. In the gui environments, Ctrl is still Ctrl, Cmd seems to be Alt, and Alt seems to be Cmd.

I made sure that the service was running in the background, and still no dice. I then did some debugging and ran the following:

```
$ systemctl --user disable keyswap
$ systemctl --user stop keyswap
$ ~/.config/xactive.sh mac 12 0 none
```

I notice that when I go into xterm, the output from the above says `internal gui to term` but when I switch to firefox, the output says:

```
Error:            
  Can't find file "mac_gui" for types include
  Exiting
  Abandoning keytypes file "(null)"
```

Any Ideas?

PS. Let me know if I can provide anymore details :)

**Comment by rbreaves** [comment]
I think I had some type of weird regression or merge issue a few commits back, but thank you for being as detailed as you were. I believe I have resolved the issues you have outlined, I believe I accidentally referenced  the custom mac_gui file in the symbols directory for the term swap, when there should be no custom references at all.

I am really not entirely sure how that happened or how I wouldn't have caught it as I normally run back through my installer before updating the repo.

**Comment by rbreaves** [comment]
I closed this prematurely. The issue is now fully resolved with the latest commit.

https://github.com/rbreaves/kinto/commit/4346597613ef848eb6434b4f415a428a40c765cb

**Comment by nbrookie** [comment]
@rbreaves thank you! pulled and things are working beautifully! and thanks again for this project :heart:
