### ISSUE TITLE
Error in log - 'unknown': I need something more specific

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#608]
@rbreaves 

I don't think this was happening early on, but at some point during the process of making the screenshot script and launch commands work I started seeing this odd error in the GUI log output. It's just: 

```
sudo[digits]: 'unknown': I need something more specific
```

The screenshot commands all work fine but this is happening in the log every time I trigger one of the related keyboard shortcuts. 

![unknown_errors](https://user-images.githubusercontent.com/64876997/150313562-c4feb285-8938-40f6-8cb1-2f308f19409c.png)

I tried to grep in the `kinto-master` install folder and even in the whole `python3/dist-packages` directory for portions of the string "I need something more specific", but I couldn't find any file containing that string. At the moment I have no idea what process or binary is putting this error into the log, so I have no idea how to approach troubleshooting why it keeps showing up. 

Googling comes up with discussions related to the TERM variable or ttys. Adding variations of "env TERM=something" to the front of the runuser launch command results in things like [6B blob data] showing up in the log instead of the "unknown" error. 

```
    K("RC-Shift-KEY_3"): launch(
        ["env", "TERM=vt220", "runuser", "-l", _user, "-c", 
        _path + "screenshot.sh desktop"]),      # Cmd+Shift+3       # screenshot: entire desktop (all attached displays, macOS default)
```

If you have any ideas of how to get rid of these log messages entirely, put them here. 

Even with nearly identical commands, this isn't happening with the `beep.py` launch command. Only when calling the bash script. 

```
    K("RC-Shift-M-b"): launch(
        ["runuser", "-l", _user, "-c", 
        _path + "beep.py"]),                    # launch beepy error beep
    K("RC-Shift-KEY_3"): launch(
        ["runuser", "-l", _user, "-c",  
        _path + "screenshot.sh desktop"]),      # Cmd+Shift+3       # screenshot: entire desktop (all attached displays, macOS default)
```

**Comment by RedBearAK** [comment]
@rbreaves 

Think I figured it out. I have a debug option that clears the screen when I run the script in the terminal, so that the only thing on the screen will be the output from the script as I work on it. Apparently, running the script from the launch command results in something saying, "I don't know what screen you want me to clear since I'm not running in a TTY", or something like that. 

So, problem solved, I hope. I'll have to be careful running any command that expects there to be a TTY for output. Or test for empty `$TERM` variable perhaps.

**Comment by RedBearAK** [comment]
Final notes: 

The `unknown` comes from within the `$TERM` variable. A notification displaying the contents of the variable during the script run reveals that it actually contains the word "unknown". 

I noticed this when I tried to test for an empty `$TERM` variable, and it didn't stop the log error. So you have to test for length greater than zero and also test for TERM="unknown", before running any command that will expect to output into a terminal. 

```
debug="1"   # set to zero to disable
if [ $debug = 1 ]; then
    if [ ${#TERM} -gt 0 ] && [ ! $TERM == "unknown" ]; then
        clear
    fi
fi
```

Using this technique you can still run the script with debug enabled from within a terminal, and no more errors appear in the Kinto GUI log if the script is run from a `launch` shortcut.

**Comment by rbreaves** [comment]
Interesting, guessing you forked xkeysnail to play around with adding some additional functionality to xkeysnail itself? If you do come up with some useful additions just PR my fork of it and I will take a look at it over there. It is a bit sad but I don't think xkeysnail appears to be under much active development atm, been over a year since it's last PR was accepted.

The codebase I think is still plenty good though and is likely more easily expandable than the 2 up comers I am seeing, keyd, and xremap. Although I prefer the format of one of their configs over xkeysnail, something I was wanting to shift xkeysnail over to tbh, a less pythonic syntax & going yaml. If I just had a week or 2 of vacation time lol.

**Comment by RedBearAK** [comment]
@rbreaves 

> Interesting, guessing you forked xkeysnail to play around with adding some additional functionality to xkeysnail itself?

Don't know why you would say that? I'm just using the `launch()` command provided by `xkeysnail`. Somehow it or something else in the execution chain sets TERM="unknown" at some point, or maybe that's some kind of internal default value, leading to those messages in the log output. 

That's all I know about it what's going on here. The debug stuff is just from my screenshot script while I'm working on it.

**Comment by rbreaves** [comment]
Oh.. well I don’t guess I ever used launched & didn’t see it mentioned in their ReadMe was all.

**Comment by RedBearAK** [comment]
@rbreaves 

> Oh.. well I don’t guess I ever used launch & didn’t see it mentioned in their ReadMe was all.

It was not exactly obvious, at least to my eyes, until just a few days ago. And I have found precious few examples of anyone actually using it. It was like seeing the Monolith from 2001: A Space Odyssey outside my dining room window when I actually got it to work. Pretty sure I made a lot of inarticulate noises, threw a thigh bone of an ass into the air and watched it turn into an orbiting space station. 

But there is also mention in the Readme of running an “arbitrary command” and I’m not clear on whether `launch()` is what is meant by that. Have you ever had any luck running an arbitrary python command on the right side of the “K” function? Every time I try things that otherwise work outside of the keymap definition function it just crashes with python errors in the log.

**Comment by RedBearAK** [comment]
@rbreaves 

So you've never tried to do anything like this?

```
import beepy as beep
import subprocess

define_keymap(re.compile("some-app", re.IGNORECASE),{
    K("M-RC-Shift-b"):    beep.beep("error"),     # do a beep
    K("M-RC-Shift-r"):    subprocess.run("echo Test", shell=True),     # echo "Test" to shell (log)
})
```

I've tried many variations of something like this and it has never worked. Is it because the functions I'm trying to call are undefined inside the scope of the `define_keymap` or `K`? Or is this just not possible?

**Comment by rbreaves** [comment]
Unless I saw an indication of a K() like function alternative in the code I wouldn't know to try something different really. define_keymap can only accept so many types of payloads based on what it was programmed to do would be my assumption. Not sure I am using the right terminology tbh - but I don't exactly refer to things properly in pythonic terms any ways lol.
