### ISSUE TITLE
kinto messing with espanso

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#61]
I know it is maybe not an issue on your side, but [kinto](https://github.com/rbreaves/kinto) prevents [espanso](https://github.com/federico-terzi/espanso) from expanding text, so I am creating an issue in both repos. If kinto is not running espanso works like expected.

I don't know on which side the issue can be fixed and I really don't expect either of you to fix it, but perhaps one of you can look into it.

* [espanso issue](https://github.com/federico-terzi/espanso/issues/202)
* [kinto issue](https://github.com/rbreaves/kinto/issues/61)

Thanks

**Comment by rbreaves** [comment]
Thanks for letting me know.

May have just figured it out, I just restarted the espanso service after starting my service and it appears to be handling the gui and term keymaps fine now (they are very similar, but apparently different enough from the default setxkbmap that the espanso service needs to start after the kinto keyswap service.).

**Comment by rbreaves** [comment]
I was thinking this could be added as an init command to run after the kinto service starts, but the init type is designed to run just before Kinto makes its first keyswap, so to do that I would either need to move it to after it makes its first keymap active or add an option to delay an init command until after the first keymap is ran.

I am going to think on it for awhile, but a tweak could be added later designed as a way to help fix apps like espanso that may cache away information about your current keymap but then never check back in to see if they change.

The other option is to restart the service after each gui and term change by tacking on the restart into the run command of those 2 categories in the user_config.json file, but honestly I don't see any need for that, a single restart of the service after Kinto starts up and applies the first keymap appears to be enough in my testing.

**Comment by owzim** [comment]
@rbreaves restarting both services with kinto first works for me as an interim solution, thanks a lot!

**Comment by rbreaves** [comment]
@owzim I think just restarting or adding a startup delay to the espanso.service file would be sufficient.

Find the path to the service via something like
```
systemctl --user status espanso
```

Then edit that file by adding something like
```
[Service]
ExecStartPre=/bin/sleep 30
```

And the whatever the daemon-reload command is, I think it will prompt you after you save it, but if not an attempted restart without the daemon-reload will prompt you to run it and give you the command.

```
systemctl --user restart espanso
```

From there the work around would be more permanent.

**Comment by bigplayer-ai** [comment]
I have a similar issue on windows 11 23H2...
I don't know on which side the issue can be fixed and I really don't expect either of you to fix it, but perhaps one of you can look into it.

[kinto issue](https://github.com/rbreaves/kinto/issues/876) :[https://github.com/rbreaves/kinto/issues/876](https://github.com/rbreaves/kinto/issues/876)
[espanso issue](https://github.com/espanso/espanso/issues/2061): [https://github.com/espanso/espanso/issues/2061](https://github.com/espanso/espanso/issues/2061)
Thanks
