### ISSUE TITLE
Add "*terminal" to terminals list? 

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#612]
@rbreaves 

I noticed that around half of the terminals already on the terminals list, especially newer terminal apps, are developing the tendency to have a WM_CLASS of "something-terminal" (often with, sometimes without the dash character, but ending in "terminal"). 

Do you think it would be unsafe or unwise to just drop a (partially) fuzzy match into the terminal list for `"*terminal"`, to match anything new that comes along to fit this pattern? Obviously every now an then a terminal will need a couple of overrides because of unusual shortcut choices, but that doesn't seem to be very common. 

I hesitate to suggest something as short as `"*term*"` with a fuzzy match on both sides. That would probably match unwanted things. But I'm very interested in your opinion on `"*terminal"`. I feel like it will automatically catch a lot of new minor terminal variations and forks as time goes on, with a very low probability of accidentally applying to anything that is not explicitly a terminal app. 

Whachuthink?

**Comment by joshgoebel** [comment]
I think this is solving a non-problem and risks being too wide... "Trading terminal" might be for the for stock market, etc... it seems easy enough to just add these on a one-off basis.

**Comment by RedBearAK** [comment]
@joshgoebel 

> I think this is solving a non-problem and risks being too wide... "Trading terminal" might be for the for stock market, etc... it seems easy enough to just add these on a one-off basis.

Yeah, I kind of came to the same conclusion. Regex patterns are just too unpredictable. Although it would indeed catch several terminal apps. 

I'll close this.
