### ISSUE TITLE
update install docs for fedora

### ISSUE THREAD

**Issue by pwright** [rbreaves/kinto#619]
**Describe the bug**
On fedora, installation failed
**Expected behavior**
installation to just work

**fixed it with**

sudo dnf install python3-devel  # for python3.x installs

before running install

**Comment by RedBearAK** [comment]
@pwright 

You probably only needed `python3-wheel` and maybe `python3-evdev` rather than the entire `python3-devel` package, but yes, there are some issues getting through the install on Fedora. 

What version of Fedora? Which desktop environment variant?

**Comment by pwright** [comment]
@RedBearAK  Fedora 35, stock gnome

**Comment by RedBearAK** [comment]
@rbreaves 

This should be resolved with the distro detection fixed, right? Seems to be working in F34/F35/F36 VMs even when reverting back to a fresh install snapshot. 

Should be able to close this issue too, now that #660 has been resolved.

**Comment by rbreaves** [comment]
Indeed, it should be - although I may go back & drop the or & just make it a like match sorta thing - fedora*.
