### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by craigglennie** [rbreaves/kinto#62]
No issue here, just thanks for making this! I was trying to get a Hackintosh setup, but got frustrated and installed Ubuntu instead. Now using Kinto I have a keyboard layout that I'm used to. Happy days :smile: 

This issue should probably be closed or deleted so it doesn't create noise. Didn't know a better way to say thanks, though :)

**Comment by rbreaves** [comment]
It's all good, I'm glad to hear that you enjoy it! And yea, I also made it in part due to that reason myself lol. There's a lot of good hardware coming out there that it's not possible to hackintosh on and yet if you get the keyboard right - it really doesn't seem to too matter much!
