### ISSUE TITLE
Global shortcuts break when Terminal is active

### ISSUE THREAD

**Issue by sommerper** [rbreaves/kinto#621]
**Describe the bug**
This is probably an edge case but I thought I'd mention it in case there is an easy fix.
I have enabled the GNOME extension https://extensions.gnome.org/extension/1485/workspace-matrix/
I changed the global shortcut keys like so:
```
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Control><Alt><Super><Shift>Left']" && \
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Alt><Super><Shift>Right']" && \
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Control><Alt><Super><Shift>Up']" && \
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Control><Alt><Super><Shift>Down']" && \
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Alt><Super>Left']" && \
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Alt><Super>Right']" && \
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control><Alt><Super>Up']" && \
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control><Alt><Super>Down']"

```

Now I can move to workspaces in a grid using `<Control><Alt><Super>` plus an arrow key.
This works fine - except when I move to a terminal window.
Then the shortcuts start typing A, B, C, or D.
This happens in other terminals as well. (Like Tilix)
If I switch to a non-terminal app the shortcuts work again.

**Expected behavior**
Global keyboard shortcuts should work in all windows including the Terminal

**Install Type:** Bare Metal
**Distro:** Pop OS 21.10
**DE:** Gnome
**Branch:** master

**Comment by rbreaves** [comment]
Yea, that is a little difficult but not impossible to support. You have to remember that normal GUI apps have the keys relaid out in this order Super, Alt, RCtrl, Spacebar - etc & the Terminal apps use LCtrl, Alt, RCtrl, Spacebar, etc. The Super key goes away completely pretty much - might be some exceptions though.

To get what you want edit `~/.config/kinto/kinto.py` on line 728 `define_keymap(re.compile(termStr, re.IGNORECASE),{` and remap things like LC-M-RC-Shift-Left to C-M-Super-Shift-Left and so on, then restart Kinto and see if that works.

During terminal use the shift key will often get appended to most singular RCtrl- combos but I think you should be in the clear since you are pressing other modifier keys as well. (RCtrl which is the Cmd key during terminal usage transforms Cmd-T to Cmd-Shift-T as an example.)

**Comment by sommerper** [comment]
Thanks a bunch for the detailed reply. I noticed you have some info on that in the readme so I'll check that out and see if I can get it working.

**Comment by sommerper** [comment]
I worked it out by stopping the xkeysnail service and running the config like so
```
sudo systemctl stop xkeysnail
sudo xkeysnail ~/.config/kinto/kinto.py
```
Then I could see the keys pressed and wrote them into `~/.config/kinto/kinto.py`
Then started the service again
```
sudo systemctl start xkeysnail
```
This is the config that works for me
```
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("LC-LM-RC-LEFT"): K("LM-RC-LSuper-LEFT"),
    K("LC-LM-RC-RIGHT"): K("LM-RC-LSuper-RIGHT"),
    K("LC-LM-RC-UP"): K("LM-RC-LSuper-UP"),
    K("LC-LM-RC-DOWN"): K("LM-RC-LSuper-DOWN"),
    
    K("LC-LM-RC-LShift-LEFT"): K("LM-RC-LShift-LSuper-LEFT"),
    K("LC-LM-RC-LShift-RIGHT"): K("LM-RC-LShift-LSuper-RIGHT"),
    K("LC-LM-RC-LShift-UP"): K("LM-RC-LShift-LSuper-UP"),
    K("LC-LM-RC-LShift-DOWN"): K("LM-RC-LShift-LSuper-DOWN"),

...
```

Appreciate the help @rbreaves

**Comment by rbreaves** [comment]
I am kinda curious of what the original hotkeys were for the pop_os workspace matrix, but I assume they collide with other hotkeys any ways that may even be macOS specific. If it was not a matter of changing the system hotkey defaults I wouldn't mind adding it to Kinto - but I sorta draw the line at changing system level hotkeys (other than the singular Win/Super overlay key - I pretty well have to release that one during install. Uninstall does place it back though.).

Glad it is working for you!

**Comment by sommerper** [comment]
The default works space matrix can be seen here if you scroll down a bit https://github.com/mzur/gnome-shell-wsmatrix/wiki/Custom-keyboard-shortcuts
