### ISSUE TITLE
Remapping Menu key

### ISSUE THREAD

**Issue by KellieOwczarczak** [rbreaves/kinto#625]
I have my setup almost exactly how I want it, but because of how my keyboard is setup, I am trying to make one last tweak that is not taking for some reason. I want the menu key in the screenshot to actually be my Mac-like ctrl key. So, I edited the code to be what I think it should be
`Key.MENU: Key.RIGHT_META, `
But that does not seem to be taking. All of my other remaps are working. For instance the Control R is now Escape, and Escape is Print, etc. Just somehow Menu is not mapping to MENU. Any suggestions? (I am in Pop!_OS 21.10) I am probably missing something silly.

![Screenshot from 2022-02-17 21-39-54](https://user-images.githubusercontent.com/59445562/154607612-eecc75c1-5059-4ef9-bc6a-ca680d17bc43.png)

**Comment by ThemysciraData** [comment]
Yes, it is right where your original `Key.RIGHT_CTRL: Key.RIGHT_META,` was.

**Comment by rbreaves** [comment]
Menu key is not seen as a modifier.. so modifying xkeysnail will likely be required. You'll need to fork my fork of xkeysnail & recompile the install from there. Run this in the xkeysnail directory when you are ready `sudo pip3 install --upgrade .`


https://github.com/rbreaves/xkeysnail/blob/kinto/xkeysnail/transform.py#L138

**Comment by ThemysciraData** [comment]
Ok. Thanks, now, I think I see what I need to do. Should be straight forward. I will tinker with it in the morning.
