### ISSUE TITLE
Unable to install on Ubuntu 21.10

### ISSUE THREAD

**Issue by evprkr** [rbreaves/kinto#632]
Running both the new install method and old install method yield the same error:

```
Failed to get sesion path: Caller does not belong to any known session.
You are not using x11, please lgout and back in using x11/Xorg
```
I couldn't find any sort of compatibility list, but it seems unlikely this wouldn't support one of the most supported distros ever, right?

**Comment by rbreaves** [comment]
Support is fine - you are running wayland though so please log out & back in under X11.
