### ISSUE TITLE
How to File a Bug Report

### ISSUE THREAD

**Issue by rbreaves** [rbreaves/kinto#64]
Template

**Install Type:** Bare Metal or VM
**Distro:** Name + Version
**DE:** Gnome, XFCE, KDE
**Branch:** master, dev

If applicable include kinto log and the status of your input caret
```
cat /tmp/kinto/caret
journalctl --user-unit=keyswap.service -b
```

## The Problem
Describe your problem and any steps I might be able to take to reproduce your problem. If it only occurs with using a particular application then please include the name of that app as well (although it should be mentioned in your kinto log as well).

**Comment by Jonchun** [comment]
Probably convert this using [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) when you have time.

**Comment by rbreaves** [comment]
Thanks for the suggestion, I was unaware of that option. Kinda hope an extra click or two won't deter people from opening tickets, but I would like to guide people a little more so that I can actually address their issue. I've had a few to never follow back up with me, where if they had conversed with me I could have solved their problem pretty readily.

Now that the debug parameter has been added though that should really help accelerate things too.
