### ISSUE TITLE
How do i bind a key to a custom  character

### ISSUE THREAD

**Issue by Imeguras** [rbreaves/kinto#640]

**Comment by Imeguras** [comment]
... I might have misclicked enter or double clicked on the issue or something but i want to do something like  `K("M-KEY_4"): "§"`, but i don't know where americans place the §

**Comment by rbreaves** [comment]
Better question to ask the guys at xkeysnail than Kinto. Kinto is powered by it for Linux, and I maintain a slightly diverged fork from the main project as well. You will need to know the proper name for symbol most likely and might be discoverable by reviewing this file.

If it is not supported then someone or you may be able to add the symbol by knowing or finding out what the associated code is for it, just know that to see it show with Kinto you'd need to fork my fork of xkeysnail and use the Kinto branch on my fork. I do accept PRs if it has to go that far and so would xkeysnail, although that maintainer has not seemed very active in awhile. To be fair my development has slowed down a lot too, but Kinto is fairly feature complete, besides needing to make updates more graceful in letting users keep their changes better & doing some potential refactoring.

https://github.com/mooz/xkeysnail/blob/master/xkeysnail/key.py

My fork and branch
https://github.com/rbreaves/xkeysnail/blob/kinto/xkeysnail/key.py

Closing as this relates more to the underlying component that runs Kinto.

**Comment by rbreaves** [comment]
Also when you install Kinto there is a folder called xkeysnail which is my fork and branch of you, you can work from that and reinstall just xkeysnail to test your changes.

```
cd xkeysnail
sudo pip3 install --upgrade .
```

Of course you will need to edit ~/.config/kinto/kinto.py to include the symbol name and remapping once you figure that out.
