### ISSUE TITLE
xkeysnail service keeps exiting

### ISSUE THREAD

**Issue by steakscience** [rbreaves/kinto#644]
Hi,

I have just done an automated install. It doesn't seem to be working at the moment.

From looking at the debug logs, it looks like this 

![image](https://user-images.githubusercontent.com/2727095/161388721-4fe930d0-f3ce-4231-92fc-7e1439f91a9e.png)

**Comment by rbreaves** [comment]
Says you’re missing xhost, was supposed to install during the installer. Install the dependency & you should be fine.

**Comment by steakscience** [comment]
@rbreaves THANK YOU!

**Comment by steakscience** [comment]
@rbreaves Since you are also a Budgie user, do you have any recommendations for how to continue using Cmd to open the Budgie menu?

**Comment by rbreaves** [comment]
In compliance with macOS keybindings that would be Cmd-Space. I purposely disable the opening of any launcher from a single key modifier as macOS heavily relies on having all 3 modifiers accessible for actual key binding combos.

And glad that has resolved your issue.

**Comment by steakscience** [comment]
Ah, I see what you mean

Did you find a way to bind Cmd-Space to open the budgie menu? So far, I've tried adding <Super>Space to mutter overlay, but that didn't work

**Comment by rbreaves** [comment]
Ummmm Cmd-Space is supposed to work by default with Budgie.. although I think I may have only tested that on Ubuntu Budgie and Manjaro Budgie. If it is not set then you can easily do that via the keyboard settings on Ubuntu Budgie that you'd use to set any shortcut combo. You do not set the overlay key directly I don't think though, unless you want to unbind it or set a single modifier.
