### ISSUE TITLE
Is it possible to use different keyboard types?

### ISSUE THREAD

**Issue by steakscience** [rbreaves/kinto#653]
Kinto allows picking between different keyboard layouts (Windows, Apple, etc)

I'm using Kinto on a laptop (Windows layout), but I also sometimes use an external keyboard (Apple layout)

Currently, I have to manually switch layouts depending on which keyboard I am using.

Is it possible to assign each device a different layout?

**Comment by rbreaves** [comment]
If you are using an official Apple keyboard then yes - both Linux & Windows has the ability to support both.

Although Windows only supports the layout of the last known keyboard that was plugged in so not simultaneously unless you can figure out how to swap the Alt & Cmd/Win/Super key around on just that Apple keyboard first under Windows.

Linux has a default Apple keyboard driver for official keyboards so it can swap those keys via it’s own driver. This puts it in line w/ any other Windows keyboard & it gets it’s own “Windows & Apple*” mode as a result for anyone that wants to use both simultaneously.

Linux does have ways though of swapping keys on any specific keyboard on a very low level still via an app on GitHub called keytable. You can also use it if needed for non official apple keyboard if you use a Windows keyboard as well simultaneously.

I do the latter w/ some Windows keyboards but to make them align w/ the Apple layout.

```
#!/bin/bash
inputPath=$(hwinfo | grep -B1 "Microsoft_Surface_Type_Cover-event-kbd" | tail -2 | head -n1 | awk '{print $2;}')
sudo /usr/bin/keytable -k 0x700e3=56 --device $inputPath
sudo /usr/bin/keytable -k 0x700e2=125 --device $inputPath
inputPath=$(hwinfo --short | grep 'Brydge 12.3 Pro+ Keyboard' | awk '{print $1;}')
sudo /usr/bin/keytable -k 0x700e3=56 --device $inputPath
sudo /usr/bin/keytable -k 0x700e2=125 --device $inputPath
inputPath=$(hwinfo --short | grep 'Holtek USB-HID Keyboard' | awk '{print $1;}' | head -n1)
sudo /usr/bin/keytable -k 0x700e3=56 --device $inputPath
sudo /usr/bin/keytable -k 0x700e2=125 --device $inputPath
```
