### ISSUE TITLE
Previous install disables keyboard

### ISSUE THREAD

**Issue by adamcbrewer** [rbreaves/kinto#654]
**Describe the bug**
I was running Ubuntu 21.10 with Kinto working well and decided to upgrade to 22.04. After some unrelated bugs I decided to re-install Ubuntu 21.10 keeping my `/home` directory intact. Reinstalling Kinto worked, but as soon as the service starts no keyboard (bluetooth or plugged in) seems to work. Stopping the service returns functionality to the keyboards.

I've tried running the uninstall script successfully and re-installing, but no success; same issue. Running debug confirms the keys are being registered, but not making it though to the desktop or any applications.

**Expected behavior**

**Install Type:** Bare Metal
**Distro:** Ubuntu 21.10
**DE:** Gnome
**Branch:** master
**Commit:** curl script from 22.04.2022 

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnai

sudo systemctl status xkeysnail
× xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; disabled; vendor preset: enabled)
     Active: failed (Result: signal) since Fri 2022-04-22 18:16:42 BST; 980ms ago
    Process: 19657 ExecStart=/usr/bin/sudo /bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/adam/.config/kinto/killdups.sh && /usr/local/bin/xkeys>
    Process: 19794 ExecStop=/usr/bin/sudo /bin/bash -c /usr/bin/sudo pkill -f bin/xkeysnail && exit 0 (code=killed, signal=TERM)
   Main PID: 19657 (code=killed, signal=TERM)
        CPU: 99ms

Apr 22 18:16:42 Wintermute sudo[19794]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/sudo pkill -f bin/xkeysnail && exit 0
Apr 22 18:16:42 Wintermute sudo[19794]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 22 18:16:42 Wintermute sudo[19796]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/pkill -f bin/xkeysnail
Apr 22 18:16:42 Wintermute sudo[19796]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 22 18:16:42 Wintermute sudo[19794]: pam_unix(sudo:session): session closed for user root
Apr 22 18:16:42 Wintermute sudo[19796]: pam_unix(sudo:session): session closed for user root
Apr 22 18:16:42 Wintermute systemd[1]: xkeysnail.service: Control process exited, code=killed, status=15/TERM
Apr 22 18:16:42 Wintermute sudo[19657]: pam_unix(sudo:session): session closed for user root
Apr 22 18:16:42 Wintermute systemd[1]: xkeysnail.service: Failed with result 'signal'.
Apr 22 18:16:42 Wintermute systemd[1]: Stopped xkeysnail.
lines 1-18/18 (END)
```

**Additional context**
If it helps, I've install gnome-tweaks and extensions, but nothing that should modify anything related to keyboard functionality. I've modified some keyboard shortcuts as per default Ubuntu settings, but nothing crazy.

**Comment by rbreaves** [comment]
22.04 is untested by me at this moment but I will get to that soon.

**Comment by adamcbrewer** [comment]
Great, thank you, I really appreciate it. 10 years of osx muscle memory is
not easily unlearnt.

If it helps, the Ubuntu upgrade and downgrade was done on a separate
partition to /home. My thinking is there were issues installing Kinto after
the upgrade which left behind incompatible settings after the downgrade.
Might be simply be purging user settings would fix the issue, but I'm not
sure which files Kinto and its deps touch on the filesystem.

**Comment by rbreaves** [comment]
Just installed and run Kinto successfully on a fresh install of Ubuntu 22.04. I did have to switch over to using Xorg and not wayland, but that is expected atm.

Closing this ticket - not sure if the issue could be related to the upgrade, but my advice is backup your current ~/.config/kinto.py file - if you have made your own modifications to it and then uninstall kinto and re-install it.

**Comment by rbreaves** [comment]
Just to note I have made an update to day that fixes the system tray icon as it does disappear on the upgrade or fresh install. That should not occur now, the icon will be there on the latest.

**Comment by adamcbrewer** [comment]
Thanks for taking a loo at the @rbreaves. I'm pretty sure I switched to Xorg after the install, but just tried it and seems to work fine now.

**Comment by nixcraft** [comment]
Everything worked on **Ubuntu 22.04 LTS** fresh install except for Command–Space bar (SUPER+SPACE Bar).  How do I debug this one? TIA.

**Comment by rbreaves** [comment]
Hmmmm, I think I need to update Kinto in general. I do not reset Super to open the launcher menu even when Kinto stops running.

but yea I should be toggling this.

```
gsettings set org.gnome.mutter overlay-key 'super'
```

**Comment by hthmkhlf** [comment]
> 22.04 is untested by me at this moment but I will get to that soon. Make sure you’re still on X11 & not wayland.

@rbreaves not sure if this will be helpful, but I recently updated Pop_OS to 22.04 and for some reason several python packages were removed after the upgrade. Simply reinstalling xkeysnail via pip fixed the issue for me.

**Comment by nixcraft** [comment]
@hthmkhlf A compatible version of xkeysnail is bundled with kinto sh (git install method). That is the recommended way. However, back in 20.04 LTS, if you install xkeysnail using pip, it will break stuff. Not sure if the updated xkeysnail version under 22.04 LTS fixed it.

**Comment by rbreaves** [comment]
The packaged version of xkeysnail will still break stuff - primarily how some hotkeys are held will fail to work as what some xkeysnail users would expect would be broken behavior for Kinto.
