### ISSUE TITLE
Next word/previous word not working for Electron apps

### ISSUE THREAD

**Issue by bramirezMAP** [rbreaves/kinto#665]
Hi, I'm using Kinto on Ubuntu 22.04 with a Magic Keyboard and am struggling to have wordwise selection/navigation working for apps other than those apps that have been explicitly defined (e.g. IntelliJ, VSCode), especially Electron apps. The problem is that pushing Option causes the menu bar to activate which steals focus from the text box being edited.

There's an Alt-F19 hack already in place for VSCode:
```py
    # Wordwise remaining - for VS Code
    # Alt-F19 hack fixes Alt menu activation
    K("M-Left"): [K("M-F19"),K("C-Left")],                  # Left of Word
    K("M-Right"): [K("M-F19"),K("C-Right")],                # Right of Word
    K("M-Shift-Left"): [K("M-F19"),K("C-Shift-Left")],      # Select Left of Word
    K("M-Shift-Right"): [K("M-F19"),K("C-Shift-Right")],    # Select Right of Word
```
But when I make a new config entry for another Electron app (like Joplin), it doesn't seem to do anything - the menu bar is still activated.

Is this hack specific to a major version of Electron?

**Comment by rbreaves** [comment]
Well I don’t even use my own hack any more - I explicitly define what I need in the electron app if possible. There’s currently no solution for Linux based electron apps.

Closing as this is a duplicate, there are already tickets that discuss this to greater detail.

**Comment by rbreaves** [comment]
To be clearer - I dogfood this every day & I don’t use that specific code block for vscode.. I add sublime text to the vscode group & then apply the the sublime text remap extension to vscode & an additional keyboard remap file which is floating in the tickets to resolve what remains in vscode.

If some new discovery is made on how to fix the Alt menu issue w/ electron then it’ll get fixed & I’ll stop w/ custom fixing the app. (Although some hotkeys are not set at all by default).
