### ISSUE TITLE
Sticky and modmaps

### ISSUE THREAD

**Issue by joshgoebel** [rbreaves/kinto#679]
What if sticky had nothing to do with combos at all but was all about the modmaps... so you have:

```
define_conditional_modmap(lambda wm_class: wm_class.casefold() not in terminals,{
   Key.LEFT_META: Key.RIGHT_CTRL,  # Mac
```

Such that now there was some sort of sticky magic setup because of the modmap mapping... or would that be too narrow?

**Comment by rbreaves** [comment]
Maybe it is late, but I am not sure I am following what you are saying atm.

**Comment by joshgoebel** [comment]
I meant that the sticky binding (holding the keys on output so long as they aren't released on input) could perhaps depend on the modmap, but actually you do a LOT of other bindings later. so I'm thinking that might not be the best idea... plus I think we first need to answer the issue I just posted about the foundations switching out from under when in the middle of a tabbing (or other) operation.

**Comment by joshgoebel** [comment]
Closing this and referencing #681 so it's not lost.
