### ISSUE TITLE
Bring back Activity overview for the Super key after uninstalling kinto

### ISSUE THREAD

**Issue by felixding** [rbreaves/kinto#68]
Hi,

I disabled Super key for "Show the Activity overview" during kinto installation. How to bring it back after uninstalling it? `./uninstall.sh` and reboot didn't work.

**Comment by rbreaves** [comment]
I believe to map it back to both L R Super keys it would be the following

```
gsettings set org.gnome.mutter overlay-key. with. "['Super_L','Super_R']"
```

or try the reset command

```
gsettings reset org.gnome.mutter overlay-key
```

You can probably also go into your keyboard preferences and reset the the defaults from there too.

**Comment by rbreaves** [comment]
Can I ask if there was anything specific you were wanting out of Kinto that it was unable to provide? I'd like to work on improving it if there is something specific you were having problems with.
