### ISSUE TITLE
Help request: Initial configuration (or something is wrong?)

### ISSUE THREAD

**Issue by drmikecrowe** [rbreaves/kinto#680]
Hey @rbreaves -- I think I'm going to love Kinto when I work out some kinks!

Having a couple of issues that I'm trying to track down how to configure.  First, some background:  Running on Manjaro, had to uninstall/reinstall, and had some difficulty installing xkeysnail.  However, it all appears fine now (I think).  However, my problems may be symptoms of something not quite working correctly.  

First, when I check my keyboard, here's what I get (in case this is not what is expected):
![2022-06-01_21-00](https://user-images.githubusercontent.com/90312/171525907-38750b09-1f4b-4ccb-8bdd-1ac845f66acc.png)

## In VSCode 

- I cannot switch between tabs using Ctrl-Tab anymore.  Further, if I try and change the mapping using the VSCode UI, no key seems to register in the UI to allow me to change it.
- In the terminal, Tab is switching between windows, not doing tab'y things (like tab completion).

**Comment by RedBearAK** [comment]
@drmikecrowe 

Part of this almost sounds like a stuck modifier issue, like Tab switching windows by itself. Which can be cleared out by just cycling through all the modifier keys once or twice. 

But the right and left control key should be Super in GUI apps and Left Ctrl in terminals. So that’s pretty odd. 

A big piece of making Kinto work as expected is the built in shortcuts of the specific desktop environment. What DE are you using? 

And when you say you’re trying to use Ctrl-Tab to switch tabs, is that the physical keys?

**Comment by drmikecrowe** [comment]
> A big piece of making Kinto work as expected is the built in shortcuts of the specific desktop environment. What DE are you using?

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.6
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
GNOME Shell 42.1
GTK 3.24.34
(LMK what other details you'd like)

> And when you say you’re trying to use Ctrl-Tab to switch tabs, is that the physical keys?

Right -- so move between MRU tabs in VSCode (or Chrome for that matter).  Prior to Kinto, control-tab would cycle between most recent tabs in various applications (and my expectation is that would remain the same).

**Comment by drmikecrowe** [comment]
Also:

```log
~/.config/kinto 
❯ journalctl -f --unit=xkeysnail.service -b
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: Device               Name                                Phys
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: --------------------------------------------------------------------------
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: /dev/input/event26   Keyboard K780 Keyboard              9c:b6:d0:f0:48:1a
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: Device removed: Compx 2.4G Receiver
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: Okay, now enable remapping on the following new device(s):
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: --------------------------------------------------------------------------
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: Device               Name                                Phys
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: --------------------------------------------------------------------------
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: /dev/input/event26   Keyboard K780 Keyboard              9c:b6:d0:f0:48:1a
Jun 01 07:53:32 mike-xps15-9560 sudo[120006]: Device removed: Compx 2.4G Receiver
^C sudo systemctl stop xkeysnail && sudo pkill -f bin/xkeysnail && sudo xkeysnail ~/.config/kinto/kinto.py


~/.config/kinto [⏱ 2h9m7s]
❯  sudo systemctl stop xkeysnail && sudo pkill -f bin/xkeysnail && sudo xkeysnail ~/.config/kinto/kinto.py

██╗  ██╗██╗  ██╗███████╗██╗   ██╗
╚██╗██╔╝██║ ██╔╝██╔════╝╚██╗ ██╔╝
 ╚███╔╝ █████╔╝ █████╗   ╚████╔╝
 ██╔██╗ ██╔═██╗ ██╔══╝    ╚██╔╝
██╔╝ ██╗██║  ██╗███████╗   ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝
  ███████╗███╗   ██╗ █████╗ ██╗██╗
  ██╔════╝████╗  ██║██╔══██╗██║██║
  ███████╗██╔██╗ ██║███████║██║██║
  ╚════██║██║╚██╗██║██╔══██║██║██║
  ███████║██║ ╚████║██║  ██║██║███████╗
  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝╚══════╝
                             v0.3.0

No keyboard devices specified via (--devices) option.
xkeysnail picks up keyboard-ish devices from the list below:

-----------------------------------------------------------------------------------
Device               Name                                Phys
-----------------------------------------------------------------------------------
/dev/input/event0    Lid Switch                          PNP0C0D/button/input0
/dev/input/event1    Power Button                        PNP0C0C/button/input0
/dev/input/event2    Sleep Button                        PNP0C0E/button/input0
/dev/input/event3    Power Button                        LNXPWRBN/button/input0
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0
/dev/input/event5    Compx 2.4G Receiver                 usb-0000:00:14.0-2/input0
/dev/input/event6    Compx 2.4G Receiver Mouse           usb-0000:00:14.0-2/input1
/dev/input/event7    Compx 2.4G Receiver                 usb-0000:00:14.0-2/input1
/dev/input/event8    Compx 2.4G Receiver Consumer Control usb-0000:00:14.0-2/input1
/dev/input/event9    Compx 2.4G Receiver System Control  usb-0000:00:14.0-2/input1
/dev/input/event10   Intel HID events                    
/dev/input/event11   Intel HID 5 button array            
/dev/input/event12   PC Speaker                          isa0061/input0
/dev/input/event15   Integrated_Webcam_HD: Integrate     usb-0000:00:14.0-12/button
/dev/input/event13   Dell WMI hotkeys                    
/dev/input/event14   Video Bus                           LNXVIDEO/video/input0
/dev/input/event16   Video Bus                           LNXVIDEO/video/input0
/dev/input/event17   DLL07BE:01 06CB:7A13 Mouse          i2c-DLL07BE:01
/dev/input/event18   DLL07BE:01 06CB:7A13 Touchpad       i2c-DLL07BE:01
/dev/input/event19   HDA Intel PCH Headphone Mic         ALSA
/dev/input/event20   HDA Intel PCH HDMI/DP,pcm=3         ALSA
/dev/input/event21   HDA Intel PCH HDMI/DP,pcm=7         ALSA
/dev/input/event22   HDA Intel PCH HDMI/DP,pcm=8         ALSA
/dev/input/event23   HDA Intel PCH HDMI/DP,pcm=9         ALSA
/dev/input/event24   HDA Intel PCH HDMI/DP,pcm=10        ALSA
/dev/input/event26   Bluetooth Mouse 4.0                 9c:b6:d0:f0:48:1a
/dev/input/event25   py-evdev-uinput                     py-evdev-uinput

Okay, now enable remapping on the following device(s):

----------------------------------------------------------------------------------
Device               Name                                Phys
----------------------------------------------------------------------------------
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0
/dev/input/event5    Compx 2.4G Receiver                 usb-0000:00:14.0-2/input0

```

**Comment by RedBearAK** [comment]
@drmikecrowe 

I know you probably won’t want to use this as a replacement, but can you test Cmd-Shift-Braces for tab navigation, just to verify that it works? The square brackets keys on a standard US keyboard. 

Manjaro and GNOME should be a well-supported combination by the installer script. 

Still having the issue with Tab operating on its own after cycling modifier keys? 

Depending on the app, Ctrl-Shift-Braces already remaps to either Ctrl-Tab/Ctrl-Shift-Tab, or Ctrl-PgUp/PgDn. The misbehaving apps may need a new shortcut to remap Super-Tab since the physical Ctrl key is sending Super while Kinto is active.

**Comment by RedBearAK** [comment]
@drmikecrowe 

Yeah, Ctrl+Tab/Ctrl+Shift+Tab is not my preferred shortcut for tab nav, but it is working for me in Firefox and Chrome on Ubuntu 22.04 (GNOME). So the question becomes, why isn't it working for you? There is no specific remap in the config file for making Super+Tab/Super+Shift+Tab do Ctrl+Tab/Ctrl+Shift+Tab, so I'm not sure why both browsers are respecting the shortcut. 

I'll keep looking.

**Comment by RedBearAK** [comment]
@drmikecrowe 

So these lines in the "None referenced here originally" code block for general GUI apps take care of remapping Super+Tab/Super+Shift+Tab: 

```
    K("Super-Tab"): K("LC-Tab"),                  # Default not-chromebook
    K("Super-Shift-Tab"): K("LC-Shift-Tab"),      # Default not-chromebook
```

If the installer script didn't correctly identify the DE, you may not have the most appropriate lines enabled/disabled for GNOME in the config file. Can you look for those lines in `~/.config/kinto/kinto.py` and see if they are disabled with a `#`?

**Comment by RedBearAK** [comment]
@drmikecrowe 

If you still have the `kinto-master` folder in your Downloads folder, there is a script called `dename.sh` in `kinto-master/linux/system-config`. 

If you go into that folder in a terminal and run the script, it should spit out what it thinks the DE name is. It should say `gnome`. If it doesn't, that's the source of the problem most likely.

**Comment by drmikecrowe** [comment]
> If you still have the `kinto-master` folder in your Downloads folder, there is a script called `dename.sh` in `kinto-master/linux/system-config`.

`gnome`

> So these lines in the "None referenced here originally" code block for general GUI apps take care of remapping Super+Tab/Super+Shift+Tab back to doing the usual Ctrl+Tab/Ctrl+Shift+Tab:

OK, this is bizarre, but the following change totally fix this issue for me (the bottom two lines were active, top two weren't):

```
    K("M-Tab"): K("C-Tab"),                       # Chromebook/IBM - In-App Tab switching
    K("M-Shift-Tab"): K("C-Shift-Tab"),           # Chromebook/IBM - In-App Tab switching
    # K("M-Grave") : K("C-Shift-Tab"),              # Chromebook/IBM - In-App Tab switching
    #K("Super-Tab"): K("LC-Tab"),                  # Default not-chromebook
    #K("Super-Shift-Tab"): K("LC-Shift-Tab"),      # Default not-chromebook
```

**Comment by drmikecrowe** [comment]
So, my only remaining issue in VSCode is "Tab" -- Right now, tab is switching window elements and not feeding to the individual window (so in the editor it's not indenting, in terminal it's not auto-completing a partial filename, etc).

Is that something Kinto related?

**Comment by drmikecrowe** [comment]
> So, my only remaining issue in VSCode is "Tab" -- Right now, tab is switching window elements and not feeding to the individual window (so in the editor it's not indenting, in terminal it's not auto-completing a partial filename, etc).

I feel like a rube -- that's totally on me.  Ctrl-M (which I apparently pressed without realizing it) and then ignored the following status indicator was the cause (argh).  Thanks for all your help.
![2022-06-02_05-31](https://user-images.githubusercontent.com/90312/171601080-f4fb5d19-396e-494b-ac49-cb2010286c49.png)

**Comment by drmikecrowe** [comment]
It is. It identified it as an ibm layout though. No win key

**Comment by RedBearAK** [comment]
@drmikecrowe 

I tried with a Logitech K480 that I happen to have. In PC mode it was identified as "Windows", and in Mac/iOS mode it was identified as "Apple". Even if I put it in PC mode and pressed the first key to the left of the space bar instead of the second, it identified as "Apple". 

The K480 is very similar to the K780. Both keyboards have a key labeled "start" that should represent Win/Super key in PC mode. And that's the key you should be pressing whether you have it in PC or Mac mode. Which should lead to either "Windows" or "Apple" as a keyboard type. 

Other than having the user press the second key to the left of space, the installer doesn't really do anything else (that I know of) to detect the keyboard type. So I don't know what is going on with your K780. But I didn't write the installer. There may be something I'm missing. 

If I do `xbindkeys -k` with Kinto disabled, this is what I get for the Win/Super key on a PC laptop: 

```
"(Scheme function)"
    m:0x50 + c:133
    Mod2+Mod4 + Super_L
```

I'd try that with the K780 and see what the result is. It will be different with Kinto enabled. Something like this: 

```
"(Scheme function)"
    m:0x18 + c:64
    Alt+Mod2 + Alt_L
```

You may have to install `xbindkeys`.

**Comment by rbreaves** [comment]
> It is. It identified it as an ibm layout though. No win key

That'd create some issues... IBM layout is intended for keyboards without a Win/Super key only. It shouldn't trigger at all during the install unless your 2nd key left of the spacebar was Ctrl.. so I am even more confused on how Kinto would have identified it as IBM unless you were already remapping keys before installing Kinto.

**Comment by RedBearAK** [comment]
@drmikecrowe 

There are special shortcuts to force the K780 into a specific layout mode, in case it's not auto-detecting the right mode to use with your device: 

>If the keyboard fails to correctly detect the operating system of your device, you can manually select the operating system by pressing one of the following function key combinations for three seconds:

>Mac OS X and iOS
>Press and hold for three seconds
>fn + I (letter "i")

>Windows, Android, and Chrome
>Press and hold for three seconds
>fn + P

**Comment by drmikecrowe** [comment]
Hmmm, so, if I switch the K780 to Apple and use:

```
    K("Super-Tab"): K("LC-Tab"),                
    K("Super-Shift-Tab"): K("LC-Shift-Tab"),    
```

That gets me my in-app switching.  I think that's pretty close to what I want (though I think it's roughly the same as IBM + earlier changes).

Great, great program, thanks for this!
