### ISSUE TITLE
Sublime Text WM_CLASS on Arch is Subl/subl.

### ISSUE THREAD

**Issue by joshgoebel** [rbreaves/kinto#696]
Is there any reason you can't just bind the regex to the start and end? `^Subl$`, done... no excessive matches.  The PKGBUILD here (I looked again) installs a `subl` link to `sublime_text` in `/usr/bin`... the actual binary software (because it's binary I presume) is installed in `/opt`... so I assume perhaps the WM_CLASS is coming from the name of the link?  But this seems a pretty desirable thing to do to me (a `subl` shortcut for terminal use).

Is this setup handled differently on other setups?  Perhaps a wrapper script or something?  If there is a much better approach I could try to upstream it - otherwise I think match `^Subl$` would be pretty safe?

_Originally posted by @joshgoebel in https://github.com/rbreaves/kinto/issues/694#issuecomment-1152846042_

**Comment by joshgoebel** [comment]
```
# xprop
WM_CLASS(STRING) = "subl", "Subl"
```

**Comment by joshgoebel** [comment]
> Is there any reason you can't just bind the regex to the start and end? ^Subl$, done... no excessive matches. 

I've been wondering why this isn't done for many of the other regex...

**Comment by rbreaves** [comment]
In the case of Subl I feel more comfortable keeping that as a non-regex grouping simply because I quickly merged one for jetbrains I think it was awhile ago and it ended up catching another app somehow I forget. It did get updated to be much more specific though in response.. still a regex.

```
define_keymap(re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE),{
```

So yea, I am not against using regex's if I feel they are narrow enough to not create a problem, just not as certain about Subl*.

**Comment by joshgoebel** [comment]
I specifically asked about  `^Subl$` which only matchs "Subl" and nothing more... that's pretty narrow is it not?

**Comment by joshgoebel** [comment]
Do you have a `subl` binary on your system?

**Comment by rbreaves** [comment]
No, but if someone had Sublimation printing software or who know what that starts with Subl that could be an issue..

**Comment by joshgoebel** [comment]
No they wouldn't ^Subl$ matches only "Subl", period. Nothing else.

**Comment by rbreaves** [comment]
Oh, sorry, I thought were trying to do a wildcard thing lol.

**Comment by joshgoebel** [comment]
It's the soft link of `subl` that does it.... it just gets the name of the actual executable.

**Comment by rbreaves** [comment]
Adding '^Subl$' is simply unnecessary because 'Subl' is already an exact match, so I guess that is why I was confused on why you were making it a regex unless you were trying to turn into a wildcard or some sort of expression that is different than how it already interprets 'Subl' lol.

'^Subl$' == 'Subl' in this context already..

**Comment by joshgoebel** [comment]
Ah so you did, so I just missed it, Sorry my bad. :)

**Comment by joshgoebel** [comment]
> Adding '^Subl$' is simply unnecessary because 'Subl' is already an exact match, 

As a regex? Not at all.. it'll match anything as if it has ** on both ends.

**Comment by joshgoebel** [comment]
```
re.compile("Subl").search("And here we find the beautifulSublimation of things")
<re.Match object; span=(30, 34), match='Subl'>
```

**Comment by joshgoebel** [comment]
Your commit is fine, it gets the job done. :)

**Comment by rbreaves** [comment]
Oh, it's fine, you did make me question my own sanity though so I did a double check before saying what I just said because I was like.. wait.. let me remove a few letters on Sublime_text and see if my Sublime keymap still runs when I restart it lol.. Sure enough it stopped working so I was like good.. I am not crazy. 😂

**Comment by joshgoebel** [comment]
There is a chance that regex here is actually slower than just matching an array of strings (I've seen it happen)... but that can be a problem for another day. :-)

**Comment by rbreaves** [comment]
> As a regex? Not at all.. it'll match anything as if it has ** on both ends.

Doesn't match like that on regex101.com.

![image](https://user-images.githubusercontent.com/10969616/173172891-63777543-04e5-4f3e-856f-67494a35fb9c.png)

Only turns blue when that 4 letters take up the entire like.. from beginning to end which is what the ^ $ indicates.

![image](https://user-images.githubusercontent.com/10969616/173172913-2c0d0f99-7422-48c9-b02e-072cf3c2e72e.png)

**Comment by rbreaves** [comment]
I think you were thinking ^Subl$ = ^Subl.* - which oddly enough was how I was interpreting what you wanted all along even though I wasn't about to insert that in vs just adding a group.

I'd rather add `Subl` in the manner I did plus `^(?i)Sublime.*` to catch other possible names. (?i) might not be needed though as I am already specifying to ignore case.

**Comment by joshgoebel** [comment]
>Only turns blue when those 4 letters take up the entire line.. from beginning to end which is what the ^ $ indicates.

Yes, exactly.  Somehow we're talking past each other.  A regex of "Subl" is VERY non-specific, while a regex of "^Subl$" is very specific.

> I'd rather add Subl in the manner I did plus (?i)Sublime.* to catch other possible names.

I think now yuo're over thinking it because of one exception... :)

**Comment by rbreaves** [comment]
But Subl can't match anything but Subl.. like it won't match a string that has the value of startSublend.. It's equally specific as ^Subl$ as far as I know. Unless I am misunderstanding you I am think that you think 'Subl' is the equivalent to *.Subl.*.

But yea I think we have been talking past each other a little bit lol.

**Comment by rbreaves** [comment]
> I think now yuo're over thinking it because of one exception... :)

I won't lie.. it scares me 😂 - I didn't think the JetBrains regex could screw anything up and yet some other user found a "toolbox" exception.

**Comment by rbreaves** [comment]
Ok, so this what you think happens
![image](https://user-images.githubusercontent.com/10969616/173173449-8ae77c52-900b-40a4-afb1-15203eb08cc3.png)

but I am telling you that that is not how xkeysnail actually handles a regular word. Words automatically have the ^ and $ symbols added to them whether you see them or not. Like I haven't seen it exactly or recently any ways, but I know that that is how it functionally works.

**Comment by joshgoebel** [comment]
>  Words automatically have the ^ and $ symbols added to them whether you see them or not. 

You do that in your config, **but not everwhere.**

```
define_keymap(re.compile("caja", re.IGNORECASE),{
    # K("RC-Super-o"): K("RC-Shift-Enter"),       # Open in new tab
    K("RC-Super-o"):    K("RC-Shift-W"),        # Open in new window
},"Overrides for Caja - Finder Mods")
```

This would break, because you haven't pinned `caja`... I showed you the raw Python earlier... (just to make sure there was no weirdness in Python I"m not familiar with)

**Comment by joshgoebel** [comment]
Some places you check the lists... and that's an exactly match because that's how `in` works against a list:

```py
define_keymap(lambda wm_class: wm_class.casefold() not in terminals,{
```

**Comment by rbreaves** [comment]
> You do that in your config, **but not everwhere.**

Oh... ok now this is making more sense lol.. sorry apparently my brain has been fried today.. I do it the groups. that I create.

```
sublimes   = ["Sublime_text","subl"]
sublimeStr = "|".join(str('^'+x+'$') for x in sublimes)
```

Sorry that took so long for you to explain to me lol.

**Comment by joshgoebel** [comment]
> I do it the groups. that I create.

But not in all cases, would you like me to create a bug report for that?

**Comment by rbreaves** [comment]
Unnecessary, I am making the corrections now.

**Comment by joshgoebel** [comment]
You realize that if any of those were non-specific (prefix/sufficx) matches before that you just broke them, right? :-)  Hopefully that's not the case though.

**Comment by rbreaves** [comment]
> You realize that if any of those were non-specific (prefix/sufficx) matches before that you just broke them, right? :-) Hopefully that's not the case though.

Yea, I realize that.. and there may be modals within apps that could be impacted, but in general I would prefer the apps to large be exact matches. I will leave it in the hotfix branch for a day or so before merging it just to give myself time to dogfood it first. It is a large a change.

**Comment by joshgoebel** [comment]
> modals within apps 

That change the WM class?  Ugh... but I'm not fullly up to speed on how those things are decided yet... I know TITLE is more all over the map.

**Comment by rbreaves** [comment]
Also I guess some parts of my config are so old at this point (2 year going project now) I forget about some of the code I have introduced that changes the behavior or amends the regex symbols into the groups/lists.

**Comment by rbreaves** [comment]
> That change the WM class? Ugh... but I'm not fullly up to speed on how those things are decided yet... I know TITLE is more all over the map.

Actually maybe not.. I do know that I would actually like to turn off remapping on certain Window titles vs the wm_class. I think someone submitted a PR to xkeysnail for that feature but when I tested it it was buggy or didn't actually work if I recall.

**Comment by joshgoebel** [comment]
> I do know that I would actually like to turn off remapping on certain Window titles vs the wm_class.

My fork has all the background work done for that, just adding that isn't my highest priority.  It'd be trivial to do though.

https://github.com/joshgoebel/keyszer/issues/2

> until you go into your remote session.

Which would have a differnt window name?

> I forget about some of the code I have introduced that changes the behavior or amends the regex symbols into the groups/lists.

I'd suggest a little more sugar so it's impossible to forget there are modifications happening.

```py
define_modmap(matches(VS_CODES), {})
define_modmap(excludes(VS_CODES), {})
```

**Comment by rbreaves** [comment]
> I'd suggest a little more sugar so it's impossible to forget there are modifications happening.

Following you, but "syntactic sugar" is usually specific to the symbols being used in a language. Python is infamous for doing without much syntactic sugar compared to most languages such as javascript, php, etc ( aka { , } , : ) . But point taken - to use more well named methods.

I think through a lot of it I was just happy to get something working and I would often just run with it lol. Kinto has had a number of false starts with me over the years though before I ever named it or created this repo so I had plenty of time to think about how to lay much of it out even before I started writing the code at least and even then I still did a pretty major rewrite to port it from my C version into something compatible with xkeysnail.

And yes I look forward to trying out Kinto against your fork keyszner.

**Comment by joshgoebel** [comment]
> Following you, but "syntactic sugar" is usually specific to the symbols being used in a language.

I don't disagree.  I guess I'm thinking in terms of "configuration syntax" NOT "python syntax" I think in that sense it's syntactic sugar from a keymapper config language perspective.  But I wouldn't die on that hill, that's just how it's in my head.

> And yes I look forward to trying out Kinto against your fork keyszer.

So far the big blocker is that my suspended keys interfere with Cmd-click on touchpads... and the alternative is false positives on Alt and Super.... which I really thought I had cleverly fixed... ugh... works fine with a mouse though since the mouse clicks can just be routed thru the keymapper.

...and that we haven't 100% sorted out the sticky/bind key stuff... but I'm using my fork 24/7 now and quite happy with it (using a very lightly tweaked kinto.py).
