### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by serafeimgr** [rbreaves/kinto#699]
Is there a Wayland support planned?

**Comment by serafeimgr** [comment]
oh never mind, i found your post here

https://superuser.com/a/1466025

**Comment by rbreaves** [comment]
Oh wow that is old post - Kinto wasn't even using xkeysnail back then but a custom C app I wrote. Closing this ticket. The better discussion on this is here and a few other places. https://github.com/rbreaves/kinto/issues/447
