### ISSUE TITLE
Failed to start keyswap for Terminal and GUI.

### ISSUE THREAD

**Issue by rickdgit** [rbreaves/kinto#7]
Hi 
I installed kinto in Ubuntu 19.04 but the service status always be failed as screen shot below 
![Screenshot from 2019-08-15 21-00-07](https://user-images.githubusercontent.com/4945599/63138406-028d5480-bfa0-11e9-96dc-3afd688504ba.png)

Meanwhile my config
![Screenshot from 2019-08-15 21-03-39](https://user-images.githubusercontent.com/4945599/63138457-36687a00-bfa0-11e9-85a0-c2b2eaa9a3c0.png)

Please let me know for any suggestions!

Thanks!

**Comment by rbreaves** [comment]
hmm.. I have made an assumption that xprop is already part of your distro, but perhaps it is not. Try the following.

```
which xprop
```
If nothing comes back then let's trying installing it.
```
sudo apt update
sudo apt install x11-utils
```

If it is installed already then could you run xactive.sh directly and see what it spits out in your terminal when you change the focus from the terminal to any app and then back to the terminal one or more times?

```
~/.config/xactive.sh mac 0 0 0
``

**Comment by rbreaves** [comment]
I am going to go ahead and close this ticket. From the looks of it I was able to replicate the problem by renaming xprop, forcing Kinto to break and it does indeed break in the same manner.

If you install xprop via
```
sudo apt update
sudo apt install x11-utils
```

Then the problem will go away. I will later create a new, shell only, install script for Linux and that should resolve the issue completely.

**Comment by guoyiteng** [comment]
I also got this problem even if I did `sudo apt install x11-utils` (`which xprop` also returns correctly). Here is my output of `xactive.sh`:
```
1
internal term to gui
0
internal gui to term
```
FYI, after I started `xactive.sh`, the keyswap began working.

**Comment by rickdgit** [comment]
Hi,

I did the `sudo apt install x11-utils` the return indicates ` x11-utils is already the newest version 
(7.7+4).`

Then I execute the cmd got following response with the most recent repo.

> rickd-ubuntu% /bin/bash /home/rickd/.config/xactive.sh mac_only 0 0 0
> xprop: error: Invalid window id format: 0x0.
> 1
> internal term to gui
> 0
> internal gui to term
> xprop: error: Invalid window id format: 0x0.
> 1
> internal term to gui
> 0
> internal gui to term
> 1
> internal term to gui
> 0
> internal gui to term
> 1
> internal term to gui
> 0
> internal gui to term
> 1
> internal term to gui
> 0
> internal gui to term
> 1
> internal term to gui
> 0
> internal gui to term
> 0
> internal gui to term
> 0
> internal gui to term
> xprop: error: Invalid window id format: 0x0.

Besides, I'd like to confirm for the install script.

> What type of keyboard are you using? (If Mac and Windows then select Mac)
>     1) Windows
>     2) Chromebook
>     3) Mac
> 

Does 1. Windows indicates the windows keyboard layout such as regular office keyboard(108 keys. e,g, [amazon keyboard](https://www.amazon.com/AmazonBasics-KU-0833-Wired-Keyboard/dp/B005EOWBHC/))?
If Im using such kind of keyboard, I should select Windows.

Besides, 
![image](https://user-images.githubusercontent.com/4945599/64131014-81013900-cd8b-11e9-813a-1a7e581a1ac5.png)

Thanks!
