### ISSUE TITLE
Why the need to kill/search for other instances?

### ISSUE THREAD

**Issue by joshgoebel** [rbreaves/kinto#717]
https://github.com/rbreaves/kinto/blob/master/linux/xkeysnail.service

I see here that you're first running `killdups.sh` here... do you remember your experiences that led to adding/needing that?  I'm very curious why Systemd isn't isn't able to handle start/stopping a single process without getting confused... ie, I would think this would not be necessary... so I wonder if I'm missing something.

I plan to start running keyszer in systemd myself today or tomorrow but I thought I might just try and get out in front of this if I'm going to run into issues with duplicate processes....

_If this is a common problem I think keyszer itself should perhaps ship an official wrapper or build in tools to deal with this - but first I'm so curious why it's a problem at all._

**Comment by rbreaves** [comment]
I don’t recall the specifics but obviously I had some difficulty w/ systemd not actually killing the process as it should have & leaving it running so I just wrote a quick script to kill it. I really hated implementing that when I did as like you I figured I just did something wrong in systemd that resulted in that ugly hack.
