### ISSUE TITLE
Kinto wants old xkeysnail

### ISSUE THREAD

**Issue by tieugene** [rbreaves/kinto#729]
As I found Kinto installer downloads xkeysnail fork that is exact xkeysnail-0.3.0 snapshot.
Q: whether kinto not works with original xkeysnail-0.4.0?

**Comment by rbreaves** [comment]
It currently does not and there will be no plans to support it as I plan to switch over to keyszer in the near future, another fork of it, but one that solves many problems that Kinto would have with the current state of xkeysnail 0.4.x.

**Comment by joshgoebel** [comment]
@tieugene As far as I can determine xkeysnail seems to currently be unsupported and unmaintained. You can find my port here:

https://github.com/joshgoebel/keyszer
