### ISSUE TITLE
Keyboard does not receive any input after running the install script

### ISSUE THREAD

**Issue by Jstuff36** [rbreaves/kinto#755]
I'm not even sure how to go about debugging this, but after installing kinto.sh my keyboard no longer receives any input at all and I have to restart my computer to use the keyboard again.

The steps I took were
1) Run the install script ```/bin/bash -c "$(wget -qO- https://raw.githubusercontent.com/rbreaves/kinto/HEAD/install/linux.sh || curl -fsSL https://raw.githubusercontent.com/rbreaves/kinto/HEAD/install/linux.sh)"```
2) Press the 2nd key to the left of my spacebar per the GUI
3) It says the Kinto install is complete and Kinto.sh shell pops up, but my keyboard no longer works.

Does anyone have any advice on how to debug this? Thanks

**Comment by rbreaves** [comment]
Distro? Type of keyboard? Logged in under X11 or wayland? Kinto does not support wayland if wayland (installer is supposed to not work under wayland).

**Comment by squk** [comment]
This is also occurring for me. I'm using an Iris Rev 6(https://keeb.io/products/iris-keyboard-split-ergonomic-keyboard) keyboard. Logged in under X11. I'm using a Debian based distro internal to my company.

**Comment by rbreaves** [comment]
Typically you can run the Kinto GUI app & enable debug mode for more info. There’s other threads here too that mention how to manually set keyboards if needed. Logitech mx keyboards are one such keyboard.

**Comment by squk** [comment]
> Typically you can run the Kinto GUI app & enable debug mode for more info. There’s other threads here too that mention how to manually set keyboards if needed. Logitech mx keyboards are one such keyboard.

The debug console seems to indicate that xkeysnail is receiving all of my key events. However, the keyboard still doesn't type *anything*. The only solution is to SSH into the culprit device and kill xkeysnail or to reboot the device.

**Comment by rbreaves** [comment]
That is odd, w/ x11 being a check and the debug console showing input that would typically be enough.. in the xkeysnail.service file mentioned in the debug window.. I wonder if all of it is really running successfully or not. Particularly `xhost +SI:localuser:root` or perhaps the display variable is not set correctly.. if you echo out DISPLAY via `echo $DISPLAY` and compare that to what is in `xkeysnail.service`  file that may be different for some some odd reason.

I will admit this part of the app needs rewriting - was fairly difficult though already to get it to where it pretty well works with most distros I've thrown at it.. but some people have different setups or will log in to multiple users and that can complicate it as it can shift the DISPLAY value around.

**Comment by squk** [comment]
The display envvar was correct, and xhost set properly. I did this working today though! I updated xkeysnail to 0.4.0 instead of using the forked 0.3.0 thats bundled w/ kinto and the inputs started working. :)

**Comment by rbreaves** [comment]
Ummm.. that’s going to create some issues but maybe you’ll get lucky & not hit the shortcut remaps that aren’t going to work w/ 0.4.0..

I do need to finish the port to keyszer but 0.4.0 stripped out one of my commits as it conflicted w/ functionality that Kinto needs to properly handle all of its remaps.

**Comment by Mavamaarten** [comment]
I can confirm that I had the exact same issue.

For me it happened right after the upgrade to Ubuntu 22.10. Immediately after the update, my keyboard would not accept any input. Stopping kinto from the menu made my keyboard responsive again. I did an uninstall + reinstall of kinto and I had the same issue (same output as https://github.com/rbreaves/kinto/issues/761 ), but from the debug log and running xkeysnail myself I could see all my inputs appearing just fine.

I tried updating xkeysnail as hinted by @squk and that seems to resolve the issue, but some keys act a bit weird now (e.g. super + backspace to remove a word)

**Comment by martijnthe** [comment]
Just another anecdotal data point confirming what already has been said:

I'm running into the same issue on a clean Ubunto 22.10 install.
The `DISPLAY` var is set correctly, as well as the `xhost` args.
In the debug mode I see key events arriving though.
Installing xkeysnail 0.4.0 also worked for me to get around the issue of applications not receiving any input at all.

**Comment by rbreaves** [comment]
Added additional dependency for python3-tk, probably fixed now. Not checking for the latest as I believe this package pre-existed any ways.. just wasn't required previously for whatever reason.

**Comment by rbreaves** [comment]
Closing, but if this isn't resolved let me know and I will re-open it.
