### ISSUE TITLE
Cmd + Space launcher shortcut no longer working after upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by yaomtc** [rbreaves/kinto#756]
**Describe the bug**
I was using Ubuntu 20.04 with no issues with Kinto. Today, I've now upgraded to 22.04, and Cmd-Space no longer does anything.

**Expected behavior**
Cmd+Space should bring up the GNOME application launcher.

**Install Type:** Bare Metal
**Distro:** Ubuntu
**DE:** Gnome
**Branch:** master

Logs and status if relevant
```
xkeysnail v0.3.0: active (running) since 13min ago
sudo journalctl --unit=xkeysnail.service -b
```
```
Oct 04 16:10:25 uwork systemd[1]: Started xkeysnail.
Oct 04 16:10:25 uwork sudo[16580]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/user/.config/kinto/killdups.sh && /usr/local/b>
Oct 04 16:10:25 uwork sudo[16580]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Oct 04 16:10:25 uwork sudo[16582]: localuser:root being added to access control list
```
```
# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```
```
Command 'xkb' not found, did you mean:
  command 'xxkb' from deb xxkb (1.11.1-1)
  command 'gxkb' from deb gxkb (0.9.3-1)
  command 'xcb' from deb xcb (2.4-8)
Try: apt install <deb name>
```
Unit keyswap.service could not be found.
```
journalctl --user-unit=keyswap.service -b
-- No entries --
```

**Comment by rbreaves** [comment]
Line 541 - ~/.config/kinto/kinto.py - aka make sure that Alt-F1 launches the gnome Application menu, if it no longer maps there then report back to where it is mapping and maybe we can confirm that and make an update? I don't really understand why they would change that.

```
...
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Shift-Left_Brace"):   K("C-Page_Up"),         # Tab nav: Go to prior (left) tab
    K("RC-Shift-Right_Brace"):  K("C-Page_Down"),       # Tab nav: Go to next (right) tab
    K("RC-Space"): K("Alt-F1"),                   # Default SL - Launch Application Menu (gnome/kde)
    K("RC-F3"):K("Super-d"),                      # Default SL - Show Desktop (gnome/kde,eos)
 ...
```

**Comment by yaomtc** [comment]
For some reason 'Search' had no keyboard shortcut associated with it. Not sure if that's a change Ubuntu made, or just something wrong on my system. Either way it's fixed now, I set it to Alt+F1.

**Comment by jbankes** [comment]
Thanks @yaomtc - same problem here and was able to fix with this :beers:

**Comment by RedBearAK** [comment]
@jbankes 

You may notice that the “Search” shortcut is not a toggle, unlike the “Show the overview” shortcut, which brings up the same screen, or at least you can just start typing to perform exactly the same kind of search operation on the Overview screen. I think that’s why there is no default shortcut assigned. My Fedora system also had no shortcut for “Search”.
