### ISSUE TITLE
Shift+Tab does not register properly while Kinto is active

### ISSUE THREAD

**Issue by leftbones** [rbreaves/kinto#757]
Any Steam users out there have the same issue? The default shortcut to open the Steam Overlay is Shift+Tab, but while Kinto is active, this doesn't work. Suspending Kinto immediately fixes the problem, so I know it's Kinto.

Sometimes, if I holy shift and spam the tab key, I can get the overlay to open, but that's less than ideal. Is there any way to remedy this?

**Comment by rbreaves** [comment]
You can try adding whatever the Steam wm_class (if Linux) name is as part of the remotes group in the kinto.py file or the kinto.ahk file for Windows. I have not tested Kinto against Steam or any Steam games at all sadly and currently have no fix for auto turning it off during gameplay. Users simply have to turn off Kinto for now or find the name of the app window when it is active and add it under remotes.

I know I don't want remapping of any kind to happen during remote app usage, such as RDP and VNC so I would assume that you'd want to treat games the same way.

Closing ticket as I have nothing specific planned to resolve this currently, there are few prior convos and there may be something still open, but I am not sure.
