### ISSUE TITLE
Installation problem related to xkeysnail

### ISSUE THREAD

**Issue by nathalizator** [rbreaves/kinto#761]
OS : Kali linux
Running on a Macbook pro 2014 with Virtualbox

The installation is mark as completed but i can spot some error and the key map is not working even if i can see the "k" icon at the top.

I think its related to xkeysnail because in the kinto i can see xkeysnail.service code:killed and failed with result "signal"

- I have tried to uninstall kinto and xkeysnail
- Reinstall xkeysnail then kinto

Thank for your help
```
Kinto 1.2-13 build e106710
Type in Linux like it's a Mac.

Resetting Super_L, please wait...
Success.
xfce4-popup-whiskermenu has been set to Alt-F1 for Cmd-Space to work.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (9.2.0)
Using systemd...
localuser:root being added to access control list
fatal: le chemin de destination 'xkeysnail' existe déjà et n'est pas un répertoire vide.
Processing /home/kali01/kinto/xkeysnail
  Preparing metadata (setup.py) ... done
Requirement already satisfied: evdev in /usr/local/lib/python3.10/dist-packages (from xkeysnail==0.3.0) (1.6.0)
Requirement already satisfied: inotify_simple in /usr/local/lib/python3.10/dist-packages (from xkeysnail==0.3.0) (1.3.5)
Requirement already satisfied: python-xlib in /usr/local/lib/python3.10/dist-packages (from xkeysnail==0.3.0) (0.31)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->xkeysnail==0.3.0) (1.16.0)
Building wheels for collected packages: xkeysnail
  Building wheel for xkeysnail (setup.py) ... done
  Created wheel for xkeysnail: filename=xkeysnail-0.3.0-py3-none-any.whl size=17538 sha256=2aef1746bb094afb99deaffced625f24600a17c370cdd05ff3e1b609c0b652fc
  Stored in directory: /tmp/pip-ephem-wheel-cache-gzgu891l/wheels/26/ca/c8/c48661f705690149f6df5f7fe7eca027bb55e9c47acc9fb906
Successfully built xkeysnail
Installing collected packages: xkeysnail
  Attempting uninstall: xkeysnail
    Found existing installation: xkeysnail 0.3.0
    Uninstalling xkeysnail-0.3.0:
      Successfully uninstalled xkeysnail-0.3.0
Successfully installed xkeysnail-0.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv   
/usr/local/bin/xkeysnail                                                                                        
Service file added to /usr/lib/systemd/system/xkeysnail.service
Ownership set for root...
Permissions set to 644...
Created soft symlink...
ln: impossible de créer le lien symbolique '/etc/systemd/system/graphical.target.wants/xkeysnail.service': Aucun fichier ou dossier de ce type
Failed to create soft symlink for graphical target...
Removed "/etc/systemd/system/xkeysnail.service".
Adding xhost fix...

Kinto install is complete.

If the setup wizard fails to appear then please run this command.
~/.config/kinto/gui/kinto-gui.py
```
![image](https://i.ibb.co/s9NChRv/Capture-d-e-cran-2022-10-18-a-21-12-34.png)

**Comment by nathalizator** [comment]
Hello, is there any way to get help on this situation ?

**Comment by rbreaves** [comment]
I've not tested it under Kali - but you could try running debug under help and you might get more info or run the command manually from the xkeysnail.service file if you need to to glean more info.

**Comment by RedBearAK** [comment]
@nathalizator 

Kali needs additional package `gir1.2-notify-0.7` installed for the tray icon to work. Other than that, I had no issue installing Kinto on Kali with the default Xfce desktop. Works as expected, even after a reboot. But, it was running in a GNOME Boxes VM on a Fedora36/GNOME host. 

Tried the same thing in VirtualBox and it worked just as well. 

Kali is based on Debian Testing, according to their documentation, and Xfce is a common DE, so it's curious that there would be a problem like this. 

To get more info on what's going wrong with your setup, try stopping the `xkeysnail` service from the Kinto tray icon or GUI app File menu, and run this command in a terminal: 

```
sudo xkeysnail ~/.config/kinto/kinto.py
```

This is a simplified version of the command from the systemd xkeysnail service file. It may show a more obvious error when run in the terminal.

**Comment by yanksyoon** [comment]
Hi guys, I wrote a comment on how I solved it here:
https://github.com/rbreaves/kinto/issues/765#issuecomment-1302866279

In short, make sure your python is the system python during installation, when it fails during systemd xkeysnail thing, install tkinter by `sudo apt-get install python3-tk` and rerun the command

Hope this helps :)

**Comment by rbreaves** [comment]
Python3-tk has now been added.
