### ISSUE TITLE
Konsole sometimes Ignores input

### ISSUE THREAD

**Issue by rbreaves** [rbreaves/kinto#77]
This issue may occur less under 1.0.6 release, but it may still occur. I believe the issue to be a bug with how xkb or xkbcomp applies the keymap, this bug does not impact other applications from what I can tell.

Issue first reported by @jonchun in this thread. https://github.com/rbreaves/kinto/issues/69

**Comment by Jonchun** [comment]
This keyboard input being ignored seems to happen in albert occasionally as well. Likely the same issue.

**Comment by rbreaves** [comment]
Pretty sure I just resolved this one, but if you'd like to test it then let me know.. although if Konsole is segfaulting on you then you might not be able to :/.. Unless this happens to be the cause of the segfault and that would surprise me.

https://github.com/rbreaves/kinto/commit/16f8b237d596f08d7056c2f83fbdadb61c1f4fd9
