### ISSUE TITLE
Add RustDesk Support

### ISSUE THREAD

**Issue by aidan-gibson** [rbreaves/kinto#775]
I use RustDesk from macOS to remote into Linux. Kinto doesn't work under these circumstances ):

**Comment by rbreaves** [comment]
I don't know anything about RustDesk or the tech stack they use for Remote Desktop into Linux. The readme file should have references for how to use or compile x11vnc to work w/ Kinto when accessing over whatever VNC client you want to use however (Windows clients vary more in quality imo so probably less choices there).

I have no control over how others transmit their keys, if it's not raw input & they're sending it direct to X11 then there's nothing I can do. Better to ping the RustDesk devs on supporting transmitting raw keyboard input to the remote destination.
