### ISSUE TITLE
How to improve support for Thunderbird?

### ISSUE THREAD

**Issue by BenoitDuffez** [rbreaves/kinto#779]
In most apps, I can move the cursor with alt+left/right arrows to move one word while typing. Currently in Chrome, I can do this in this text box.

However, while writing an email in Thunderbird, this doesn't work. Alt still triggers the menu and then arrows don't move anything because the focus was lost to the menu bar.  
If I want to move words in Thunderbird, I have to use the same shortcut as if kinto wasn't installed: Ctrl+Arrows.

I read the config file but I don't understand where this is set. Can you help or show guidance on how to achieve the same behavior in Thunderbird as in other apps? Thanks

edit: elementary OS 6.1 / ubuntu 20.04
Keyboard: logitech K750 mac keyboard
thunderbird 102

**Comment by RedBearAK** [comment]
@BenoitDuffez 

The solution to this is most likely the same as the solution for Firefox, which is to disable the activation of the menu bar with the Alt key. You have to do this within the problematic application itself. 

Find a way to open the config editor in Thunderbird, like this: 

https://support.mozilla.org/en-US/kb/config-editor

Then set the preference responsible for the menu focus activation key to "false": 

https://support.mozilla.org/en-US/questions/1278533

```
ui.key.menuAccessKeyFocuses = false
```

This issue with the Alt key focusing the menu bar is a common problem with Firefox and a few other apps like VSCode and its variants.

**Comment by BenoitDuffez** [comment]
Haha, awesome. You just helped my muscle memory A LOT!
