### ISSUE TITLE
ALERT: Merge of #776 caused a bug in kinto.py

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#799]
@rbreaves 

The recent merge of the PR that replaces the rest of the instances of "M" with "Alt" accidentally caught a line that was using the letter "M" as part of the shortcut. So now a fresh install of Kinto is barfing on the line because it's just modifiers. 

Faulty line: 

```py
    K("RC-Alt"): K("C-Shift-Alt"),
```

Should be changed back to: 

```py
    K("RC-M"): K("C-Shift-M"),
```

**Comment by rbreaves** [comment]
Thanks
