### ISSUE TITLE
How to remap Alt + Space to launch a program

### ISSUE THREAD

**Issue by Smith-Chris1** [rbreaves/kinto#815]
If possible, I'd like to not launch the windows start menu with Alt + Space, I'd like that keyboard command to open Flow Launcher. I'm unsure how to map that in the settings. Is it possible?

**Comment by RedBearAK** [comment]
I'm not the Kinto dev, just a user. 

https://github.com/rbreaves/kinto/blob/99a8566262ce3cf488b13fdbdb7f04d156dac8af/windows/kinto.ahk#LL515C1-L517C1

```ahk
    ; Cmd+Space Alternative
    $^Space::Send ^{Esc}
```

These are the lines in `kinto.ahk` that seem to be remapping Cmd+Space. In this case it looks like it remaps to Ctrl+Esc. 

You can just comment out the line and put a new one in that remaps to whatever shortcut you set up for Flow Launcher to bind to.

**Comment by Smith-Chris1** [comment]
You are awesome - I thought that was the line too, but I was confused by the Esc. 

Anyways, I changed it to my Flow Launcher Shortcut of Alt+P:

`    ; Cmd+Space Alternative
    $^Space::Send ^{p}`

**Comment by behloolsabir** [comment]
I have a similar concern with Ubuntu. Could you advise me on the equivalent modification needed to turn it off?
