### ISSUE TITLE
arrow right stopped working after installing on kde neon 5.27

### ISSUE THREAD

**Issue by kvonspiczak** [rbreaves/kinto#820]
**Describe the bug**
Arrow right stopped working in any application/terminal/browser etc.

**Expected behavior**
Arrow right should continue working

**Install Type:** Bare Metal
**Distro:** kde neon 5.27
**DE:** KDE
**Branch:** master

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
```
```
● xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-07-24 11:17:35 CEST; 1h 10min ago
   Main PID: 20360 (sudo)
      Tasks: 2 (limit: 18878)
     Memory: 11.0M
        CPU: 16.212s
     CGroup: /system.slice/xkeysnail.service
             ├─20360 /usr/bin/sudo /bin/bash -c "/usr/bin/xhost +SI:localuser:root && /home/kvonspiczak/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kvonspiczak/.config/kinto/kinto.py"
             └─20362 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /home/kvonspiczak/.config/kinto/kinto.py

Jul 24 11:17:35 kde systemd[1]: Started xkeysnail.
Jul 24 11:17:35 kde sudo[20360]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c '/usr/bin/xhost +SI:localuser:root && /home/kvonspiczak/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kvonspiczak/.config/kinto/kinto.py'
Jul 24 11:17:35 kde sudo[20360]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Jul 24 11:17:36 kde sudo[20363]: localuser:root being added to access control list
```
```
sudo journalctl --unit=xkeysnail.service -b
```
```
Jul 24 11:17:35 kde systemd[1]: Started xkeysnail.
Jul 24 11:17:35 kde sudo[20360]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c '/usr/bin/xhost +SI:localuser:root && /home/kvonspiczak/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kvonspiczak/.config/kinto/kinto.py'
Jul 24 11:17:35 kde sudo[20360]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Jul 24 11:17:36 kde sudo[20363]: localuser:root being added to access control list
```

# xkb
systemctl --user status keyswap
`Unit keyswap.service could not be found.`

journalctl --user-unit=keyswap.service -b
`-- No entries --`

**Comment by RedBearAK** [comment]
@kvonspiczak 

I'm not the Kinto dev, but I used it for a long time and contributed a few things. 

Do you mean your right arrow key stopped working in all applications? Just the right arrow key by itself? 

What kind of keyboard do you have? 

I have no idea what would stop the right arrow key from working, unless it's some kind of compact keyboard where you have to do a chording shortcut to get to the arrow function.

**Comment by kvonspiczak** [comment]
> @kvonspiczak
> 
> I'm not the Kinto dev, but I used it for a long time and contributed a few things.
> 
> Do you mean your right arrow key stopped working in all applications? Just the right arrow key by itself?
> 
> What kind of keyboard do you have?
> 
> I have no idea what would stop the right arrow key from working, unless it's some kind of compact keyboard where you have to do a chording shortcut to get to the arrow function.

@RedBearAK yes exactly. The other arrow keys still work fine. I have this keyboard https://www.daskeyboard.com/daskeyboard-4-professional-for-mac/

**Comment by kvonspiczak** [comment]
okay forget what i said. I simply reinstalled kinto with the quck install instructions from the website and it works again :shrug:
