### ISSUE TITLE
How to use alt as command in windows ?

### ISSUE THREAD

**Issue by shpodg** [rbreaves/kinto#832]
the winkey is performed as command in windows11 after installed with config Apple keyboard type .  so why is winkey maped as command  and are not Mac style  and CapsLock cannot switch input methods either.

**Comment by RedBearAK** [comment]
@shpodg 

I'm not the Kinto dev, just a user of both the Linux and Windows versions of Kinto. 

If you have a "Win" key it means you have a "Windows" keyboard type from the perspective of Kinto's configuration settings, and that is what you need to set as the keyboard type, not "Apple". Kinto will then correctly remap the modifier keys so the shortcuts will react as if you were on an Apple keyboard. 

If you were actually using an Apple keyboard, you would want to set the keyboard type to "Apple" (if that doesn't happen automatically when you connect the Apple keyboard). 

Kinto is designed to make any of the keyboard types in the menu act like a Mac keyboard, you just need to make sure you tell it which keyboard type you have, so it can do the correct remaps of the modifier keys. 

Not sure about the CapsLock issue. In macOS input switching is done with physical Ctrl+Space or Shift+Ctrl+Space. There are preference options to turn CapsLock into Cmd or a combined Esc/Cmd key, but I don't see how that's relevant to input switching like macOS.

**Comment by shpodg** [comment]
@RedBearAK 
Thank you very much for explaining how to use the software. I now switch to the Windows keyboard and it is the expected usage. 
Perhaps my statement is inaccurate. It's not about switching input methods by CapsLock, but about switching input modes, such as Chinese and English.

**Comment by RedBearAK** [comment]
@shpodg 

>  Perhaps my statement is inaccurate. It's not about switching input methods by CapsLock, but about switching input modes, such as Chinese and English.

I think that is what they call input sources on macOS, but I'm not really familiar with all the terminology. They seem to call them input methods on Linux, which is where I spend most of my time. 

What matters is whether you can set up a shortcut for this in Windows, using the tools built into Windows. Maybe Windows will let you set CapsLock as the key to switch the input modes, or you'll have to set a different shortcut and then look at the AutoHotkey documentation to see if you can remap a CapsLock tap onto another shortcut. 

Kinto uses AutoHotkey to do the key remapping on Windows, and it can do almost anything you can think of. But unless using CapsLock to switch input modes is a common shortcut for that on macOS, it is kind of outside the scope of what Kinto does by default, and you'll have to customize your `kinto.ahk` config file to make it work. (If Windows doesn't let you just use the CapsLock key as the shortcut already.)

**Comment by shpodg** [comment]
@RedBearAK Thank very much. You have solved all my questions.

**Comment by shpodg** [comment]
resolved
