### ISSUE TITLE
Can I detect Kinto if Synergy is being used w/ a remote desktop?

### ISSUE THREAD

**Issue by josephlavin** [rbreaves/kinto#835]
First off: thank you for making this software!  I'm switching from MacOS to Linux and it is such a huge help! My muscle memory thanks you.

I'm trying out [Synergy](https://symless.com/synergy): a app that lets you seamlessly switch between two different computers as if it is another monitor.  The main computer acts as a host for the keyboard and mouse. It then remotely controls the keyboard/mouse on the remote machine. In my case: the host is my Linux box (Pop! OS) running Kinto.  I'm thinking the keyboard manulation being applied by Kinto is throwing off the keyboard presses being sent via. Synergy.  Is it possible to setup a conditional in the Kinto Config file that simply disables all keyboard press changes if the app being used in Synergy?

Thanks again!

**Comment by RedBearAK** [comment]
@josephlavin 

I have a variant of Kinto in another repo and I would also like to figure this out. Hopefully the solution will be equally applicable to Kinto. If you are up for some back and forth on this, please open an issue here: 

https://github.com/RedBearAK/toshy

**Comment by josephlavin** [comment]
I found this in the config file:

https://github.com/rbreaves/kinto/blob/6f42c68e4b9d2988bd26aafcc42640cc63057fa7/linux/kinto.py#L117-L121

Setting it does the trick... mostly. (Since I'm running Pop! OS disabling the SUPER key is causing other issues.) But the comment is pretty self explanatory.  They are releasing a new version so perhaps the WM_CLASS situation has changed.  I'll dig around a bit more and if I can figure something out I'll open a PR.

Thanks again!
