### ISSUE TITLE
How to actually use kinto to really mimic a Mac Keyboard?

### ISSUE THREAD

**Issue by smileBeda** [rbreaves/kinto#841]
... for example alternative characters
... for example the right option key
... for example the fn key

My main concern right now is that i cannot write any umlaut characters, special characters, anything that worked on MacOS keyboard even despite of the US layout, does simply not work on linux end (using Gnome Xorg).

It does not help that Gnomes inbuilt settings for these (alt chars etc)t options are all but clear, or working, or recognising the Kinto-modified keybard keys.

Does anyone here have any tips how I can at least get my umlauted U, A, O back?
(I cannot type them here, I refer to these characters: https://en.wikipedia.org/wiki/Umlaut_(diacritic))

Thanks to anyone who has a tip. I went through the similar issues on this repo already and they just don't make sense on a macbookpro laptop, we do not have a numpad, for starters...

**Comment by RedBearAK** [comment]
@smileBeda 

I'm not the Kinto dev, but I've been using and contributing to it a for long time, and made my own project based on Kinto, called Toshy. 

There are several different aspects of this. At the most basic, Kinto has an option in the tray icon or GUI app menu to stop modmapping the right-side modifier keys next to the Space bar (Cmd on an Apple keyboard, or Alt on a PC keyboard). Once you enable that option and restart Kinto, you should be able to use the right Alt key (or the Option/Alt key on an Apple keyboard) as the Alt_Gr key to get to the level3/4 characters. 

Next aspect is that you won't find those Mac-style special characters on the keyboard unless you choose a "Macintosh" keyboard layout in the GNOME keyboard settings. If you pick the right keyboard layout and then make sure the Alt_Gr key is enabled in the GNOME keyboard settings, you should be able to get the special characters like you would on the equivalent Apple keyboard layout. But it will only work with the key on the right side. 

In my own project I implemented a different way of getting to the Option-key special characters, and it works with the key on both sides of the keyboard in the position equivalent to Option/Alt, and works with a normal keyboard layout, even if you don't choose the "Macintosh" variant. But only the standard US and the ABC Extended keyboard layouts special characters are available. 

The keymapper used by Kinto and the fork used by Toshy can also have some issues with non-US keyboard layouts. Characters or shortcuts that get remapped by the keymapper can come out as if you were typing on a US layout unless you edit the key definition file. 

This is a slightly complex subject. One of the reasons I split off Kinto and created Toshy was to use the fork of the keymapper with support for Unicode character input sequences, for those special characters. The other main reason was that I was able to add some Wayland support to the keymapper fork. 

If you want to talk more about this you can open an issue on the Toshy repo, even if you want to continue to use Kinto. 

https://github.com/RedBearAK/toshy/issues/

**Comment by smileBeda** [comment]
Thanks @rbreaves for the reply and the hint to Toshy, I feel inclined to try it.

But before I do, what do you mean with 
> Next aspect is that you won't find those Mac-style special characters on the keyboard unless you choose a "Macintosh" keyboard layout in the GNOME keyboard settings. If you pick the right keyboard layout and then make sure the Alt_Gr key is enabled in the GNOME keyboard settings, you should be able to get the special characters like you would on the equivalent Apple keyboard layout. But it will only work with the key on the right side.

I have no such option. Layouts can only change in terms of language, not maker (see screenshot below)

I did choose `apple` when I did install the system (EndeavourOS T2 kernel). But that I cannot change anywhere anymore.
![Screenshot from 2023-12-15 11-22-22](https://github.com/rbreaves/kinto/assets/11800236/221b2c52-261d-4b77-b2c9-796960c934fb)
![Screenshot from 2023-12-15 11-23-18](https://github.com/rbreaves/kinto/assets/11800236/197d0e27-05c0-4586-9401-481a7f6869aa)

On this mac, which has an US layout (`qwertyuiop` and `zxcvbnm,./`), when using macOS, I can easily trigger an `u` with the umlauts by doing the modifier key + letter in question (u in this case), release, and type letter again.
If I recall right the modifiers in macOS where `shift+alt(left`, but it has been a while.

In any case, I am confused about the above... and, you are saying if I uninstall kinto, and install toshy, this will "just work"?
Then I might as well just spare me the hassle and try Toshy.

**Comment by smileBeda** [comment]
.... answer my own question by removing kinto and installing toshy. Works like a charm. **** Congrats and thanks for that project.
