### ISSUE TITLE
How to enable ALT + L to insert @

### ISSUE THREAD

**Issue by opensource21** [rbreaves/kinto#842]
On German-Apple-Keyboard the @ is defined via ALT + L. 
Furthermore the special combinations for [{ PIPE is missing.
Any hints how to fix this?

**Comment by RedBearAK** [comment]
@opensource21 

Linux or Windows?

**Comment by opensource21** [comment]
Sorry for forget the detail
Linux Ubuntu 22

**Comment by RedBearAK** [comment]
@opensource21 

The keymapper operates below the level of the part of the system that knows what the keyboard layout/language is. This can cause difficulties with keys or shortcut combos that get transformed by the keymapper, if you are not on a US keyboard layout. 

But, if you're only talking about the level 3/4 characters you get to with the Alt_Gr key on international keyboards, Kinto has an option that can disable the remapping of the keys on the right side of the Space bar, so international characters still be available with the Alt_Gr key. Check the tray icon menu or the menus on the Kinto GUI app window to enable this, and restart Kinto. 

If you're talking about combos that get remapped and are producing the incorrect character, you'd have to find and edit the `key.py` key definition file to match the key codes to the actual symbols on the keyboard. That can get complicated, and in some cases the config file would also need to be modified to match your new symbol names (if they don't exist in the standard US layout).

**Comment by opensource21** [comment]
Thanks for the explanation. I found a good solution. Use kinto for the shortcuts and use German mac keyboard layout in the keyboard settings.
