### ISSUE TITLE
Kinto install has failed with setup.py: error: unrecognized arguments: egg_info --egg-base

### ISSUE THREAD

**Issue by lucaslgr** [rbreaves/kinto#855]
**Describe the bug**
I've tried to install kinto using the old and new method and for both I got this error:
```bash
➜  kinto git:(master) ./setup.py 

Kinto 1.2-13 build 4a3bfe7
Type in Linux like it's a Mac.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (9.2.0)
Using systemd...
localuser:root being added to access control list
Cloning into 'xkeysnail'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 116 (delta 70), reused 94 (delta 62), pack-reused 0
Receiving objects: 100% (116/116), 35.81 KiB | 1.88 MiB/s, done.
Resolving deltas: 100% (70/70), done.

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --break-system-packages

Kinto install has failed.

cd into ./xkeysnail
Run 'sudo pip3 install --upgrade .' to debug issue
```

As recommended I ran this command below to debug the issue:
```bash
➜  kinto git:(master) ✗ sudo pip install --upgrade .          
Processing /home/lucaslgr/Downloads/kinto
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 2
  ╰─> [2 lines of output]
      usage: setup.py [-h] [-r] [--remove]
      setup.py: error: unrecognized arguments: egg_info --egg-base /tmp/pip-pip-egg-info-8i2x3p4n
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I have no idea what is going on 🤔 

**Expected behavior**
A successful instalation.

**Install Type:** I've followed both in the guide for linux.
**Distro:** Ubuntu + 22.10
**DE:** Gnome
**Branch:** master
**Commit:** The current commit from master.

**Comment by lucaslgr** [comment]
@RedBearAK  I saw that you had the same problem, Am I right?

**Comment by lucaslgr** [comment]
Also these are all python and pip locations and versions:
![image](https://github.com/rbreaves/kinto/assets/30275723/18162022-04eb-422d-978e-f7a169ec1b54)

**Comment by RedBearAK** [comment]
@lucaslgr 

The Kinto installer has been having issues for a while now with distros that have been moving to using a "managed Python environment". I don't know specifically how to solve this particular error, other than the notes on other issues about trying to use `pipx` to install the cloned version of `xkeysnail` that Kinto needs. 

I maintain my own significantly different fork of Kinto called Toshy, with a very different install process that doesn't have these issues (uses a Python `venv`), works in some Wayland environments, uses a different keymapper utility, and supports a wide range of distro types, including all recent versions of every flavor of Ubuntu except Ubuntu Kylin. 

It's here if you want to try it out: 

https://github.com/RedBearAK/toshy

You haven't gotten Kinto installed, but if you did you'd need to stop it and disable its auto-start option, or they would conflict with each other over accessing the `uinput` device.

**Comment by rbreaves** [comment]
I will try and rebase the installer on 23.10 and move things over to the managed Python environment as I do do agree w/ RedBearAK - Linux distros have moved towards a more self contained install environment for Python in general. I also have not slowed down enough to try out Toshy but I believe RedBearAK has put in the work to yes fork this project and bring it to Wayland environment which I appreciate as that is another area I have not been able to dedicate time towards.

**Comment by lucaslgr** [comment]
First of all thank you both guys @rbreaves and @RedBearAK, I understood the issues that you've explained here and I appreciate your help a lot. I'll try to use the toshy app here.

**Comment by lucaslgr** [comment]
Thank you guys, toshy worked very well for my distro!
