### ISSUE TITLE
Support for Polish language/characters

### ISSUE THREAD

**Issue by kgorol** [rbreaves/kinto#86]
**Is your feature request related to a problem? Please describe.**
I cannot type Polish characters like ą,ć,ś,ę... etc.

**Describe the solution you'd like**
Add support for Polish language.

**Describe alternatives you've considered**
n/a

**Additional context**
How can user help in making this happen?

**Comment by rbreaves** [comment]
Can you provide me with the contents of these two files? I want to make sure we're dealing with the right language region first off as the keymap is, in theory is supposed to be laid on top of whatever your region language is that you had set during the install.

Also are you expecting to type polish the same way you would under linux or macOS? I won't be implementing a hover over for accented letters any time soon, and that may be a separate project, if it ever comes at all. (I have found some potential ways to do it though.)

```
cat ~/.xkb/keymap/kbd.mac.gui
cat ~/.xkb/keymap/kbd.mac.term
```

Mine look something like this
~/.xkb/keymap/kbd.mac.gui
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete+mac_gui(addmac_levels)"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

~/.xkb/keymap/kbd.mac.term
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete+mac_term(addmac_levels)"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+altwin(alt_super_win)+mac_term(mac_apple)+mac_term(mac_global)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

**Comment by kgorol** [comment]
My output for both files:
```
[kamil@kamil-pc]$ cat ~/.xkb/keymap/kbd.mac.gui
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete+mac_gui(addmac_levels)"       };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+pl+inet(evdev)+altwin(ctrl_alt_win)+mac_gui(mac_levelssym)" };
        xkb_geometry  { include "pc(pc105)"     };
};
[kamil@kamil-pc onedrive]$ cat ~/.xkb/keymap/kbd.mac.term
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete+mac_term(addmac_levels)"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+pl+inet(evdev)+altwin(swap_alt_win)+mac_term(mac_win)+mac_term(mac_global)" };
        xkb_geometry  { include "pc(pc105)"     };
};
```
Well I expect it to work with any existing combination such as ALT+s = ś.
On macOS it it OPTION+s = ś.

I have Manjaro Linux with English language, but with Polish keyboard. Maybe that is the problem?

**Comment by rbreaves** [comment]
@kgorol I don't know, I mean if it worked on your keyboard under Manjaro Linux before applying Kinto my hope would be that it'd continue to work without much or any additional configuration/modification.

I do see that pl is listed in your files instead of my us, so I'd have thought it'd carry over the polish accents in the expected manner. I have an english keyboard but I will see what happens when I apply the polish config to it, both normally and while running kinto.

**Comment by rbreaves** [comment]
@kgorol So I just added the Polish language as an additional input method on my Ubuntu 19.10 install and I set it to pl in the top right corner of my task try like area as well and re-ran my kinto installer. Once I did that I was able to use the Right Alt (compose key) just as you normally would under linux to type in accented characters of your chosen language, so as far as I can tell Kinto does not interfere with the normal operation of Alt Gr for various languages.

I am even able to toggle between US and PL just fine while Kinto is running as well, so it looks like multi-language support does work - but all of your language Input Methods will likely need to be set before installing Kinto or you'll need to reinstall Kinto on top of itself.

I do not believe it would make sense to add the compose key to the left side of the keyboard, but in theory one could place the actual Alt key on the right side and the Alt Gr key on the left side if they wanted to. I am concerned that if I attempted it that I might create conflicts with other apps, hotkeys and it could make xkb modifiers more complicated as I don't think it is possible to have the compose key to also act as an alt key.

It might be possible to remap alt+e or alt+s, a or whatever specific letters to release the alt key and use compose instead in the symbols file.. but that does risk hotkey issues again and it would vary with the language (specific characters).

If you wanted to fork the dev branch you could certainly give it a go yourself.

There are 2 files you would want to focus on.

Add a compose key entry to "symbols[Group1]" & "actions[Group1]". I know you will use a redirectkey entry on actions, but not sure of the new key value to redirect to, you can read the readme on pulling out the characters and their values if you want.

https://github.com/rbreaves/kinto/blob/dev/.xkb/symbols/mac_gui

```
...
    // Ctrl + A - Beginning of Line
    replace key <AC01> {
        type[Group1]= "ONE_LEVEL_SUPER",
        symbols[Group1]= [
            // Base
            a,
            // Shift
            A,
            // Super
            NoSymbol,
            // Shift Super
            NoSymbol
        ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            RedirectKey(key=<HOME>,clearmods=Super),
            RedirectKey(key=<HOME>,clearmods=Super)
        ]
    };
...
```

The main catch is how do you add the compose key to the types file? It would add a 5th level to this which should be able to be added.
This article might suggest how to do it, some testing would need to occur.
https://wiki.archlinux.org/index.php/X_keyboard_extension#Compose_key

﻿https://github.com/rbreaves/kinto/blob/dev/.xkb/types/mac_gui
```
...
﻿    type "ONE_LEVEL_SUPER" {
        modifiers = Shift+Super;
        map[Shift] = Level2;
        map[Super] = Level3;
        map[Shift+Super] = Level4;
        level_name[Level1] = "Base";
        level_name[Level2] = "Shift";
        level_name[Level3] = "Super";
        level_name[Level4] = "Super Shift";
    };
...
```

**Comment by kgorol** [comment]
Thanks for your reply. I think I have everything set up correctly with my Manjaro setup, but since it works for you under Ubuntu I guess it must be something off with my system setup.

Writing Polish characters with just right alt would be fine, no need to remap it on the left side.

**Comment by rbreaves** [comment]
Just tested it out on the latest master under Manjaro KDE 19.04 and it seems to work fine for me. Uses the right Alt key all the same, once I set it for pl.

<img width="722" alt="Screen Shot 2020-04-06 at 12 18 53 AM" src="https://user-images.githubusercontent.com/10969616/78525290-5bfafb80-779c-11ea-963a-8dfb584e655b.png">
