### ISSUE TITLE
How to use press Control key after enabling Kinto for Macbook Pro 2015 with LinuxMint 21.3 Cinanamon installed

### ISSUE THREAD

**Issue by HuangJiaLian** [rbreaves/kinto#862]
I can press `control` key to show where my cursor is before turning on the Kinto in Linux Mint. 
<img src='https://github.com/rbreaves/kinto/assets/17427791/21a2ebf6-f340-4d31-9164-0bd33c0b9889' width='50%' />
The problem is I can't  trigger `control` anymore, even though I tried `cmd`, `fn` and `option` after enabling Kinto.  

**How can I keep using the above feature (trigger single `control`) after turning Kinto on ?** 

Thank you for your assistance.

**Comment by RedBearAK** [comment]
@HuangJiaLian 

Question: Does it work if you happen to be using a terminal emulator app, when you press the physical Ctrl key? 

Also, if you stop Kinto, does the Ctrl key on the right side of the keyboard also show the cursor position? Or only the Ctrl key on the left side?

**Comment by HuangJiaLian** [comment]
Thanks for your reply. No, it still didn't show the cursor position when I use system Terminal app. There's only left Control on my keyboard, and it works when I stop Kinto. 

Now, I'm using [this](https://askubuntu.com/a/766216/1106807) solution, which makes left cmd work like left Control. I can use the feature by pressing left cmd.

**Comment by RedBearAK** [comment]
> Now, I'm using this solution

@HuangJiaLian 

If I understand correctly that will only give you a small fraction of the total functionality of the Kinto config remaps. Kinto's config does much more for many apps than just move modifiers around.
