### ISSUE TITLE
fatal: destination path 'xkeysnail' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by Rivoks** [rbreaves/kinto#863]
**Describe the bug**
Hello, I am trying to install Kinto on Ubuntu 22.04.4 LTS. I get an error during the installation:
`/bin/bash <( wget -qO- https://raw.githubusercontent.com/rbreaves/kinto/HEAD/install/linux.sh || curl -fsSL https://raw.githubusercontent.com/rbreaves/kinto/HEAD/install/linux.sh ) -r`

I get:
```
Kinto 1.2-13 build 4a3bfe7
Type in Linux like it's a Mac.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (9.0.1)
Using systemd...
localuser:root being added to access control list
fatal: destination path 'xkeysnail' already exists and is not an empty directory.

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --break-system-packages

Kinto install has failed.

cd into ./xkeysnail
Run 'sudo pip3 install --upgrade .' to debug issue

``

**Expected behavior**
A clear and concise description of what you expected to happen.

**Install Type:** Bare Metal
**Distro:** Ubuntu 22.04.4 LTS
**DE:** Gnome, XFCE, KDE
**Branch:** master
**Commit:** 4a3bfe7

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
# Unit xkeysnail.service could not be found.

sudo journalctl --unit=xkeysnail.service -b
# sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
# Unit keyswap.service could not be found.

journalctl --user-unit=keyswap.service -b
# -- No entries --
```

Thank you for your support.

**Comment by krbaio3** [comment]
I have successfully installed the program using the old installation method outlined in the project's documentation (https://github.com/rbreaves/kinto?tab=readme-ov-file#old-install-method). I needed to read through setup.py and xkeysnail_service.sh to understand what was causing the failures. My initial step was to install (or reinstall) python3-pip. Next, I went to the xkeysnail repository and installed the dependency with: sudo pip3 install xkeysnail.

My environment uses GNOME, as indicated by the output of "dename.sh", which required an additional dependency: sudo apt install python3-tk. The last dependencies to install were setuptools and wheel via pip3 install setuptools wheel, which I had already installed previously.

The final step was to rerun setup.py, which was successful.

**Comment by RedBearAK** [comment]
> Next, I went to the xkeysnail repository and installed the dependency with: sudo pip3 install xkeysnail.

@krbaio3 

That installs the wrong version of xkeysnail. Your Cmd-Tab and other shortcuts that require holding a modifier key down will not work correctly until you reinstall xkeysnail from the folder the Kinto installer clones during install.

**Comment by cjambrosi** [comment]
I have the same problem in Ubuntu 22.04 
=/

**Comment by cjambrosi** [comment]
@Rivoks  Try the following.
- Using the terminal, go to where kinto was downloaded (example: `/Downlads/kinto-master`);
- Access the directory `./xkeysnail` and run the command `sudo pip3 install --upgrade .`
- The terminal must open signaling that the service is **active**. In the **Keyboard** menu option, select **Apple**.

This worked for me. This is the first time I've used it, so I believe this is how it should work.

**Comment by Rivoks** [comment]
@cjambrosi Thank you that works!
