### ISSUE TITLE
Command + L, keeps logging me out of my Windows machine when using Kinto from MacOS to Windows 11 Machine via Jump Desktop RDP

### ISSUE THREAD

**Issue by bigplayer-ai** [rbreaves/kinto#875]
**Describe the bug**
When using Kinto on Windows 11 machine, Remote control from macOS to control a Windows 11 machine via Jump Desktop RDP, pressing **Command + L** logs me out of Windows instead of performing the expected action of focusing the address bar/go to location (similar to **Ctrl + L** in Windows). This behavior occurs in applications like File Explorer and Microsoft Edge.

**Expected behavior**
Pressing **Command + L** should remap to the Windows equivalent of **Ctrl + L**, which focuses the address bar in browsers or File Explorer, instead of triggering a log-out.

**OS:** macOS (local) connecting to Windows 11 Pro N (remote)  
**Branch:** master

Logs and status if relevant  
N/A – occurs in a remote and local desktop scenario (both)

**Screenshots**  
This is a keyboard shortcut-related issue:  
![Screenshot 2024-09-15 at 20 50 32](https://github.com/user-attachments/assets/1a140ba9-50c5-4561-a560-63f1067a65fb)

**Additional context**  
The issue happens specifically when using Jump Desktop RDP from macOS to a Windows 11 machine with Kinto running and Jump Desktop's key conversion disabled. The **Command + L** shortcut incorrectly logs out the session instead of focusing the address bar on windows 11 machine

**Comment by bigplayer-ai** [comment]
Fixed it by adding this to kinto.ahk:
```
#IfWinNotActive ahk_group remotes
    ; Remap Command (Win) + L to Control + L
    #l::Send ^l
    ; wordwise support
```

**Comment by bigplayer-ai** [comment]
This bug is still relevant, @RedBearAK only when using Jump Desktop from macOS connecting to Windows... How can I fix this issue, you got any idea? using Apple keyboard

On local windows machine without any remote or anything the workaround I mentioned worked correctly... using Windows Keyboard.

**Comment by RedBearAK** [comment]
@bigplayer-ai 

I left a comment on issue #877.
