### ISSUE TITLE
Restore default Windows 11 Alt-Tab behavior

### ISSUE THREAD

**Issue by anrelps** [rbreaves/kinto#879]
Maybe i'm being dumb but i haven't found a way to have the default alt-tab behavior instead of just cycling through the windows

**Comment by RedBearAK** [comment]
@anrelps 

Can you be more specific about what you mean by the "default Alt+Tab behavior" and how that's different from "cycling through the windows"? Isn't that what Alt+Tab has always done on Windows?

**Comment by anrelps** [comment]
My bad, I just found out it was because I had a registry hack on my Windows to have the legacy Alt-Tab menu. Kinto now works as expected once I went back to the modern Alt-Tab menu.
